### ISSUE TITLE
clang src/main.c:219:13: warning

### ISSUE THREAD

**Issue by mike402** [fanglingsu/vimb#108]
src/main.c:219:13: warning: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)'
            snprintf(xid, LENGTH(xid), "%u", (int)vb.embed);
src/main.c:219:13: note: please include the header <stdio.h> or explicitly provide a declaration for 'snprintf'

**Comment by fanglingsu** [comment]
Closed out of inactivity. If this is still an issue for you, please feel free to reopen it.
