### ISSUE TITLE
Allow to configure path for history, cookie, ... files in config

### ISSUE THREAD

**Issue by fanglingsu** [fanglingsu/vimb#129]
Allow to change the path to following files in `$XDG_CONFIG_HOME/vimb/`

- cookies
- closed
- history
- command
- search
- bookmark
- queue

This would it make easier to run different vimb session. But I'm not sure it this is an overkill for vimb, because it's up to the user to write a script and to change the `$XDG_CONFIG_HOME` to run vimb with a different environment.

**Comment by j1r1k** [comment]
I have implemented profile name parameter which kind of addresses this issue. However it creates completely separate environment (also config, scripts etc.). I guess it is up to user to link those on filesystem level if desired.

Also cache and sockets are separated.

**Comment by fanglingsu** [comment]
Pretty nice patch!
