### ISSUE TITLE
Some clickable elements don't respond

### ISSUE THREAD

**Issue by QuantumNemesis** [fanglingsu/vimb#134]
I love your project here, but there's one big problem that I keep running into when browsing various websites. Some clickable elements don't respond to being clicked on or followed as a hint. I have seen this on two popular websites so far:
- Google. Clicking search suggestions is impossible; it is only possible to arrow-down to the suggestion you want. Also, when viewing a search page, the Settings gear icon in the top right corner is not clickable.
- Craigslist. The view mode links/buttons at the top don't work (list/thumb/gallery/map). Note that the newest/$$$/$$$ buttons *do* work. I noticed that the buttons that don't work seem to use HTML page anchors somehow (I'm not a web dev so I'm not sure how this is implemented), while the working buttons use form parameters.

This might have something to do with JS? Interestingly, both of these websites work fine in Vimprobable2 (the basis for vimb, I thought?), as well as every other WebKit browser I've tried.

**Comment by mike402** [comment]
Some time ago, yes. Now everything seems to work.

**Comment by mike402** [comment]
Some time ago, yes. Now everything seems to work.

**Comment by mike402** [comment]
Some time ago, yes. Now everything seems to work.

**Comment by mike402** [comment]
Some time ago, yes. Now everything seems to work.

**Comment by mike402** [comment]
Some time ago, yes. Now everything seems to work.

**Comment by mike402** [comment]
Oops. Apologies for the spam, GitHub is freaking out... :(
