### ISSUE TITLE
Mapping mouse buttons

### ISSUE THREAD

**Issue by dantleech** [fanglingsu/vimb#142]
Is it possible to map the "forward" and "back" mouse buttons?

**Comment by MichaelMackus** [comment]
@dantleech any progress on this? I'm considering opening a PR myself since mouse back button would be great.

**Comment by dantleech** [comment]
No, I no longer have a mouse with back/forward buttons so this has fallen off of my todo :)

**Comment by fanglingsu** [comment]
Closed because of long time of inactivity.
