### ISSUE TITLE
url hints by letters

### ISSUE THREAD

**Issue by serpent7776** [fanglingsu/vimb#145]
vimb supports hinting with numbers. I suggest adding support for hinting by letters. They are easier to type and there are 26 of them instead of only 10.
I really like how it's implemented in vimium: extension for chromium

**Comment by JacksonGariety** [comment]
@fanglingsu is there a way to enable this feature?

**Comment by fanglingsu** [comment]
@JacksonGariety You don't have to enable it, you can still set the `hintkeys` to be used for hinting.
```
set hintkeys=sdfghjkla
```

**Comment by JacksonGariety** [comment]
@fanglingsu the man page makes sense now, thanks!
