### ISSUE TITLE
hsts / redirect problem

### ISSUE THREAD

**Issue by semarie** [fanglingsu/vimb#146]
Hi Daniel,

I encounter an issue with hsts: it don't catch all possibles cases for url rewrite, and it is possible to by-pass it.

Here an example:
- first, visit https://www.eff.org/ in order to see the HSTS header one time at least.
- now, if you go to http://www.eff.org/ you will be redirected to https version
- now, go to http://bit.ly/1zZ4fzo it is a shorten url for http://www.eff.org/

vimb don't redirect to https version, and you arrive on the http version.

**Comment by fanglingsu** [comment]
@semarie Our hacky solution creates additional entries in webkits back/forward history list like mentioned in referenced issue.

**Comment by semarie** [comment]
I'm not sure to be able to provide alternate solution which works for HSTS... a possible workaround would be to have a (temporary) setting for configure if HSTS should be enable for redirect, and if setted, which don't call the `webkit_web_frame_load_uri` part. But it would complexify the vimb code.

**Comment by fanglingsu** [comment]
I'm not sure, but maybe we can identify the main request that load the entire pages html by using [soup_message_get_first_party](https://developer.gnome.org/libsoup/stable/SoupMessage.html#soup-message-get-first-party). If this would be possible, we could do the `webkit_web_frame_load_uri`, else the requeueing of the soup request should be sufficient.

But might be that the first party stuff is also true for pages loaded in (i)Frames, which is normally the case for social media links.

If you have some spare time, I'll invite you to check if this works.

I suggest to do further discussions in #172.
