### ISSUE TITLE
:eval! -- js works on command line but crashes vimb when used in keybinding 

### ISSUE THREAD

**Issue by sdothum** [fanglingsu/vimb#160]
Just discovered vimb (coming from luakit whose development has been dormant for many years now) and finding it quite a delight. I played with a readable javascript from http://readable.tastefulwords.com/#

I can execute the js from the command line ":e! ..js snippet.." and it works beautifully -- web page is made *readable*. but when I use it in the vimb config with "nnoremap Z :eval! ..js snippet.." and apply the keybind to a web page, the browser closes (crashes?.. actually there doesn't appear to be any visible output from "vimb 2>>error.log" other than

java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (Arch Linux build 7.u75_2.5.4-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

Any ideas?

As an aside, is there anyway to use surf's "simplyread.js" with vimb?

**Comment by fanglingsu** [comment]
Can you provide an example JS-snippet that causes the crash and the keybind that cause this?

> As an aside, is there anyway to use surf's "simplyread.js" with vimb?

You can put such scripts in the `$XDG_CONFIG_HOME/vimb/scripts.js` file that's sourced on each opened page.

**Comment by sdothum** [comment]
The keybind.. (tried "Q", will try others while I am at it..)

nnoremap Z :eval! (function(){_readableOptions={'text_font':'quote(Lucida Grande), quote(Lucida Sans Unicode), sans-serif','text_font_monospace':'quote(Courier New), Courier, monospace','text_font_header':'Molengo','text_size':'16px','text_line_height':'1.625','box_width':'30em','color_text':'#000000','color_background':'#FBF5E6','color_links':'#009900','text_align':'normal','base':'web_readability','custom_css':'h1, h2, h3, h4, h5, h6 { color #333333; }'};if(document.getElementsByTagName('body').length>0);else{return;}if(window.$readable){if(window.$readable.bookmarkletTimer){return;}}else{window.$readable={};}window.$readable.bookmarkletTimer=true;window.$readable.options=_readableOptions;if(window.$readable.bookmarkletClicked){window.$readable.bookmarkletClicked();return;}_readableScript=document.createElement('script');_readableScript.setAttribute('src','http://readable-static.tastefulwords.com/target.js?rand='+encodeURIComponent(Math.random()));document.getElementsByTagName('body')[0].appendChild(_readableScript);})()

I did see the "scripts.js" but I wouldn't want to apply the readable script to every opened page..

Thanks!

**Comment by fanglingsu** [comment]
OK, I can reproduce this. So I hope we can fix this soon. But it might also be a WebKit JavaScript bug like in #157.

**Comment by sdothum** [comment]
Thank you for the quick fix! Given the size of the snippet, your suggestion to put it in the scripts.js works just fine for me.. as I don't at the moment have anything else defined in it, so loading it on each page is no big deal. (Actually, I have started hacking simplyread.js which executes much faster than *readable*).
