### ISSUE TITLE
inputbox not hidden on startup with :input_autohide=true

### ISSUE THREAD

**Issue by sdothum** [fanglingsu/vimb#162]
Nit picking here.. the inputbox autohides after the 1st action but on startup is unhidden. On a rare occaision, the input box is unhidden, such as when filling in a form (but not always and is rare enough that I don't notice it till it is too late to remember the prior event sequence). Uncertain whether these 2 cases are related -- to the inputbox check not being performed late enough in a cycle.

**Comment by fanglingsu** [comment]
Confirmed, the inputbox is shown even if `input-autohide=on` is set in config file. I think this is cause because the settings are applied before the widgets are realized so that the later call to `gtk_widget_show_all` shows also the inputbox. I'll try to fix this soon.
