### ISSUE TITLE
opening downloaded files?

### ISSUE THREAD

**Issue by kdart** [fanglingsu/vimb#168]
Hello. I'm really liking vimb overall. But I'd like it to automatically open downloaded files, such as pdf files. But I can't seem to get it to work.

I have this in the config:

	au DownloadFinished *.pdf shellcmd! open-download

Which calls a shell script:

	#!/bin/bash
	
	URL=$VIMB_URI
	#URL="$@"
	# XXX
	logger "$URL : $VIMB_TITLE"
	exit

	URL=${URL//*\//}

	if [ -n "$URL" ] ; then
		 exec xdg-open "$HOME/Downloads/$URL" >/dev/null 2>&1
	fi

But the VIMB_URI is set to the original page, not the just downloaded URL. Same
with the title. Is there a better way to do this?

**Comment by fanglingsu** [comment]
We should think about a way to provide the url of the download to the scripts. At the moment there is no clean way to get the url of the download in case the download is done by webkit.

But maybe you can get the file with the latest creation date out of the downloads directory. This would also work in cases when the filename is changed by webkit or by you for the download.

Another way for doing this would be to use the external download mechanism (see `download-command` and `download-use-external` setting). But note that the autocmd event is not triggered for this, so you have to launch the xdg-open right after the download is finished.

**Comment by kdart** [comment]
Cool, thanks. I'll try the external download settings. 

Another way might be to just set up a inotify watcher process on the Download directory. Then we don't have to do anything. :)

**Comment by fanglingsu** [comment]
Oh, right maybe I should advice this hint with the inotify watcher on the project page.
