### ISSUE TITLE
TLS Mutual Auth Seems to be Unsupported

### ISSUE THREAD

**Issue by torrancew** [fanglingsu/vimb#169]
Hi,

I have a few sites I access which require client certificates for TLS mutual authentication. Unfortunately, I cannot find a way to provide these certificates to vimb. Am I overlooking a setting?

**Comment by fanglingsu** [comment]
This feature is not provided by webkit or libsoup as I know. In webkit2 exists a way to get informed about such an authentication request to hook in and allow the user to select the right certificate. But there is no way to do this in vimb at the time.

**Comment by torrancew** [comment]
@fanglingsu thanks, I came to a similar conclusion last night while looking at webkitgtk and libsoup. FWIW, I think it would be a great addition, if it's ever more do-able! And of course, thank you for your work on vimb!

**Comment by fanglingsu** [comment]
I've started to port vimb to webkit2 but this is a hard way. The APIs changed a lot and some of the features that are now available could not be done with webkit2. But I'll create a new issue so that we don't forget to put this in. But I think we can't do this in webkit1 in a clean and simple way. And I must admit that I don't want to implement such security things. There are potentially sticking points and a little mistake in the implementation could reduce the security to nothing. Hope that there is one or more other developer helping us.

**Comment by fanglingsu** [comment]
I've written an issue for the mutual auth #170. But I think this feature isn't released in the next two months.

**Comment by torrancew** [comment]
@fanglingsu totally understandable. For what it's worth, I'm happy to try to help hack that feature out. I've done similar things with other platforms before, just not C/WebKit.

**Comment by fanglingsu** [comment]
Oh, that's fine. Do you think you can get this working also with webkit1?

**Comment by torrancew** [comment]
My first glance didn't reveal any API methods for doing this in the existing libraries, but I'll take another look this week.

**Comment by foudfou** [comment]
@fanglingsu you said you were working on the webkit2 port. Is there a code repository somewhere ? I was expecting a `webkit2` branch in this repo in fact.
For the record, I think [WebKitAuthenticationRequest](http://webkitgtk.org/reference/webkit2gtk/stable/WebKitAuthenticationRequest.html) is what's needed.
Anyway, kudos for the great project!

**Comment by fanglingsu** [comment]
@foudfou I don't have much time and the code looks horrible at the moment and not ready for the initial push. I've taken the current code and commented the most things out and started to make it ready to the new process achitecture. I didn't found a way to do this step by step - the most essetial things do not work anymore and have to be put into a webprocess extension that communicates by dbus with vimb.
