### ISSUE TITLE
Migration to webkit2

### ISSUE THREAD

**Issue by fanglingsu** [fanglingsu/vimb#171]
Remove the support for gtk2 and webkit1 from the code and Makefile. Migrate the code to provide as many of the current features also on webkit2.

**Comment by fanglingsu** [comment]
At the time vimb uses the DOM-API to check for editable fields in the html for the editor command and to put vimb into `-- INPUT --` mode if an editable element is focused. With webkit2gtk we don't have a way to access the DOM-API from the UI-Process. To access the DOM-API we need to implement a webextension that is automatically loaded into webkits web-process.

But unfortunately there is no webkit built in IPC to transfer data between the two processes. So there is a need to have some kinde of IPC within vimb.

**Comment by The-Compiler** [comment]
I just saw in the [blog post about WebKitGTK+ 2.8.0](http://blogs.igalia.com/carlosgc/2015/03/23/webkitgtk-2-8-0/) that it now has some lightweight IPC built in.

**Comment by fanglingsu** [comment]
@The-Compiler Oh, that's fine but this allows only one way communication from webprocess to the ui process and not vice versa.
I started to implement the dbus stuff locally, I thinks we'll use this, but there are a lot of more cases for unintended behaviour (DBus name lost, Webextension crashed, Settings change in UI but arrive to late in the webextension ...).

**Comment by faxm0dem** [comment]
is the webkit2 branch testable? I tried compiling with the following errors:

```
cc ext-util.lo
cc ext-main.lo
cc ext-dom.lo
cc webext_main.so
cc shortcut.o
cc normal.o
cc main.o
main.c: In function ‘vimb_setup’:
main.c:1130:56: error: ‘GUI_STYLE’ undeclared (first use in this function)
     gtk_css_provider_load_from_data(vb.style_provider, GUI_STYLE, -1, NULL);
                                                        ^
main.c:1130:56: note: each undeclared identifier is reported only once for each function it appears in
Makefile:24: recipe for target 'main.o' failed
make[2]: *** [main.o] Error 1
Makefile:15: recipe for target 'src.subdir-all' failed
make[1]: *** [src.subdir-all] Error 2
Makefile:38: recipe for target 'sandbox' failed
make: *** [sandbox] Error 2
```

**Comment by faxm0dem** [comment]
I managed to get it to compile by including `config.def.h` in `main.c`.
Is it already possible to use x509 certificate based auth?

**Comment by fanglingsu** [comment]
The webkit2 branch is far away from beiing usable. I pushed it, because I don't have time at the moment do work on it. there is a lot of work to do and I hope there will be some developer supporting me to rework vimb on webkit2.

**Comment by faxm0dem** [comment]
thanks for the update

**Comment by fanglingsu** [comment]
There are now issues for all know missing features for the webkit2 vimb, so this general issue is closed.
