### ISSUE TITLE
Mapping <Space> and <BS>

### ISSUE THREAD

**Issue by xged** [fanglingsu/vimb#174]
\<Space\> and \<BS\> has to be included as a special key names (\<Tab\>, \<Esc\>, \<CR\> are already there).

**Comment by fanglingsu** [comment]
We could add this to be closer to vim. But I try to keep vimb simple in this case and implemented the key map stricter than vim.

- `<Space>` this can already be mapped, but only as space character (not that this must be escaped by `\` for the `:map` commands). Example `:nmap \  ;o`.
- `<BS>` also this can be mapped under the equivalent `<C-H>`. Providing `<BS>` too could make the user assume to be able to mapp `<BS>` and `<C-H>` to different things which is in fact not possible. But if you are petty, you may remind me for `<CR>` and `<C-M>` that are the same even in vim.
