### ISSUE TITLE
Mapping to a space

### ISSUE THREAD

**Issue by xged** [fanglingsu/vimb#176]
How can i map to a space? `cmap ₃₂ \[space]` does not work. Related to #174.

**Comment by fanglingsu** [comment]
If you intend to use `:imap` there is no way to map to space or to any other normal char at the time like `:imap teh the`. Vimperator allows to add also such mappings but I never found a useful case to do this that is worth to bloat vimb. 

Currently the imap is only useful to run normal mode commands from input mode `:inoremap <C-I> <Esc><C-I>` or to remap the few input mode commands to others `:imap <C-E> <C-T>` to start the editor in case vimb is run in tabbed that catches the `<C-T>`.

**Comment by xged** [comment]
*there is no way to map to space or to any other normal char*
Explain this, cos I had successfully *imapped* to a lot of normal chars via `vimb -c [file]`.

**Comment by fanglingsu** [comment]
Could you provide the imap line from you config file that works. I can't map one char to another normal char.

**Comment by xged** [comment]
I *imapped* ₀ - ₉ unicode characters to normal characters.

**Comment by fanglingsu** [comment]
Strange, in my opinion this should not work. A possible similar mapping like `:imap ¬ f` does not work for me, neighter from config file nor from inputbox.

**Comment by xged** [comment]
My bad. I meant `cmap` instead of `imap`. Inability to *imap* would be a deal breaker for me. Any plans to make that work?

**Comment by fanglingsu** [comment]
There are no plans to rework the imap stuff, sorry. I don't have much spare time to do that and there are normally no usecases for doing this. The input mode is used to write text into form field which works out of box with webkit. In case you are unhappy with this, you still have the option to open the editor of choice with the contens of the form field and edit it there (`<C-T>` in insert mode).

But the `:cmap` should be fixed to allow to map `{rhs}` with leading spaces, and this only works by `<Space>` in vim. So you convinced me from adding `<Space>` as special key name.

**Comment by xged** [comment]
Another use case is `<C-Space>` (`<C-BS>`).

**Comment by fanglingsu** [comment]
But as I can see vim does not have special keynames like `<C-Space>` or `<C-BS>` so I don't think we should add these to vimb.

**Comment by xged** [comment]
`<C-Space>` and `<C-BS>` are mappable, meaning vim has those *special keynames* (?).

**Comment by xged** [comment]
I think `<C-Space>` and `<C-BS>` are mappable ([eg](http://vim.wikia.com/wiki/Map_Ctrl-Backspace_to_delete_previous_word)), though I cannot test that, because of specifics of Terminal.app interpretation.

**Comment by fanglingsu** [comment]
OK, vim lists the mapping, but you cant trigger them. And according to `:help key-codes` they don't exists, and you can't insert them as names keys by `:cmap <C-K>...`.

**Comment by fanglingsu** [comment]
OK `<BS>` is now available by #182.
