### ISSUE TITLE
Create an irc channel for vimb?

### ISSUE THREAD

**Issue by sdothum** [fanglingsu/vimb#178]
Hey Daniel,

You've been supporting vimb and its community a great deal of late.. I was wondering if you might consider creating a vimb irc channel?

I noted that you were addressing #176 and wanted to let you know I added a further note to #165 which might offer up a clue as to what may be going on/where to look. I am not sure if you get notifications when issue comments are added or whether you need to manually check them -- which would be a pain and difficult to track. An irc channel would provide a easy means for us to ping you.. which may or may not be a good thing from your end!

Tx for all your great work!

**Comment by fanglingsu** [comment]
I'm informed via email about each comment on issues. So you don't have to worry I don't read them. But according to #165 I've no further idea what to do further to reproduce or fix it.
According to the irc, I don't use it, and if there would e a channel, I wouldn't be there as often to be informed about news.

**Comment by sdothum** [comment]
Thanks for the time and effort, nevertheless. I may try to take a gander at luakit and see how it does thnigs differently for a clue.. I never thought any other browser would supplant luakit for my everyday use but vimb seems to have done that.
