### ISSUE TITLE
support wayland

### ISSUE THREAD

**Issue by 257** [fanglingsu/vimb#179]
you can use these for testing:

https://github.com/michaelforney/velox
https://github.com/michaelforney/swc

if you're into dwm, suckless and all that jazz

**Comment by fanglingsu** [comment]
I don't want to compile all the wayland stuff and use another window-manager. As I can see vimb does not use any gdk_x11_* or xlib functions so vimb should run under wayland in case it was compiled against gtk3 with wayland backend.
If you are familiar with wayland, feel free to provide patches to support wayland.

**Comment by fanglingsu** [comment]
Closed out of long time of inactivity. Feel free to reopen it if you are still interested in and know someone who knows what's to do for wayland.
