### ISSUE TITLE
implement suggestengines

### ISSUE THREAD

**Issue by 257** [fanglingsu/vimb#181]
...vimperator style:
https://github.com/vimperator/vimperator-labs/search?utf8=%E2%9C%93&q=suggestengines&type=Code

**Comment by fanglingsu** [comment]
I don't know what you have in mind, the search url you provided shown only a two matches in JavaScript that make me believe that there is one fork of vimperator-labs that llos to set a property called `suggestengines`.
What should be suggested, where and why? At the moment an can only guess that this might be related to #180.

**Comment by foo-bar-baz** [comment]
On Feb 17  14:26 -0800, Daniel Carl wrote:
> I don't know what you have in mind, the search url you provided shown
> only a two matches in JavaScript that make me believe that there is one
> fork of vimperator-labs that llos to set a property called
> `suggestengines`.  What should be suggested, where and why? At the moment
> an can only guess that this might be related to #180.

it is indeed related to #180 but this is for the search suggestion only. i
asked people on #vimperator channel earlier and someone suggested that it
uses firefox's built-in suggestion engine which seems to be a module that
talks to google's autosuggestion api.

**Comment by fanglingsu** [comment]
Ah you mean that you are not sure what to search for and start typing to near down the list of older search queries from other users to search for them.

At my current point of view this is to much overhead and a lot of work. And I don't think this will be added to vimb. Besides this I don't like the concept that a search engine suggests the user what to search for. If I'm interseted in something, I'll search for that and don't want to be persuaded to search for something other albeit something similar.

**Comment by foo-bar-baz** [comment]
On Feb 18  14:30 -0800, Daniel Carl wrote:
> Ah you mean that you are not sure what to search for and start typing to
> near down the list of older search queries from other users to search for
> them.

no, that would be stupid.

> At my current point of view this is to much overhead and a lot of work.
> And I don't think this will be added to vimb. Besides this I don't like
> the concept that a search engine suggests the user what to search for. If
> I'm interseted in something, I'll search for that and don't want to be
> persuaded to search for something other albeit something similar.

i give you an example. i'm not a native English speaker. and learning the
language i discovered some articles are bitch to memorise in terms of where
they're used. for instance, would you say "i will see _at_ the party" or "i
will see you _on_ the party". looking at what others say in this case would
be helpful, me thinks. or if i have no notion of how Engligh speaker would
spell a Russian name like Tarkofsky (the probably spell Tarkovsky), well i
would like to type Tarko and see what i get. i can give you endless
examples but i think the idea is obvious. search engine suggestions are
like every other technologies, one can make use of it or hang himself with
it.

**Comment by fanglingsu** [comment]
I thinks this is to much for light weight tool like vimb.
