### ISSUE TITLE
Add :mkvimb to save current configuration in to config/vimb

### ISSUE THREAD

**Issue by tyjak** [fanglingsu/vimb#183]
I'm starting using vimb, it would be useful to have a command to save the current configuration to config/vimb, or to have a mode to make `:set` command persistant.

**Comment by fanglingsu** [comment]
Oh, this would be nice. I've thought about this too, some months ago. But this was not so important for me to take the time for doing this.

At the time I try to built vimb from scratch on webkit2, which is a hard work and takes a lot of time. So don't be sad if this feature will take some time.

**Comment by fanglingsu** [comment]
It's still not so important and I think it's easy to write the file by hand.
