### ISSUE TITLE
Option to remove auto-triggering hinting

### ISSUE THREAD

**Issue by mynameisfiber** [fanglingsu/vimb#184]
I really love the hinting system, but sometimes when I'm typing out the hint and it auto-triggers because there is only one thing left, the page changes but I'm still typing and then random commands get triggered!  I would much rather be able to change this functionality so I _always_ have to press enter to continue.

**Comment by mynameisfiber** [comment]
For some reason this segfaults when set in the config file, however setting during runtime with `:set hint-follow-last=false` works great.  This seems to be a general problem, however... any configuration in `$XDG_CONFIG_HOME/vimb/config` leads to a segfault.

**Comment by mynameisfiber** [comment]
Ah, nevermind.  The documentation seemed to maheke me think that there was a special config format of the form,

```
key  value
```

However, trudging through the code shows that it is simply a list of commands such that the correct thing to have in the config file is,

```
set key=value 
```

Anyways... this pull is ready to go!

**Comment by fanglingsu** [comment]
I've merged you patches, so I think this issue is solved by you great work.
