### ISSUE TITLE
Update README.md distribution-specific? (AND deb file for Ubuntu amd64)

### ISSUE THREAD

**Issue by martensms** [fanglingsu/vimb#185]
Required packages for compilation on my UbuntuGNOME (edge-gnome3) were:

```bash
sudo apt-get install libsoup2.4-dev libwebkit-dev libgtk-3-dev libwebkitgtk-3.0-dev
```

Maybe it makes sense to either have that in the makefiles (via distro-switch?) or in the README.
Not sure where to host those instructions. Works like a charm afterwards.

I also generated a debian package for Ubuntu (GTK3) users here with correct dependencies (don't know where to host, so I uploaded it here):

http://martens.ms/raw/vimb_2.9-1_amd64.deb

**Comment by fanglingsu** [comment]
Thank you for the hint. I've put a little notice to the README.md.
