### ISSUE TITLE
Bookmarks and autocompletion

### ISSUE THREAD

**Issue by Artymort** [fanglingsu/vimb#189]
Hi,

I can't use the autocomplete feature on bookmarks. With this bookmark file for exemple :
```
http://www.duck.com/	foo1
http://www.duckduckgo.com/	foo2
https://github.com/fanglingsu/vimb/	bar
```
```:open !d<tab>``` does absolutely nothing, neither does ```:open !foo<tab>```.

(BTW : puting spaces instead of <tab> here leads to a segfault. Should I open another issue ? Since the syntax of the bookmark file is not specified, this is not actually a bug...)

**Comment by fanglingsu** [comment]
Thank you for the issue. The segfault is a bug independent of this is somewhere specified ore not. I'll have a look at this and you don't need to open a new issue for this.

**Comment by fanglingsu** [comment]
The segfault should be fixed.
The format of the bookmark file is `uri<tab>title<tab>Space separated tags`. For you case this should be `http://www.duck.com/<tab><tab>foo1`.

**Comment by Artymort** [comment]
Ok. I tried putting 2 tabs instead of one but it changes nothing though.

What's more, apart from any title or tag, ```:open !d<tab>``` should let me choose between duck.com (this is a surprising one) or duckduckgo.com, right ? While it actually does nothing in my case.

**Comment by fanglingsu** [comment]
The bookmark completion with `:open !d<tab>` does only lookup by the tags. There is none url matching done like in history lookup.

I don't like to mix them up, but maybe we can allo the user to do both with something like:

    :open UrlPattern !Tag OtherTag<tab>

But this could be irritating for the user, because `:open foo<tab>` and `:open !foo<tab>` are totally different things that are feed from two different files.

**Comment by Artymort** [comment]
Ok I see your point, and I agree that mixing them is not satisfactory. Maybe a behaviour such as *in the absence of tag, you filter via URL* ? That is, the URL is a default tag of any untagged bookmark ?

The point is that I don't want to tag every bookmark, but I still want to be able to manage them if I tend to have a lot... But this is just an idea.

**Comment by fanglingsu** [comment]
Thank you for this nice idea. This is a simple solution and can be used like the tag completion.

**Comment by fanglingsu** [comment]
Thank you for this nice idea. This is a simple solution and can be used like the tag completion.

**Comment by fanglingsu** [comment]
Thank you for this nice idea. This is a simple solution and can be used like the tag completion.

**Comment by fanglingsu** [comment]
Thank you for this nice idea. This is a simple solution and can be used like the tag completion.

**Comment by Artymort** [comment]
Thank you for implementing this feature :+1:  !

I think this can be closed now.
