### ISSUE TITLE
Can't map literal \

### ISSUE THREAD

**Issue by ggVGc** [fanglingsu/vimb#191]
Trying to use this mapping `nmap \\ :tabopen` makes me have to press `\` twice to trigger.
With only one `\` the map instead maps space, since it escapes in that scenario.

**Comment by fanglingsu** [comment]
Oh, right, can reproduce this. I'll try to fix it soon.

**Comment by fanglingsu** [comment]
It works for me now, hope that this does not introduce regressions somewhere else.

If the patch works for you too, please feel free to close the issue.
