### ISSUE TITLE
No way of copying URL of current page

### ISSUE THREAD

**Issue by ggVGc** [fanglingsu/vimb#192]
As far as I can tell, there's no way of copying the URL of the current page to clipboard. I do this quite a lot in other browsers, so I think it's a valid feature to have.

**Comment by iamleot** [comment]
Hello ggVGc and the entire vimb community,

ggVGc writes:
> As far as I can tell, there's no way of copying the URL of the current page to clipboard. I do this quite a lot in other browsers, so
>  I think it's a valid feature to have.
Probably you are looking for the "y" (yank) keybind.

You can also do something like that:

 :sh! sh -c "echo $VIMB_URI | xclip -i"


HTH,
Ciao,
L.

**Comment by ggVGc** [comment]
ah, yes, thanks. I missed that command somehow, sorry!
