### ISSUE TITLE
Bookmark tab completion seems broken

### ISSUE THREAD

**Issue by ggVGc** [fanglingsu/vimb#193]
Typing `:open !foo<tab>` seems to do nothing for me, even when having several bookmarkis matching `foo`. 
`:open foo bar<tab>` works fine and completes as it should though, and `:open !<tab>` lists all bookmarks.

**Comment by fanglingsu** [comment]
Are you shure that you have bookmarks matching foo? Note that the tags are matched from beginning of the tag. This means foo will match entries with tags that starts with foo like 'football' but not 'tofoo'.

**Comment by ggVGc** [comment]
yeah, sorry, I misunderstood the feature, and didn't actually have any tags attached to my bookmarks. I would however like to suggest to have the same kind of completion for bookmarks as for history. It would be nice if it sorted by tags primarily, but then also included matching URLs secondary.

**Comment by fanglingsu** [comment]
There was another issue #189 similar to this. If you use the master branch the matching should also work if there are no tags in the file. But, that's different to the history matching the url is split at '/' and '.' and the resulting parts are used in the same way as the tags (prefix matching).

**Comment by fanglingsu** [comment]
I like the tag filtering, because it allows me to filter very precisely. If the url is used by default too, I'll be confrontated with too many matched results.
I like to filter only by tags and fallback to the url matching only if there are no tags defined.
