### ISSUE TITLE
Need more input field customization

### ISSUE THREAD

**Issue by amerlyq** [fanglingsu/vimb#196]
Best of all would be integration with   https://github.com/ardagnir/pterosaur
But will do even standard emacs shortcuts (imap don't work with them?)

```
imap <C-h> <Backspace>
imap <C-d> <Delete>
imap <C-b> <Left>
imap <C-f> <Right>
imap <C-a> <Home>
imap <C-e> <End>
```

**Comment by fanglingsu** [comment]
You are right, the current mapping for imput mode isn't really useful. It would be nice to allow to do some text editing in input fields too. But this have to be done in JavaScript and I'm not the right person for doing that. So, I suggest you to use you favorite editor to edit input fields.

**Comment by amerlyq** [comment]
Hmm. I haven't looked at your sources yet, so do not completely understand the meaning of "have to be done in JavaScript". Something like "script.js" file for *surf* browser? Point me at, please, and when I will be completely freakened out by clumsy input fields, I will play with js more deeply.

**Comment by amerlyq** [comment]
Frankly speaking, I could not force this ```<C-T>``` editing magic to work.
```set editor-command="gvim -f"``` don't reacting at all. 
Nothing happens when pressing on focused or unfocused field. 
Is it bug or my wry hands?)

**Comment by fanglingsu** [comment]
Oh, maybe you missed the placeholder for the file to open `%s`. Could you try `:set editor-command=gvim -f %s`, this should work.

**Comment by amerlyq** [comment]
Oh, yes, I mistyped when posting issue. In config all was ok -- with '%s'. So your command works.
Real problem was in using quotes. Is it bug or feature?

**Comment by fanglingsu** [comment]
I don't know. There is really no need to have quotes arount settings, so I've never took the time to implement this.
