### ISSUE TITLE
Toggle auto-focusing on input field

### ISSUE THREAD

**Issue by amerlyq** [fanglingsu/vimb#197]
There are irritating behaviour (as for google.com) -- after puting text and pressing enter -- on new loaded page with search results cursor is again standing in input field, so I can't instantly do 'f' or 'j/k' and must press escape (twice!) to choose search result. I would appresiate option to toggle auto-focusing on input field (or I miss that one in manual?) to vimb have more like pentadactyl behaviour.
Same with weird feeling of default auto-input-mode for unbinded keys in normal mode -- when mapped keys do what they supposed to do, not mapped jumps to input field, which is obviously _not_ what I wanted in that moment of work, being guided by reflexes or when simply missed right key. 
Thanks.

**Comment by fanglingsu** [comment]
You can change the behaviour with the `strict-focus` setting. But in case of google and github this does not work. I spent a lot of hours some month ago and did find a nice solution for this. The problem on google is, that the enter doest not post the form. But even if the focus is removed from the form fiel this is focused by googles JavaScript.
Even if we can fix that for google search I assume we get a regression on translate.google.com with enabled instant translation like in #95.

**Comment by amerlyq** [comment]
As you can assume, strict-focus in my config enabled by default)). And pitiful it isn't enough in case of google or github... and several other random sites I tried with. How about intercepting that "too smart" behaviour of google scripts, disabling "search-as-you-type" feature and sending all form on enter? Optionally of course.

**Comment by fanglingsu** [comment]
I fear that would be to much work, to intercept such rich internet applications from doing what they do at the time. I hope someone else or I, will trip over some nice solution in  vimb to get rid of these kinds of issues. But at the time, I don't understand really why we end up in input mode.

**Comment by fanglingsu** [comment]
I've found a way to get rid of both pages google search and google translate. I've made some fundamental changes in the way vimb follown focus/blur events. I hope this will not bear other regressions. I'll test it more on some more pages.
