### ISSUE TITLE
problem with "cursor to the first editable element"

### ISSUE THREAD

**Issue by semarie** [fanglingsu/vimb#198]
hi @fanglingsu 

I encounter a problem that I don't arrived to debug: on a page with an `input type="TEXT"` element, the `gi` command don't work (`Set cursor to the first editable element in the page and switch to Input Mode`). The problem seems to be case related as if I edit the page to change `TEXT` to `text`, it works.

Here a non-working minimal example:
```html
<html>
<head><title>gi</title></head>
<body>
    <form>
        <input type="TEXT"/>
    </form>
</body>
</html>
```

**Comment by fanglingsu** [comment]
Thank you for reporting this issue. This is strange the hinting works, fir this text field but the focus does not, but both use nearly the same xpath expression. One is written in JavaScript the other in c. I'll try to fix this soon.

**Comment by fanglingsu** [comment]
I added a little hack to do case insensitive xpath matching in webkit dom api too. I haven't tested much, but this seems to work.

**Comment by semarie** [comment]
it solve the problem. thanks !
