### ISSUE TITLE
Minor issues with styles

### ISSUE THREAD

**Issue by jasonwryan** [fanglingsu/vimb#199]
Two small bugs applying styling to vimb:

One. Irrespective of what value I set for `completion-bg-normal` it only ever displays as off-white. Currently I am using `set completion-bg-normal=#222`. All of the other `completion-*` values work as expected.

I tried removing all of the options from the `config` and hard coding them in `/src/setting.c` but it made no difference, as you can see in this screenshot:

![background](https://cloud.githubusercontent.com/assets/126317/7214406/395f09c4-e5ff-11e4-8445-9663332e8e1a.png)

Two. I have a custom `.config/vimb/style.css` to change the hinting colours (adapted from the [FAQ page](http://fanglingsu.github.io/vimb/faq.html), which works fine, but when hinting is activated, all of the link colours on the page turn to `#000`: is there any way to write a style that does not change the colour of the links, merely hints them?

My style.css:

```
/*     Vimb hint styles            */
._hintLabel {
    -webkit-transform:translate(-4px,-4px);
    position: absolute;
    z-index: 100000;
    font: 11px monospace !important;
    color: #000 !important;
    background-color: #CCC !important;
    margin: 0;
    padding: 2px 4px;
    border: none !important;
    opacity: 1 !important;
}
._hintElem {
    background-color: transparent !important;
}
._hintElem._hintFocus{
    background-color: transparent !important;
}
._hintLabel._hintFocus{
    color: #FFF !important;
    background-color: #707070 !important;
    z-index: 100001;
    opacity: 1
}

/*         General styles           */
code {font: 10px !important;} 
```

Three. Bonus question (completely unrelated): how do you comment lines in `.config/vimb/config`?

**Comment by fanglingsu** [comment]
> One. Irrespective of what value I set for completion-bg-normal it only ever displays as off-white. Currently I am using set completion-bg-normal=#222. All of the other completion-* values work as expected.

Can't reproduce this, `set completion-bg-normal=...` works. Did you compile vimb with GTK3? At the time I'm not on my machine to check with GTK3, but GTK2 works.

> Two. I have a custom .config/vimb/style.css to change the hinting colours (adapted from the FAQ page, which works fine, but when hinting is activated, all of the link colours on the page turn to #000: is there any way to write a style that does not change the colour of the links, merely hints them?

You re right, this does not work, or I don't know how to overwrite style done during hint processing. If you wan't to keep the original link color, you have to patch the https://github.com/fanglingsu/vimb/blob/master/src/hints.js#L32 hints.js file. But than you might run into trouble when the link color is the same as the hint elements background. Maybe we should strip down the default style to position the hint labels near the links and let the user style the hints via _style.css_. Or even simplier we can put the default hint style css into _config.h_ file.

> Bonus question (completely unrelated): how do you comment lines in .config/vimb/config?

Lines starting with `#` are considered as comments. It's not possible to put comments on the end of line like in vim.

**Comment by jasonwryan** [comment]
>> One. Irrespective of what value I set for completion-bg-normal it only ever displays as off-white. Currently I am using set completion-bg-normal=#222. All of the other completion-* values work as expected.

> Can't reproduce this, set completion-bg-normal=... works. Did you compile vimb with GTK3? At the time I'm not on my machine to check with GTK3, but GTK2 works.

No, compiled with GTK2. This is odd, as you can see in the screenshot, it remains white...

>> Two. I have a custom .config/vimb/style.css to change the hinting colours (adapted from the FAQ page, which works fine, but when hinting is activated, all of the link colours on the page turn to #000: is there any way to write a style that does not change the colour of the links, merely hints them?

> Maybe we should strip down the default style to position the hint labels near the links and let the user style the hints via style.css.

That sounds good.

Thanks Daniel.

**Comment by fanglingsu** [comment]
So, I'm back on my machine. I can change the `completion-bg-normal` with GTK2 and GTK3 during runtime or by config file. Does vimb write some useful messages if started from cli.
Do you have some GTK theme running, maybe this overrules the color that vimb tries to use. You could use strace to show which files are used. For example `strace -e trace=open,access -f -o log vimb` and search for gtk theme related files like `gtkrc`.

**Comment by jasonwryan** [comment]
> Do you have some GTK theme running, maybe this overrules the color that vimb tries to use.

That was it. I changed the theme and it works perfectly. I should have thought of that myself: thanks for the help and sorry for the noise.

**Comment by kazufukurou** [comment]
Facing same issue. I have 2 themes: Raleigh and Adwaita, which I believe are default GNOME themes. Adwaita looks good but somehow overrides 'completion-bg-normal' setting. Raleigh doesn't override settings but looks ugly. Isn't it wrong that GTK theme has priority over vimb/config?

**Comment by fanglingsu** [comment]
As I know, there is no way in GTK2 to ensure GUI-Settings. With GTK3 this would be possible, but not the reconmendet way. The application should normally set some useable default values and the the used theme may override this.
