### ISSUE TITLE
Insert mode in Captchas

### ISSUE THREAD

**Issue by guaraqe** [fanglingsu/vimb#201]
The browser does not identify when you are typing inside a captcha and stays in normal mode.

The older captchas work ok, but the most recent one that's entirely in Javascript (such as the one used in 4chan.org) no. In order to type them, it's needed to go to pass through mode.

**Comment by fanglingsu** [comment]
Confirmed. I think the reason for this is that the captcha is within an iframe. Maybe we have to add event observers to each frame to get rid of this.

**Comment by scrzbble** [comment]
Possibly related to this bug. It's not only captchas. Vimb mixes up normal and insert mode also in some web forms, for example:

Email field at https://profile.theguardian.com/signin
Search field at https://en.wikipedia.org/

This makes it impossible to interact with such fields.

**Comment by semarie** [comment]
@scrzbble The PR #202 should have been addressed your problem (Email & Search fields are new input type under HTML5). If it isn't the case, please open a new issue.

For this bug, it isn't the same problem: the input type is defined to `text`. So clicking to the field should switch mode to `input` (and it isn't the case).

**Comment by fanglingsu** [comment]
I've create the new branch issue-201 for fixing this issue. Well, I've fixed it, but the fix seems to break the `set focus-input=on` behaviour. If a page is loaded in an iFrame that sets focus and vimb is configured to use `strict-focus` vimb switches to input mode, what's wrong I think. In case the input setting page is loaded directly, vimb bahaves like expected.
@semarie Maybe you can have a closer look to the issue. I've added a new test file _tests/manual/201-editable-focus-in-iframes.html_

**Comment by fanglingsu** [comment]
I merke the branch into master. I think the issue should be fixed.
@guaraqe can you please check if it works ofr you too?

**Comment by guaraqe** [comment]
Just checked, it works now, no problems. I'm closing the issue, thanks!
