### ISSUE TITLE
Crash on Bitbucket.com

### ISSUE THREAD

**Issue by Dickby** [fanglingsu/vimb#203]
Hi,
I use this browser on arch-linux 86_64.
It crashes every time I open a site of bitbucket.com.
I tested this on two laptops. I hope it can be fixed.
I really love this browser, Thanks.

**Comment by semarie** [comment]
I couldn't reproduce this issue on https://bitbucket.org/ . Which URL crashs the browser (exactly) ?

Also, could you provide a stacktrace via gdb ? in order to help us to locate the problem ?

**Comment by Dickby** [comment]
It happens at every bitbucket site, for example https://bitbucket.org/emacsway , it just loads to 89% and freezes.
how shold I do that stacktrace, are there any debug flags for vimb or do i have to recompile with -g flag?
I compiled vimb with gtk3 support, could that be the reason?

**Comment by semarie** [comment]
I use gtk2. So It *may* be the reason (but normally vimb works well with gtk3 too). I couldn't check with gtk3 now, but I will try soon.

For the stacktrace, just adding `-g` to `CFLAGS` in `config.mk` should be enough (and recompile). If you aren't familiar with gdb, I could provide a step-by-step procedure.

You could also try to disable plugins (`set plugins=false`) and/or javascript (`set scripts=false`) before opening the page, in order to check if the crash if related to one of them.

**Comment by The-Compiler** [comment]
I've never heard of a *crash* there - but hanging on bitbucket pages is a WebKit1GTK bug which is present in all browsers using that (e.g. dwb or luakit too).

**Comment by Dickby** [comment]
With `set scripts=false` it works fine.
Is that enough information?
If you still need a stacktrace for tracking down the bug, let me know.

**Comment by semarie** [comment]
a stacktrace would permit to locate the bug (I hope).
Knowing that with `set scripts=false` it don't crash just permit to known the bug should be related to javascript.

**Comment by fanglingsu** [comment]
I can't reproduce this issue. I use arch-linux 86_64 too, vimb does not crash neighter with GTK2 nor with GTK3. But with enabled JavaScript this hangs the browser on hight cpu usage.

**Comment by kdart** [comment]
Just  a "me too" here. I'm pretty sure it's bad javascript on the site.

**Comment by shioyama** [comment]
Crashes for me too.

**Comment by fanglingsu** [comment]
@shioyama The hang on bitbucket is a knwon webkit issue and affects all Webkit browsers like mention by The-Compiler.

**Comment by fanglingsu** [comment]
According to the hang on bitbucket, and some other sites. It's possible to disable the JavaScript JIT Compiler in Webkit by setting environment variable `JavaScriptCoreUseJIT` to 0. When I start vimb by `JavaScriptCoreUseJIT=0 vimb` bitbucket is fast also with enabled javascript. Maybe this helps also against the reported crash, but I can't say, because it never crashed on my systems.

**Comment by TieDyedDevil** [comment]
This is interesting. For some reason, vimb no longer crashes on
bitbucket.com. It used to, and also on other Atlassian sites. I've had to
use icecat, a Firefox derivative) to access those sites.

I'm currently compiling vimb against webkitgtk (GTK2, not 3) version 2.4.9.

On Wed, Feb 17, 2016 at 11:39 PM, Daniel Carl <notifications@github.com>
wrote:

> According to the hang on bitbucket, and some other sites. It's possible to
> disable the JavaScript JIT Compiler in Webkit by setting environment
> variable JavaScriptCoreUseJIT to 0. When I start vimb by JavaScriptCoreUseJIT=0
> vimb bitbucket is fast also with enabled javascript. Maybe this helps
> also against the reported crash, but I can't say, because it never crashed
> on my systems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fanglingsu/vimb/issues/203#issuecomment-185582307>.
>



-- 
"I think as musicians, we have more vision than we credit ourselves for. We
should dive into it without reserve, and take the sort of risks it takes to
be divisive and impactful. Things have yet to be done."
   Aaron Fowler Clark

"Do not seek to follow in the footsteps of the masters. Seek what they
sought."
   Matsuo Basho

"Knowledge speaks; wisdom listens."
   Jimi Hendrix

http://soundcloud.com/davidlamkins
http://reverbnation.com/lamkins
http://reverbnation.com/lcw
http://lamkins-guitar.com/
http://lamkins.net/
http://successful-lisp.com/

**Comment by fanglingsu** [comment]
Is there some one else where vimb still crashes on bitbucket?

**Comment by Dickby** [comment]
It still crashes on my Computer.

**Comment by fanglingsu** [comment]
@Dickby Does vim also crash if you run it like this `JavaScriptCoreUseJIT=0 vimb https://bitbucket.org/`?

**Comment by Dickby** [comment]
@fanglingsu It doesn't crash!!
Is there an option for my vimb config file that sets this as default?

**Comment by fanglingsu** [comment]
@Dickby This is a normal environment variable that is used by webkit. So you can set/export it from your shell configuration for example _/etc/profile_, _~/.bashrc_, _~/.zshrc_ or _~/.zshenv_.
