### ISSUE TITLE
Fails to compile now, compiler is trying to interpret javascript

### ISSUE THREAD

**Issue by kdart** [fanglingsu/vimb#206]
Now when I compile, it get this:

505 $ make
cc shortcut.o
minify hints.js
cc hints.o
In file included from hints.c:28:0:
hints.c: In function ‘hints_init’:
hints.js.h:1:5160: error: expected ‘)’ before ‘HINT_CSS’
#define HINTS_JS "Object.freeze((function(){'use strict';var hints=[], .....

hints.c:64:49: note: in expansion of macro ‘HINTS_JS’
         hints.obj = js_create_object(hints.ctx, HINTS_JS);
                                                 ^
hints.c: At top level:
cc1: warning: unrecognized command line option "-Wno-typedef-redefinition"
Makefile:38: recipe for target 'hints.o' failed
make[1]: *** [hints.o] Error 1
Makefile:43: recipe for target 'vimb' failed
make: *** [vimb] Error 2

**Comment by kdart** [comment]
FYI:

	507 1$ gcc --version
        gcc (Gentoo 4.9.2 p1.3, pie-0.6.2) 4.9.2

**Comment by semarie** [comment]
@kdart I had experimented the same issue some times ago. You should regenerate `config.h` from `config.def.h`.

Just removing `src/config.h` is enought (you will lose any customization, beware), next rerun `make`.

**Comment by kdart** [comment]
@semarie Great, that did fix it. Thanks.
