### ISSUE TITLE
some sites fail due to invalid certificate

### ISSUE THREAD

**Issue by kdart** [fanglingsu/vimb#207]
Hello. I'm not sure this is a vimb problem, bit I only see it in vimb. 

When using https, some resources are unable to load. The dev tool says: 

    Unable to load resource: unacceptable TLS certificate

Not all sites, but sites such as facebook do this. It seems to mostly be resources that come from Akamai. 

So I thought I'd pose the question here if anyone else has seen this?

**Comment by fanglingsu** [comment]
Vimb looks for authorized CAs in a single file that can be set by `:set ca-bundle=/path/to/file`. You can check the path by running `:set ca-bundle?` from inputbox on runtime. Maybe you should use another file that contains the authorities you like to use.
You may try some other crt file like Leonardo Taccari suggested at https://github.com/fanglingsu/vimb/issues/76#issuecomment-41855891.

**Comment by kdart** [comment]
Yes, thanks for the info. I did track it down to the shared certificates bundle on my system. It was missing a CA cert for "GTE CyberTrust Global Root". I guess it's considered weak and not included in my distro.  But the popular browsers must include it as a built in.
