### ISSUE TITLE
Feature request: colorschemes

### ISSUE THREAD

**Issue by jeaye** [fanglingsu/vimb#208]
In Fx, I use to key addons:

- VimFx (like vimperator)
- Stylish (with a global solarized scheme)

I'd love to adopt vimb, as a minimal replacement, but I can't get all of my pages styled to something not glaringly white. vimperator supports colorschemes, Fx has stylish, vimb needs something.

**Comment by fanglingsu** [comment]
I don't think a browser need something like stylish. But you can play around with the styles.css file to change the look of all pages like the example on http://fanglingsu.github.io/vimb/scripts.html.

**Comment by jeaye** [comment]
That's handy, thanks. Looks like there's no way to have site-specific styles. Correct?

**Comment by fanglingsu** [comment]
There is no direct way to have sitespecific styles, but maybe you can play around with the `scripts.js` file to write the style directive into the DOM depending on the cirrent domain and to lod there different local stylesheets. But I'm not sure if this is allowed according to the same origin policy. Maybe you can doe something fancy with the `:autocmd` to inject different stylesheets via JavaScript.

**Comment by jeaye** [comment]
Closing this, since I found that the style.css works very well for me.
