### ISSUE TITLE
How can I get return of JS via a shell script ?

### ISSUE THREAD

**Issue by tyjak** [fanglingsu/vimb#212]
```sh
#!/bin/sh
SOCKET=$(< ~/SOCKET)
test=$(echo '<ESC>::e (function (){return "this is a test";})();<CR>' | socat - UNIX-CONNECT:$SOCKET)
echo "<ESC>::e console.log('$test');<CR>" | socat - UNIX-CONNECT:$SOCKET
```

When I launch these script in my terminal, it works :
- "this is a test" displayed in the console log
- but when I launch in Vimb `:sh test.sh` the line in console log is empty

I don't know if it's an issue or me doing something wrong...

Any idea ?

**Comment by fanglingsu** [comment]
I'm not on my machine, so I can only guess. The socket returns the contents that are shown in the inputbox. If you script does write the intended content to the inputbox of vimb you're on the right way. So the first approach should work for that. I'm not sure, but I think you have to give some additional option to socat to wait for the returned content. This would normally written to stdout. But maybe the `$(echo ... | socat)` does not get the returned value for some shell internal reason. Can you try this with backticks instead.

```sh
test=`echo '<ESC>::e (function (){return "this is a test";})();<CR>' | socat - UNIX-CONNECT:$SOCKET)`
```

**Comment by tyjak** [comment]
alas same bad result with :
```sh
test=`echo '<ESC>::e (function (){return "this is a test";})();<CR>' | socat - UNIX-CONNECT:$SOCKET)`
```
By vimb via `:sh` an empty value is returned by `$(echo ... | socat ...)` but via my shell it returns the js value .
There is definetly something getting wrong between the invocation of the shell by vimb and the use of the output by socat... I'm a newbie with the use of socat so I can't really figure out what I can do...

Anyway, thank you for your help.

**Comment by fanglingsu** [comment]
If you launch your script as `:sh! test.sh` this returned value of the socet call should be available.
I'm not sure what happens, but I assume that the out put of the `:sh` command and the `:e` command that are nested into eachother conflict. The implementation of the socet return value is really crude and simple. The called command is processed and the content that is available in the inputbox after this is taken as return value.

**Comment by fanglingsu** [comment]
By the way, if you only use the script from withcin vimb (by `:sh test.sh`) you can access the current used socket file from environment variable `$VIMB_SOCKET` instead of the `SOCKET=$(< ~/SOCKET)` which wouldn't work if there are running multiple instances of vimb using sockets.

**Comment by tyjak** [comment]
Thank you for your help, if I use `sh! test.sh` in async mode it works. I didn't yet figure out why the async mode is required...
