### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by serpent7776** [fanglingsu/vimb#215]
It would be nice to add support to scroll horizontally using shift + mouse wheel as it is in chromium. I mean pages like stackoverflow where code blocks are fixed width; if the content is wider it has to be scrolled and now there's no way to scroll using keyboard that I'm aware of.
Any other way of scrolling would also be good, but using shift + mouse wheel seems simplest and quite common.

**Comment by fanglingsu** [comment]
Well you can scroll horizonally with `0`,`$`,`h` and `l` like in vim. It's right that it might be useful to allow user also to mapp mouse buttons or the mouse wheel for that. Like

    map <ScrollWheelUp> h
    map <ScrollWheelDown> l

or similar. But at the time I thought vimb to be keyboard driven and excluded mouse support in favor to implement more useful features firt.

**Comment by fanglingsu** [comment]
I there anyone else who like to have more mouse support in vimb?

**Comment by serpent7776** [comment]
Yeah, I know about scrolling with `0`, `$`, `h` and `l`, but I mean pages like this:
http://stackoverflow.com/questions/357939/example-of-using-authtype-digest-to-authenticate-a-user-once-across-sub-domains
There's really no way to scroll content of code block. Commands you mentioned scroll only whole document; they doesn't work for scrollable blocks
And I don't mean to add more mouse support, but in this particular case I think using mouse is simplier both to use and implement.

**Comment by fanglingsu** [comment]
OK I think I misunderstood you. There is also no way in vimb to scroll the active element, and this will never be added in the version for webkit1. Maybe we can add this for the upcomming webkit2 version. This would also allow to scroll with keyboard within frames which is also not possible at the time.
Maybe you can setup your XServer to allow horizontal scrolling. I have only a thinkpad and can scroll vertically and horizontally with the trackpoint if I press the middle mouse button.

If I remember right this was added by following xorg config section.

```
Section "InputClass"
    Identifier      "Trackpoint Wheel Emulation"
        MatchProduct    "TPPS/2 IBM TrackPoint"
        MatchDevicePath "/dev/input/event*"
        Option          "EmulateWheel"          "true"
        Option          "EmulateWheelButton"    "2"
        Option          "Emulate3Buttons"       "false"
        Option          "XAxisMapping"          "6 7"
        Option          "YAxisMapping"          "4 5"
EndSection
```

I think you can achive you intended behaviour by something similar for you mouse wheel.

**Comment by serpent7776** [comment]
xorg config section you provided doesn't work for me, but I'm using FreeBSD.
Anyway I can use scrollbars for now, it's not a high priority issue.

**Comment by fanglingsu** [comment]
Closed becaue of long time of inactivity.
