### ISSUE TITLE
compiling against musl libc

### ISSUE THREAD

**Issue by ScrumpyJack** [fanglingsu/vimb#218]
vimb successfully builds on musl libc but seg faults when I exec it.
I'm using musl libc to build a package for Alpine Linux.
I can provide a bt and any other info if it's of interest, it would be nice to see this working.
I see there is a package for voidlinux. Was that compiled with musl i wonder?

**Comment by fanglingsu** [comment]
I don't have time to check what's going on in musl libc. Can you generate a stacktrace if vimb sfaults? I think this would help to solve the issue.

**Comment by ScrumpyJack** [comment]
Here is a detailed backtrace of the core dump. hope it proves to be helpful

http://st.ilet.to/vimb.gdb

Versions of those libraries are libjavascriptcoregtk-1.0.so.0.16.17 and libwebkitgtk-1.0.so.0.22.15

**Comment by fanglingsu** [comment]
There are several Bug reports available that might be the same like yours. I searched for 'JSC::GCThread::waitForNextPhase' and webkit. So, it might be a webkit ony issue and not wired to musl libc in this case.

Maybe we can near down to the issue by following questions.

1. Does vimb creash immediately after starting?
2. Does vimb crash also if no page is opened - for example if `home-page` is set to 'about-blank'?
3. Does it appear if Javascript is disabled? `:set scripts=off`

**Comment by ScrumpyJack** [comment]
Thanks for your help in looking into this.
1. Yes, the crash is immediate, before any gtk rendering.
2. and 3.
If I put 
set home-page=about-blank
set scripts=off
in ~/.vimb
and run
vimb -c ~/.vimb
I get the same behaviour, an immediate crash
hope this helps

**Comment by fanglingsu** [comment]
@ScrumpyJack Did you get vimb working with musl libc?

**Comment by ScrumpyJack** [comment]
unfortunately not. it still seg faults with updated webkitgkt

**Comment by ScrumpyJack** [comment]
I've just tried building 2.11 and same problem

**Comment by fanglingsu** [comment]
This is webkit1 related. I close this in hope webkit2 will work for you when the migration is done.
