### ISSUE TITLE
Page loading incomplete (text only) on some websites

### ISSUE THREAD

**Issue by sdothum** [fanglingsu/vimb#220]
Recently, the Archlinux site loads with text content only. Notably,

https://www.archlinux.org/
https://www.archlinux.org/packages/
https://www.archlinux.org/download/

The other links on the home page load correctly but have a different domain prefix.

Interestingly, Voat.co pages often load text only as well but refreshing the page several times often produces the properly formatted page contents.

Other browsers do not appear to exhibit this abnormality. Not sure if this is a webkit timing problem. Very strange. Lurking on Voat is fairly recent but the Archlinux home page problem started happening recently with both the vimb and vimb-git packages in the Archlinux AUR.

**Comment by iamleot** [comment]
Hello sdothum!

sdothum writes:
> Recently, the Archlinux site loads with text content only. Notably,
> 
> https://www.archlinux.org/
> https://www.archlinux.org/packages/
> https://www.archlinux.org/download/
> 
> The other links on the home page load correctly but have a different domain prefix.
> 
> Interestingly, Voat.co pages often load text only as well but refreshing the page several times often produces the properly formatted
>  page contents.
> 
> Other browsers do not appear to exhibit this abnormality. Not sure if this is a webkit timing problem. Very strange. Lurking on Voat 
> is fairly recent but the Archlinux home page problem started happening recently with both the vimb and vimb-git packages in the Archl
> inux AUR.
I could not reproduce it with vimb/2.10... To me it sounds like a
problem with SSL certs... Can you try to retry it after setting
strict-ssl option to false, please?


HTH,
Ciao,
L.

**Comment by sdothum** [comment]
That did the trick! Thanks again!

Steven
