### ISSUE TITLE
Check boxes not rendering

### ISSUE THREAD

**Issue by sdothum** [fanglingsu/vimb#222]
Recently check boxes have stopped rendering on input forms (no visual square box to click on), though, the boxes may be there (just invisible).

This occurs with my custom config/vimb removed allowing vimb to create a default config.

Any ideas?

**Comment by fanglingsu** [comment]
Are all checkboxed drawn invisible, or only on sepcifik pages? Can you provide an URL to a page where I can check the bahaviour.
To check the reason, you can enable the webinspector by `:set webinspector=on`. This allows you to right click on on checkbox "Inspect Element" Normally you should be able to inspect the applied css styles to the element on the right. Maybe you can find some style that make the box not visible (display:none, or color set to the same of the surronding content, no boarder, or something similar).

**Comment by sdothum** [comment]
Here is a sample url

https://01100111011001010110010101101011.info/

(the "remember me" checkbox). It appears to be a problem with the urls I visit (afaik) but is difficult to remember now because the missing checkbox may not get my attention!
