### ISSUE TITLE
Indic font rendering in Vimb

### ISSUE THREAD

**Issue by jasonwryan** [fanglingsu/vimb#231]
Vimb doesn't seem able to pick up some of the installed system fonts to render the Indic languages correctly.

See this sceenshot in Vimb:
![vimb](https://cloud.githubusercontent.com/assets/126317/8795246/79712612-2fdf-11e5-9dea-c510d03dc01a.png)

And the same Wikipedia page in Chromium:
![chromium](https://cloud.githubusercontent.com/assets/126317/8795253/8b44f56c-2fdf-11e5-9c0e-5094dc6fa8d4.png)

Is there any way to configure Vimb to pick up these fonts?

**Comment by fanglingsu** [comment]
Sorry for the late answer. I'm not familiar with all the font stuff on linux. On my archlinux system vimb shown none of the indic chars right (I can only see squares). On the ubuntu machine of my wife the indic font is rendered completely and nice looking. This might be of missing font on my system.
For the first you could use `strace -eaccess,lstat64 -f -o trace.log vimb ...` to see which font config files are loaded and which fonts vimb uses. Maybe this will hel to get rid of the issue.
I wonder why only some of the chars of the language are rendered as dotted rounds and not all. I would expect a font ton eigther contain chars of a specific language or not. But to provide only some chars sounds strange.

**Comment by jasonwryan** [comment]
Thanks Daniel. On Arch, you'd need ttf-indic-otf to be able to render those glyphs.

I ran the strace and it all looks as you would expect: https://ptpb.pw/HRiG.log (I truncated it to just the section covering the font calls).

I am equally perplexed as to why it is only a small subset of the glyphs that are not rendered correctly. I might ask bohoomil (I use his infinality patchset) if he has any pointers.

**Comment by Earnestly** [comment]
The dotted circles represent combining characters, which aren't being combined, for whatever reason.

**Comment by fanglingsu** [comment]
I've installed the `gnu-free-fonts` package on archlinux and all the font chars are rendered well. Maybe this is more an issue of the font itself.

I used `https://hi.wikipedia.org/wiki/%E0%A4%AD%E0%A4%BE%E0%A4%B0%E0%A4%A4` to check.

**Comment by jasonwryan** [comment]
Earnestly: thanks.

Daniel: I installed gnu-free-fonts and get the same issue with those joined glyphs. Given that they render in Chromium, I don't think it is due to the font package(s), more the way that Vimb displays them.

I'll look into it some more over the coming days.

**Comment by fanglingsu** [comment]
I have nearly no special font config, the only change I've done was for wrong font used on github.
I have only some lines in _~/.config/fontconfig/fonts.conf_. The content can be found in issue #70.

**Comment by fanglingsu** [comment]
@jasonwryan Did you find a solution that fixed the issue on your system? Shoul I keep the issue open?

**Comment by jasonwryan** [comment]
Sorry Daniel: I completely forgot this was open. A recent update to the infinality patches I use fixed the issue. So vimb was blameless and this can be closed.
