### ISSUE TITLE
hint labels broken on http://www.metafilter.com/

### ISSUE THREAD

**Issue by thedward** [fanglingsu/vimb#232]
On [MetaFilter](http://www.metafilter.com/) when I press `f` the links get highlighted as expected, but I don't see any labels. 

To try and debug the issue I entered:

    :eval var tid = window.setTimeout(function () { document.querySelector("._hintLabel").scrollIntoView(true) ;}, 2000 );
    
Then I immediately hit `f`; after the delay the page was scrolled down past the normal bottom and the link hints were hanging out there in otherwise empty space.

I'm using the default CSS for the hint labels.

**Comment by thedward** [comment]
More info, `vimb -v` reports `vimb/2.10` and I compiled from master (3758486bd5677b767fa431eaf1db5ce9da97856e).

Here is what I see when I hit `f`:

![image](https://cloud.githubusercontent.com/assets/213372/8892018/34240a64-3306-11e5-8097-3c569193113d.png)

Here is what I see when I do the `scrollIntoView` hack:

![image](https://cloud.githubusercontent.com/assets/213372/8892039/b689be0e-3306-11e5-8e6d-b348b8eaec17.png)

**Comment by fanglingsu** [comment]
Thank you for reporting the issue. I've never seen this before. Seems that this is ralated to the `position: relative;` set for all elements. I'll try to provide a fix for that soon.

**Comment by fanglingsu** [comment]
OK, I found a solution that works for me. I've adaptes the default hint style in _src/config.def.h_. Can you please check if this work's for you too? Note that you have to merge manually the _src/config.def.h_ into _src/config.h_ file.

**Comment by thedward** [comment]
That did it!

Thanks!
