### ISSUE TITLE
History/bookmark searching

### ISSUE THREAD

**Issue by jeaye** [fanglingsu/vimb#234]
When opening up the history or bookmarks with `:open !` and then tab, it would be great if I could then search to find pages which I've visited or bookmarked. If this feature already exists, it'd be great if we could add it to the manual (I've found nothing in there).

I think, in general, this feature could apply to Command Mode as a whole. Being able to search through previous commands could also prove useful, though it's not something I desire right now (the rest is).

**Comment by fanglingsu** [comment]
I'm not sure what you mean by the 'search', but you can enter the search phase before hitting the tab. `:open !tagPrefix OtherTagPrefix<Tab>`. But you have to set the search before the completion list is generated. This is similar to the command mode history search. But this is started by `<Up>` or '<Down>`. The search that's sone is a prefix search, so you have to use something like `:open <Up>` step throught the history of the last open commands. Note that there is no completion list shown like for the history and bookmark completion. In this way the command history should work like we know it from vim.

**Comment by jeaye** [comment]
On Wed, Aug 12, 2015 at 04:02:38AM -0700, Daniel Carl wrote:
>    I'm not sure what you mean by the 'search', but you can enter the search
>    phase before hitting the tab. :open !tagPrefix OtherTagPrefix<Tab>. But
>    you have to set the search before the completion list is generated. This
>    is similar to the command mode history search. But this is started by <Up>
>    or '. The search that's sone is a prefix search, so you have to use
>    something like:open ` step throught the history of the last open commands.
>    Note that there is no completion list shown like for the history and
>    bookmark completion. In this way the command history should work like we
>    know it from vim.

I'm interested in searching through the URLs of all items in the bookmarks/history. If I type :open github<tab> it doesn't list each item in my history that contains github in the URL; it only references my previous commands.

Ideally, I'd like to do this:

:open <tab>
-- list appears --
/github
-- filters all URLs in the list by the search terms --

I don't think any equivalent functionality is present.

**Comment by fanglingsu** [comment]
> If I type :open github<tab> it doesn't list each item in my history that contains github in the URL; it only references my previous commands.

This sounds strange. This should list all URL containing github from `XDG_CONFIG_HOME/vimb/history` file. Independent if they where open via `:open` command or by browsing link by link.

**Comment by jeaye** [comment]
On Thu, Aug 13, 2015 at 04:14:55AM -0700, Daniel Carl wrote:
>      If I type :open github it doesn't list each item in my history that
>      contains github in the URL; it only references my previous commands.
> 
>    This sounds strange. This should list all URL containing github from
>    XDG_CONFIG_HOME/vimb/history file. Independent if they where open via
>    :open command or by browsing link by link.

Gah. >.< It does. I'll close this; I'm not sure what the hell I was doing.

Thanks for the support.
