### ISSUE TITLE
Feature request: Implement ^ (by default)

### ISSUE THREAD

**Issue by aksr** [fanglingsu/vimb#236]
Even in old vi, existed '^' cursor motion.

**Comment by iamleot** [comment]
Hello aksr,

aksr writes:
> Even in old vi, existed '^' cursor motion.
In vimb there is '0' (zero) if you prefer to use the '^' you can add in
your config:

 [...]
 nmap ^ 0
 [...]


HTH!
Ciao,
L.

**Comment by aksr** [comment]
I know, thank you. Still, It should be default.

**Comment by fanglingsu** [comment]
In my opinion the `^` does not make any sense in vimb. In vi and vim this moves the cursor to the first none blank char on a line, which is very editor related. And there is no direct wa to force webkit to move the cursor onto the right position. OK, may be this could be done by a JavaScript or with some hack in Caret-Mode.
The `0` is more take from pentadactyl than vim, but is a common key to scroll horizontally to the left most position. The `^` isn't a scroll key in vim so I don't see a reason to add this by default.

**Comment by aksr** [comment]
Inside the browser, in *normal* mode, *key-mappings* (like `^`, `0`, `$`) refer to page. 
Having that in mind, `0` and `$` wouldn't also *make sense* because they  (according to legacy software) refer to line. Also, `0` (e.g. in *ed*, *sam*) would put cursor (*dot*) "before the first line" (meaning: *before the first character of the first line*). This is also the case with vim in ex mode.
I don't see any contradiction here, *vi(m)'s cursor motions* in browser, in fact, influence *the page* not *the cursor* (and they are *not actually* cursor motions). For me, this is consistent with other vi(m)-like software. 
(Pentadactyl uses both `^` and `0` - vim, too. They do the *same* thing.)

I felt obliged to defend my seeing of things. 
Anyway, I don't mean to impose my will, just thought of this as convenient, natural thing.

**Comment by fanglingsu** [comment]
I didn't notice that pentadactyl uses also `^` http://5digits.org/help/pentadactyl/buffer.xhtml#^, thank you for the hint. In this case we can add this to vimb too.

**Comment by aksr** [comment]
Thank you.
