### ISSUE TITLE
Vimb does not enter input mode for contenteditable='true' attribute

### ISSUE THREAD

**Issue by j1r1k** [fanglingsu/vimb#237]
Steps to reproduce:

1. Navigate to keep.google.com (must be logged in google account tho). 
2. Click into "Add note" field

Vimb should enter input mode at this point, but it does not. Input field is div with [contenteditable='true'](http://www.w3schools.com/tags/att_global_contenteditable.asp).

I suppose that this is not limited to keep.google.com, but I did not find any other app using this tag/attribute combo.

Might be somehow related to #114. But I did not fully understand the fix made there.

**Comment by j1r1k** [comment]
I have came with quick fix and I am not sure whether this is a nice solution - therefore I am humbly asking for review/comments.

Secondly this fix does work only with mouse click. It does not work with follow hint.

**Comment by fanglingsu** [comment]
The fix looks right, great work. I've merged it into the master branch. But we should eep the issue open to fix the other things related tpo editable elements.

1. Allow to focus contenteditable elements by hinting `;o` and possibly also `;y` and to switch vimb into input mode too.
2. Allow to use these elements with the editor command by hinting `;e` or if the focus is already on by `CTRL-T`.

**Comment by fanglingsu** [comment]
Moved the open enhancements into #248 so we can close this issue.
