### ISSUE TITLE
set status-font not working

### ISSUE THREAD

**Issue by sdothum** [fanglingsu/vimb#239]
I tried setting the status-font on the command line with --cmd="set status-font='monospace bold 8'" but the font setting does not appear to take. I vaguely recall we had a previous issue (resolved) with the "set statusbar=" command not taking as well in the vimb config file so this may be a similar problem.

"set status-font" shows the setting attempted at the command line. It just doesn't actually reflect the attributes. I haven't been able to test whether other fonts work.

**Comment by fanglingsu** [comment]
The issue with the statusbar was #164.

**Comment by fanglingsu** [comment]
This is a more serious issue. The `--cmd` args are evaluated on the early startup of vimb at a time where the setting data structures are not prepared and the settings are not known. We'll have to spent some more time to find a way to have to allow to use `--cmd` for all possible settings.

**Comment by fanglingsu** [comment]
Oh, sorry. My last comment is wrong. The setting works, but you should remove the single quotes around the `set='value'` value. The right call would be `--cmd="set status-font=monospace bold 8"`.

**Comment by sdothum** [comment]
Hmm.. I am not seeing any changes to the font size either manually from the colon prompt or the --cmd line.

**Comment by fanglingsu** [comment]
Did you use it without the quotes? The `:set status-font=monospace bold 8` on runtime should work. Have you compiled vimb against gtk2 or gtk3? There are some GUI-updating issues with gtk3, maybe also the status style is also affected by this.

**Comment by sdothum** [comment]
It's a puzzler. Tried both gtk2 and gtk3 versions (arch) without the quotes and using runtime.

fc-match monospace gives me this, nothing exotic..
LiberationMono-Regular.ttf: "Liberation Mono" "Regular"

Tried without style as well.

**Comment by fanglingsu** [comment]
Does it work when you use another font? You may try to run ivmb from cli and watch if there appear some relevant messages when you try to change the status-font.

**Comment by sdothum** [comment]
Doesn't appear to be font related (ie changing fonts has same no-effect). Also no messages appearing when launched from cli.

Only thing I can think of is that "infinality" may be interfering with the vimb status line.

**Comment by fanglingsu** [comment]
Have you tried to bypass or remove the infinality to verify that this is related to the issue?

**Comment by fanglingsu** [comment]
@sdothum Related to #239 maybe a update of infinality would remove this issue for you too.
