### ISSUE TITLE
set statusbar=false in config file not applied when start vimb

### ISSUE THREAD

**Issue by claudiuschan** [fanglingsu/vimb#244]
Hi,
I am using vimb-gtk 2.9 on FreeBSD-Current amd64. When i put the

set statusbar=false

in the config file under my ~/.config/vimb/config. It is not working. 

But I tried the 
set fullscreen=true
 it works. 

so I suspect the config is read during vimb startup, only the statusbar setting is not apply.

**Comment by fanglingsu** [comment]
This seems to be the same issue as #164. This is already fixed in master or release 2.10.
