### ISSUE TITLE
youtube issues

### ISSUE THREAD

**Issue by axionix** [fanglingsu/vimb#249]
If Flash is installed, loading a youtube video page will not play the issue until the page is refreshed. Youtube gives an error the first time.

If Flash is not installed (my preference) this error NEVER goes away and videos will not play at all. Yes, HTML5 is enabled for youtube.

**Comment by fanglingsu** [comment]
Can you please provide the error text that appears? Youtube with htm5 work well on all my systems, maybe you are missing some gstreamer package to get the videos working. Maybe following issue may help to find if there is a missing package #69 and #240.

**Comment by axionix** [comment]
@fanglingsu I did read both of those issues before filing.

The error text is:
An error occurred. Please try again later.

Here are my gst packages:
pacman -Q|grep gst
gst-plugins-base-libs 1.6.0-1
gst-plugins-good 1.6.0-1
gstreamer 1.6.0-1
gstreamer0.10 0.10.36-4
gstreamer0.10-bad 0.10.23-10
gstreamer0.10-bad-plugins 0.10.23-10
gstreamer0.10-base 0.10.36-3
gstreamer0.10-base-plugins 0.10.36-3
gstreamer0.10-ffmpeg 0.10.13-2
gstreamer0.10-good 0.10.31-9
gstreamer0.10-good-plugins 0.10.31-9
gstreamer0.10-ugly 0.10.19-15
gstreamer0.10-ugly-plugins 0.10.19-15

**Comment by shioyama** [comment]
Did you see [this comment](https://github.com/fanglingsu/vimb/issues/69#issuecomment-130175982) on #69? It fixed the issue for me on arch. I don't see `gst-libav` in your list of packages, I'd suggest trying to install it if you haven't already.

**Comment by axionix** [comment]
@shioyama Thanks, that single package was the problem.
