### ISSUE TITLE
Fonts readability

### ISSUE THREAD

**Issue by jam-jam** [fanglingsu/vimb#252]
Great project. Fast. Customizable. Don't change anything...except : 
In all webkit-based browsers I have tried, the displayed fonts of the most well-known websites are slim and uncomfortable. 
Vimb is no exception, and I was wondering if you could suggest a font configuration (either in vimb or on the system itself (I'm an arch user)) that would improve font readability. Example attached. 
Thanks a lot. 
![vimb_firefox_shot](https://cloud.githubusercontent.com/assets/953650/11103593/ac243f58-88c3-11e5-9d5c-44dc43b76d9c.png)

**Comment by fanglingsu** [comment]
Oh, I don't have any experience with font configuration. I've installed only some font's and have set the default fonts on my system and vimb to those of DejaVu. I know that's a stupid anwer, but have you tried to increase the default font size in vimb by one pixel `:set fontsize+=1`? This may look sometimes better.

**Comment by jam-jam** [comment]
Thanks for the prompt response. :set fontsize=+1 doesn't really affect the content fonts. It reflects on some of the titles, but not really the way I want it to.  
I'll fiddle around and post my font config once it is satisfying.

**Comment by jam-jam** [comment]
As promised, I came back to leave feadback.
I downloaded the google noto fonts (they are available in the arch "extra" repo).
This suits me for the moment.
