### ISSUE TITLE
URL in title

### ISSUE THREAD

**Issue by hoplaahei** [fanglingsu/vimb#256]
Add option to customise the window title to e.g., add the current site URI so that password managers such as KeePassX can pattern match against unique window title URL and autotype passwords for sites.

**Comment by fanglingsu** [comment]
I've never thought about this, maybe we can use some compiletime formatstring to determine what to show in the title.
If you really need the title to be the url for KeePassX you could use following workaround.
`:autocmd LoadFinished * sh! xprop -id $VIMB_XID -f _NET_WM_NAME 8u -set _NET_WM_NAME "%"`. Except of some pages, that do update the title periodically by JavaScript this should work. The autocmd is triggered for all pages when they are completely loaded and change the title of the window to the current url (`%` is expaned to the current url). Maybe you can even define also for `LoadCommited` and `LoadFirstLayout`.

**Comment by hoplaahei** [comment]
That should be fine most of the time, and then perhaps I could inject some script to override the javascript on misbehaving sites, or just disable scripts completely on said site.

I just made a small change of including both the title and the URL:

```
autocmd LoadFinished * sh! xprop -id $VIMB_XID -f _NET_WM_NAME 8u -set _NET_WM_NAME "$VIMB_TITLE ( % )"
```

That way I can still see the titles of open windows in my taskbar, but KeepassX can pattern match the URL. 

Thanks for the help.

**Comment by fanglingsu** [comment]
OK, I think I can close the issue.
