### ISSUE TITLE
Web inspector support?

### ISSUE THREAD

**Issue by djeik** [fanglingsu/vimb#261]
The web inspector is supported by libwebkit (possibly only as of libwebkit2, I'm not sure of the version). For instance, it's available in the surf browser, which uses libwebkit. Is it possible to access the inspector in vimb?
This would be great, as then I wouldn't need to keep Firefox for doing web development.

**Comment by cdlscpmv** [comment]
Set `webinspector = true`. Then press `gF`. The man page says about that.

**Comment by djeik** [comment]
@cdlscpmv Thanks!
