### ISSUE TITLE
Unable to nmap plus or minus keys

### ISSUE THREAD

**Issue by jmcantrell** [fanglingsu/vimb#263]
I'd like to be able to do:

    nmap <C-=> zI
    nmap <C--> zO
    nmap <C-0> zz

I've tried:

    nmap <C-equal> zI
    nmap <C-minus> zO
    nmap <C-0> zz

And capitalizing minus and equal.

Is this possible?

**Comment by fanglingsu** [comment]
Soory for the late answer. You are right the bindings you intend are not implemented at the time. The `<C-...>` works only for chars A-Z. I've not tested but I think those bindinge would also not work in vim.

**Comment by jmcantrell** [comment]
Ah, ok. Thanks for looking into it.
