### ISSUE TITLE
'file:///' URIs are not rendered, and are downloaded instead

### ISSUE THREAD

**Issue by AveryGlitch** [fanglingsu/vimb#264]
Whenever I try to view a html file on my hard drive (e.g. _'file:///home/avery/public_html/rawdog.html'_), it is not drawn, it is just downloaded to my downloads folder.

If I visit a directory, I get a directory viewing (as expected), but following any of the links results in (once again) a downloaded file.

**Comment by fanglingsu** [comment]
Thak you for the issue. I can't reproduce this on my system. I open local help files and documentations with vimb without any issue?
Does this behaviour also appear with empty config file?

    touch emptyfile
    vimb -c emptyfile

**Comment by AveryGlitch** [comment]
Yes, I still get this behaviour with an empty config file:
```
touch emptyfile
vimb -c emptyfile
    :o /home/avery/test.html       # results in Download <path> finished
    :q
vimb -c emptyfile /home/avery/test.html     # results in Download <path> finished
```
Same thing happens if I put 'file://' in front of the `/home/avery/test.html`.

I noticed, however, that I get the following error message in the console whenever one of these downloads starts:
```
** (vimb:18878): CRITICAL **: void webkit_download_start(WebKitDownload*): assertion 'priv->timer == NULL' failed
```
(Sorry about the delay in response)

**Comment by fanglingsu** [comment]
Sounds strange. Can you provide on which system you use vimb and which version you have. It seems that the webkit on your system triggers the 'download-requested' signal when you open the local file.
Another attempt:

    vimb -c emptyfile -C 'set universal-access-from-file-uris=on' /home/avery/test.html

The webkit error could be thrown by your `vimb :o /home/...`. Vimb expects the file to open as last argument and the `:o` is no option.

**Comment by AveryGlitch** [comment]
Sorry, I should have been more clear about the `:o` bit - the indented section in that code block is what I typed _after_ vimb launched.

The webkit error occurs no matter which way I open the file.

Your suggested command has the same result:
```
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

** (vimb:22114): CRITICAL **: void webkit_download_start(WebKitDownload*): assertion 'priv->timer == NULL' failed
```
My system is NixOS 15.09 _(Linux/x86_64 3.18.24)_, and this happened on vimb releases `2.9` and `2.11`

**Comment by bfortz** [comment]
Same problem here just appeared (archlinux, vimb 2.11, webkitgtk 2.4.11-1). The problem showed up after an update of the system, with vimb untouched. Could it be related to webkit or another external lib use for url handling ?

**Comment by fanglingsu** [comment]
I have latest vimb installed on archlinux too, with webkit .2.4.11-1 and can't reproduce the issue.

**Comment by bfortz** [comment]
After investigating a bit more: I suspect a bug in webkit, not in vimb,
with the function webkit_web_view_load_uri when the file has xhtml
contents.

**Comment by fanglingsu** [comment]
OK, then the issue could e located at [mimetype_decision_cb](https://github.com/fanglingsu/vimb/blob/master/src/main.c#L1535) where vimd decides if the response can be shown or have to be downloaded. Maybe we should add an check to never download from URIs beginnign with 'file://'

**Comment by bfortz** [comment]
Thanks for the feedback. I will look into this, making tests to see the
different mime_type reported on the different files I tested. The
solution of viewing any URI starting with 'file://' is a bit too
aggressive (especially if the file is binary). Note that a possible
enhancement could be to call xdg-open (if available) on local files that
are not viewable. vimb would then become as well a usable local file browser.

I will try to cook up something reasonable.

**Comment by fanglingsu** [comment]
Thank you for sending time on the issue. Hope we can fix this without much changes.

**Comment by yyt16384** [comment]
Maybe this is a bug in webkit. I have no problems here with webkit-gtk 2.4.10.

**Comment by JacksonGariety** [comment]
Same issue

**Comment by fanglingsu** [comment]
This is related to no more supported webkit1 branch. If it's an webkit issue, nobody will fix this.

**Comment by Artymort** [comment]
I have this issue with version `3.0-alpha` (AUR package `vimb`, but also manual build of master) with an empty config file. As far as I can tell my webkit version is `2.18.3-1`. Any update about this?

I can reproduce this way:
```bash
git clone [...]
cd vimb ; make ; cd src
touch empty
```

From here,
* `echo "content" | pandoc -t html5 -s | ./vimb -c empty -` works
* `echo "content" | pandoc -t html5 -s > tmp.html ; ./vimb -c empty tmp.html` downloads a file
