### ISSUE TITLE
Add an option to "don't let pages steal focus on input element when loaded"

### ISSUE THREAD

**Issue by lynnard** [fanglingsu/vimb#267]
This can be particularly useful on sites such as google.com; I remember several other vimperator-like browsers supporting this e.g., vimium

**Comment by fanglingsu** [comment]
Have you tried to use `:set strict-focus=on`. This was intended to prevent the page to switch vimb into input mode automatically.

**Comment by lynnard** [comment]
Ah, forgot about this option :) Perfect, thanks!
