### ISSUE TITLE
Possible to rebind mouse?

### ISSUE THREAD

**Issue by rodyaj** [fanglingsu/vimb#268]
I would like to rebind right click to open a link straight away like middle click would. Is this possible?

**Comment by fanglingsu** [comment]
There is no real mouse support in vimb. So you have to patch it to use the right click to open links. Note that you will not be able to use the right-click-contextmenu then.
You can add the right mouse key in main.c [main.c button_relase_cb](https://github.com/fanglingsu/vimb/blob/8ae4cadf58e46b3e9951fa89cf084bd2792984c3/src/main.c#L1367) should be `event->button == 3`.

**Comment by rodyaj** [comment]
Ok thanks. Seems simple enough to patch in.

**Comment by rodyaj** [comment]
Another thought on this: I noticed the url is displayed in the statusbar when the mouse hovers over a link. Is there any way to get this link piped into an open command? Then I could bind the open link using external tools like xbindkeys, without having to grep for changes in source code and patch each release. Thanks.

**Comment by fanglingsu** [comment]
I fear I don't understand what you want to reach with that? You want to open links with the mouse by using the right mouse key, right? Why not right click an selecting "open link in new window"? OK a lot of work to get the page opened, but maybe you could simplify this with xbindkeys and/or xdotool a little.

**Comment by rodyaj** [comment]
In my setup middle click is unusable because the window manager consumes it for other things (so applications can't use it). I would explain my unusual setup, but want to keep on point.

I don't want to right click and select open in new window, as it is cumbersome. You are right that I could use X automated tool to catch right click event and send e.g., right click + down arrow + enter to vimb windows only. I will try to get something working like this if all else fails.

But I use a trackpoint/mouse stick on a laptop which is in middle of my keyboard keys, so it would be easy for me to open link by e.g., hovering on link with cursor and pressing 'h' key, which is right next to my mouse stick. So if I could bind 'h' key to open new vimb window with the URL under the mouse (not the URL of the current page), it would be nice. It seems from the man page that I can retrieve URL of current page, but not the URL under the mouse though, so I am thinking it is not possible.

**Comment by rodyaj** [comment]
I was thinking I could use a script compressor to call :eval on some javascript code that gets the link under the cursor, or add it to ~/.config/vimb/scripts.js:

```
document.addEventListener('mouseover', function(event) {
    var hoveredEl = event.target; // The actual element which was hovered.
    if (hoveredEl.tagName !== 'A') { return; } // Ignore non links
    console.log(hoveredEl.href); // Do what we want here!
});
```

But I 'm still trying to figure out if it is possible for me to get the contents of hoveredEl.href piped into an :open command.

**Comment by fanglingsu** [comment]
If you only want to open link into a new window by mouse/trackpoint without using the middle mouse button you can still use `CTRL-LeftMouseButton`. At the moment I don't see a way to get the hovered link url into a prepared open command. One way to do would be the socket, but this can't be triggered from JavaScript.
