### ISSUE TITLE
web inspector crashes the browser

### ISSUE THREAD

**Issue by acodispo** [fanglingsu/vimb#271]
When I open the web inspector, the inspector begins to load, and then the window crashes after a second or two. Doesn't seem to matter what page, though I haven't tested widely.

Not sure where to start in debugging this. Perhaps someone can point me in the direction of a helpful log?

I ran vimb from the console to see if I could get any output. Used a very simple html file:

``` html
<html>
   <head>
      <title>Test!</title>
   </head>
   <body>
      <h1>Test!</h1>
      <p>This is the <em>test</em> file.</p>
   </body>
</html>
```

Ran the file (it rendered fine), then hit `gF` and it crashes:

``` bash
$ vimb test.html 
** Message: console message: resource:///org/webkitgtk/inspector/UserInterface/Main.js @665: Localized string "Hide console (%s)" was not found.

Segmentation fault (core dumped)
```

I'm on Arch Linux with vimb 2.11.

Thanks for any help you can give!

**Comment by fanglingsu** [comment]
I get the same error message on all my systems. But vimb never crashed on opening the webinspector, neighter on my Arch Linux nor on the Ubuntu system of my wife.
A first attempt would be to compile vimb with debug symbols.

    CFLAGS="-ggdb -g -O0" make

And to make shure that the core dump is saved by calling `ulimit -c unlimited` on the terminal before starting vimb.

Did you compile vim agains GTK2 or GTK3 (`make GTK=3`), maybe it's related to the GTK. I compile always agains GTK2.

**Comment by fanglingsu** [comment]
Close of long time of inactivity. Hope this crash will disappear with webkit2.
