### ISSUE TITLE
segfault on www.gentoo.org

### ISSUE THREAD

**Issue by glsubri** [fanglingsu/vimb#272]
Hi,
I don't know what changed on www.gentoo.org, but now, everytime I want to open this page or wiki.gentoo.org, vimb crashes.

This bug is reproducible by going to www.gentoo.org
My vimb version 2.9. I'm on a GNU/Linux Gentoo machine. My kernel is 4.1.15-r1.

Thanks,
glsubri

EDIT: Also, I compiled vimb with gtk3

**Comment by fanglingsu** [comment]
Did you compile aganis GTK2 or GTK3? Does vimb also crash is JavaScript is disabled (`vimb -C 'set scripts=off' www.gentoo.org`)? I can't reproduce this issue.

**Comment by glsubri** [comment]
I compiled against gtk3. Vimb also crashed with javascript disabled.

**Comment by yyt16384** [comment]
I used to have this problem (and also on some other sites), but it doesn't happen anymore now. Maybe you should try upgrading to latest version (the version in repo is quite old).

**Comment by fanglingsu** [comment]
@glsubri Have you tried to compile latest version?

**Comment by glsubri** [comment]
@fanglingsu No, not yet. But I will. Thanks

**Comment by wahrwolf** [comment]
i have the same iussue, but on several websites. It occurs randomly on time and pages ...

**Comment by yyt16384** [comment]
@wahrwolf Does it still crash with javascript disabled? If it doesn't, it is probably a different issue.

**Comment by wahrwolf** [comment]
it seems to be a problem of javascript ... any way of handling those errors?

**Comment by fanglingsu** [comment]
@wahrwolf You can try to set environment Variable `JavaScriptCoreUseJIT=0` (see also #203). You can try if this will work by calling vimb as `JavaScriptCoreUseJIT=0`.

**Comment by hsoft** [comment]
I was experiencing similar random crashes with one being reproducible (opening a foreign key "+" popup in a [Django](https://www.djangoproject.com/) 1.8.x admin window) and I confirm that the crash stops when setting `JavaScriptCoreUseJIT=0`. Thanks for the tip @fanglingsu .

For the record, I'm on a gentoo system running on a Raspberry Pi 3 (`armv7l`) and I compiled vimb with `GTK=3`.
