### ISSUE TITLE
Hinting doesn't work on reddit.com

### ISSUE THREAD

**Issue by florianbeer** [fanglingsu/vimb#273]
I am using the latest vimb (gtk3) version from git and using it to browse reddit doesn't let me use any hints. They do appear when I press "f" but then selecting one just lets them disappear again but no action is taken. I have to use my mouse to click.

**Comment by fanglingsu** [comment]
OK, I can reproduce this issue if I enable Javascript. Without Javascript the hinting works. I'll try to inspect what going on there when the hints are fired.

**Comment by florianbeer** [comment]
Cheers mate!
I guess I could selectively disable JS on Reddit in the meantime. 

Thanks for looking into it. 

_____________________
DI (FH) Florian Beer
42dev e. U. - web solutions & hosting services
+43 699 14422569
http://42dev.eu

**Comment by fanglingsu** [comment]
I don't see through what reddit does with the click events. At the time vimb fires a fake mouse event on the element to trigger the click. This does not work on reddit.com, when I change this to call the JavaScript method `e.click()` on the element the links are opened, but this does not allow to open them into a new window and does not work with duckduckgo.com. I'd have to dig deeper into the issue and test the behaviours of some other hinting browsers.

**Comment by parnmatt** [comment]
Has there been any progress on this issue?

**Comment by fanglingsu** [comment]
I didn't find time to check what block our JavaScript triggered click events there. I fear that we could not get vimb working there even if we know that reddit does some fancy logic on the click events.

**Comment by fanglingsu** [comment]
The hinting make a lot of trouble and I'm not sure if it was a good choice to add it to vimb. I close this to clean up the issue to keep developers focused on the webkit2 branch.
