### ISSUE TITLE
sf.net mailing list archive does not work (HTTP 500 status)

### ISSUE THREAD

**Issue by smemsh** [fanglingsu/vimb#277]
https://sourceforge.net/p/vimb/vimb/vimb-users/ is broken

**Comment by fanglingsu** [comment]
Where did you find the url? In the README of the project and the webpage the url is right https://lists.sourceforge.net/lists/listinfo/vimb-users.

**Comment by smemsh** [comment]
the archives are the very first link on the page you reference.

I didn't say the list didn't work (although I didn't try), I said the
archives don't work.

**Comment by fanglingsu** [comment]
OK, the page the link is on is not under my control, seems to be a sourceforge bug. The mail archive for other projects work fine, but our not. Strange.

**Comment by smemsh** [comment]
just trawling old tickets, checked the link, this seems to work now.  closing ticket.
