### ISSUE TITLE
Key mappings

### ISSUE THREAD

**Issue by aksr** [fanglingsu/vimb#283]
I changed a few key-bindings to emulate **readline** key-bindings when in command mode, but keys like `<Left>`, `<Right>` etc. don't work if on {rhs}. Something like this:

    `cmap <C-b> <Left>` (left)
    `cmap <C-f> <Right>` (right)

Is this intended? If so, could this behaviour be changed?
Is there another way to achieve the same thing?

**Comment by fanglingsu** [comment]
This is a know none working keybinding. You can find more information about this in #56. There are also some hint's how to change the bahaviour via the gtk configuration mechanism. I hope this will help you to change the keybindings to you need in command mode. If you have trouble with that, please feel free to ask for help here, maybe we can help you.
