### ISSUE TITLE
Shortcuts without arguments

### ISSUE THREAD

**Issue by aksr** [fanglingsu/vimb#284]
Currently, shortcuts without arguments don't do anything useful.
I doubt google search for `g` or `i` or `s` etc. is useful for anyone.
For example, _conkeror_ has `$alternative` for shortcuts without arguments, e.g:

```
 define_webjump("lwn.net", "http://lwn.net/Search/DoSearch?words=%s", $alternative="http://lwn.net");
```

Somethink similar would be nice to have.
What do you think?
Is there a way to implement this?

PS: $[0-9] is a really useful feature ;)

**Comment by fanglingsu** [comment]
> I doubt google search for g or i or s etc. is useful for anyone.

You are right, to use a shortcut without arguments makes no sense. But I don't see the need to add code to do a fallback to something else. The user decides what vimb should do, or in this case what the shortcuts work. So I assume that the users know what they are typing in the statusbar. When I understand the webjump right, the path part of the url is stripped away, if the webjump is called without arguments (or the given alternative is taken). But in this case is nothing more than opening a bookmark to the alternative page.

**Comment by aksr** [comment]
> You are right, to use a shortcut without arguments makes no sense. 

Of course, but it *could* make sense, it *could* be useful.
For example, w (for wikipedia):
`w` (without arguments) would go the wikipedia main page, e.g:

    https://en.wikipedia.org/wiki/Main_Page

Yet, `w Albert Einstein` searches wikipedia, e.g:

    http://en.wikipedia.org/wiki/Special:Search?search=Albert+Einstein

There are plenty examples like this (*imdb* news and search for title/actor etc.).
Besides Conkeror, Firefox has the same possibility using `OpenSearch`.

**Comment by aksr** [comment]
Pity.

**Comment by fanglingsu** [comment]
@aksr Can you have a look at the pull request #329 from @rti? Would this approach help you?

**Comment by aksr** [comment]
@fanglingsu: **Well, it's better then nothing.** (While very few would search for *g* or *w* or *whatever*.)
Still, having/using only one shortcut (e.g. `w`) is easier and more elegant.
However, if it *very much* complicates the code to have something like this, then, I guess, it's not worth it.
