### ISSUE TITLE
feature request: text select/copy mode

### ISSUE THREAD

**Issue by chairmank** [fanglingsu/vimb#285]
Sometimes I want to select and copy a snippet of text on a web page. I can use the pointing device to select into the X selection buffer, but I prefer to avoid touching the rodent. It would be very convenient to have a selection mode like visual mode in vim or copy mode in tmux.

**Comment by fanglingsu** [comment]
I think to have a selection mode would be nice. But I'm note sure if webkit provides an API that allows to do this. For now you can work around this by using search to mark a specific content on the page, switch on 'caret browsing' by `:set caret=on` and use the webkit builtin keybindings to move the cursor to make a selection (Shift-(CTRL)-Cursor). I know, that is cumbersome and not vim-like, but it works also without mouse.
