### ISSUE TITLE
Option to inverse history and bookmarks completion

### ISSUE THREAD

**Issue by antoyo** [fanglingsu/vimb#289]
Hello.
I don't use the history and I would like to have the bookmark completion by default.
I know I could use `nnoremap o :open !`, but if I only want to input an URL, I need to delete the `!`.
So, it would be nice to have an option to inverse the history and bookmarks completion, so that `:open <TAB>` will complete by bookmarks instead of history.
Or perhaps it could be done automatically if `history-max-items` is set to 0.
Thanks.

**Comment by fanglingsu** [comment]
For me it would be confusing when the completion would be changed by setting
the `history-max-items`. the feature make not much sense in my opinion. So,
can patch vimb to apply this change.

```patch
diff --git a/src/ex.c b/src/ex.c
index f0b00f3..e3f83b3 100644
--- a/src/ex.c
+++ b/src/ex.c
@@ -1166,9 +1166,9 @@ static gboolean complete(short direction)
                 case EX_OPEN:
                 case EX_TABOPEN:
                     if (*token == '!') {
-                        found = bookmark_fill_completion(store, token + 1);
+                        found = history_fill_completion(store, HISTORY_URL, token + 1);
                     } else {
-                        found = history_fill_completion(store, HISTORY_URL, token);
+                        found = bookmark_fill_completion(store, token);
                     }
                     sort = false;
                     break;
```
