### ISSUE TITLE
Multiline settings

### ISSUE THREAD

**Issue by antoyo** [fanglingsu/vimb#290]
Hello.
It is possible to span a command over multiple lines in the `config` file?
I would like to be able to enable JavaScript for multiple websites, like so:
```
autocmd LoadCommited
    { http://rustbyexample.com/
    , https://doc.rust-lang.org/
    }* set scripts = true
```
but it does not work on multiple lines.
I know I can use multiple commands, but I find it less convenient.

If it is possible to do so in another way (perhaps using a variable?), please tell me.

Thanks.

**Comment by fanglingsu** [comment]
At the time there is no way to use multiline commands. Neighter in config file nor via inputbox. So you have to write it into a single line.
