### ISSUE TITLE
Command to set the tags for the current bookmark

### ISSUE THREAD

**Issue by antoyo** [fanglingsu/vimb#292]
Hello.
It would be nice to have a command to set/edit the tags for the current bookmark.
That would be very useful to add tags at the same time as adding a new bookmark.
Thanks.

**Comment by fanglingsu** [comment]
Not sure what you mean. You can already set the tags for a boorkam you make by `:bma tag1 tags2`. OK edit does not work directly but you could remove the bookmark by `:bmr` and add it again.

**Comment by antoyo** [comment]
I did not know we can add the tags while adding the bookmark.
It is sufficient for me: if I need to edit, I will edit the bookmark file directly.
