### ISSUE TITLE
set status-font on command line

### ISSUE THREAD

**Issue by sdothum** [fanglingsu/vimb#305]
This issue is a follow-up to #239 when attempting to set the status-font with --cmd="set status-font=.." from the command line. The startpage does not reflect the font request. 

But, subsequent tabopens do reflect the font spec. Also, curiously, opening a link on the startpage and going back with Ctrl-O does refresh the status-line with the font spec.

Wonder if we just have a page display initialization sequence problem here with the startpage?

**Comment by fanglingsu** [comment]
Can't reproduce this. Ther are multiple status font settings at the time, one for http-Pages, one for https pages and one for https-Pages with untrusted certificate `status-font`, `status-ssl-font` and `status-sslinvalid-font`. May be you set only one an your start page use another one.

**Comment by sdothum** [comment]
That did it.. providing font specs for ssl and sslinvalid. Thanks.
