### ISSUE TITLE
Shortcuts not saving from session to session

### ISSUE THREAD

**Issue by SamTay** [fanglingsu/vimb#315]
Shortcuts are not saving for me after I quit a `vimb` instance. I don't see them being specified as saved in configuration anywhere in the docs... but can't imagine this is working as intended. Is this a bug?
```shell
$ vimb --version
vimb/2.11
```

**Comment by cdlscpmv** [comment]
Anything you configure inside vimb is not saved automatically. You have to put your settings in `~/.config/vimb/config` in order to make them permanent.

**Comment by SamTay** [comment]
Ah gotchya. Somehow that flew over my head. Thanks.
