### ISSUE TITLE
Socks5 support

### ISSUE THREAD

**Issue by iacchus** [fanglingsu/vimb#316]
Can you suggest me a way I can use socks5 with vimb? (using ssh -D as proxy)

**Comment by fanglingsu** [comment]
I'm not sure, but as I know you can set the socks proxy also via the http_proxy environment variable but with socks protocol like this `export https_proxy="socks://hostname:port"`. If you export this in your shell an start vimb, this should be picked up.

**Comment by fanglingsu** [comment]
The socks proxy should work out of box with webkit2. There is no more development action in webkit1 branch of vimb. So I close this.
