### ISSUE TITLE
Doxygen Documentation

### ISSUE THREAD

**Issue by Phenitei** [fanglingsu/vimb#327]
It would be nice for contributors if there was an indexable documentation (faster then re-searching through the source files when we don't know the project very well yet); I think the standard for C would be doxygen but really anything generating an indexable documentation would do. I am voluntary for writing as much as possible if you think it a good idea.

**Comment by fanglingsu** [comment]
I've never used such documentation, but as I understand it's only a convention how comments are written in the code so that the doxygen can use them to generate the documentation. If it does not add a new dependency, you are pretty welcome to start the transformation of the comments.

**Comment by Phenitei** [comment]
You are correct, it requires nothing more than a small effort in comment formatting. Users are then free to use them or not to generate code documentation. I'll open a PR with a proposed doxygen config file and start commenting away.

**Comment by rti** [comment]
What do you think about a make target to generate the docs?

**Comment by Phenitei** [comment]
First thing I did, though typing 'make doc' is not so much longer then typing 'doxygen'!
Things are coming around gently, especially since a number of functions already had well-formatted documentation comments (modulo a few syntactic details). I should have a PR ready soon enough.

**Comment by Phenitei** [comment]
@fanglingsu Would you rather a PR with everything as documented as I can, or just doxygen configuration and doc template comments everywhere to be filled as we go on ? Both are fine, the first will take a bit more time (I'll probably finish by the end of this week-end), second can be opened in an hour or so.

**Comment by fanglingsu** [comment]
Do as much as you can. I don't have much time and in case you do fast work I would probably take much longer to merge the PR.

**Comment by fanglingsu** [comment]
@Phenitei You use the `\Param` syntax. Is this common for such documentation? Most projects seem to use some `@param` syntax which (event if they use some other documentation tools).

**Comment by Phenitei** [comment]
doxygen parses @word and \word interchangeably. I prefer typing \ than @ because I have a qwerty, but the only important thing is coherence, so if you think more people use @ I don't mind.

**Comment by fanglingsu** [comment]
Some of the comments already use the `@param` syntax so I think we should keep it. I'm not sure, but the tools that I've seen used to simplify the doxygen use the `@` out of box. So I'd prefer that, if this is possible.

**Comment by Phenitei** [comment]
No problem on my part, will do!

**Comment by fanglingsu** [comment]
Thank you for your contribution!

**Comment by Phenitei** [comment]
My pleasure - I use vimb everyday; though not very profficient in C I like to help when I can!
