### ISSUE TITLE
Trying to build webkit2 version...

### ISSUE THREAD

**Issue by paoloap** [fanglingsu/vimb#331]
When I try to "make runsandbox" get this:
```
vimb [webkit2] % make runsandbox
make[2]: Nessuna operazione da eseguire per "all".
cc ext-util.lo
ext-util.c:23:23: fatal error: ../config.h: File o directory non esistente
 #include "../config.h"
                       ^
compilation terminated.
make[2]: *** [Makefile:17: ext-util.lo] Error 1
make[1]: *** [Makefile:16: src/webextension.subdir-all] Error 2
make: *** [Makefile:43: sandbox] Error 2
```
Idem if I try to "make". I would like to run it and to test some websites that are not accessible from stable version (i.e. web.whatsapp.com). Any suggestion?

Thanks!

**Comment by rti** [comment]
Hi,

You need to copy the file `config.def.h` and name it `config.h`.

So from the project root folder you should run:

`cp src/config.def.h src/config.h`

Then, run `make runsandbox` again. 

Hope that helps.

**Comment by fanglingsu** [comment]
The config.h file should normally be copied during make in _src/Makefile_. I assume that we have to rework the Makefiles. At the moment the make of the webextension is also triggerd from the base Makefile which does not consider the dependencies between vimb and the webextension. So it might be that make starts first building the webextension which needs the _../config.h_ but the rul how to generate the config.h is located in _src/Makefile_.
@rti Do you think it would be an option to start the webextension make from _src/Makefile_ instead from _Makefile_? So we can make sure that the config.h is generated prior to the webextension.

**Comment by paoloap** [comment]
Applying the workaround posted by @rti it compiles and works properly!
Guys... I will never thank you enough for your work... this can become the definitive minimal browser, the first one with a modern web engine. I'm just frustrated because I don't code in C since decades and I'm not enough skilled to help. Keep going, thanks for your work!

**Comment by fanglingsu** [comment]
I've restructured the Makefiles so that this sould work now even when no src/config.h is present.
