### ISSUE TITLE
Multiple ex commands on startup (--cmd, -C)

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#342]
Run multiple ex-commands during startup using the ```--cmd,-C``` options.

Check vimb2 [1] for a reference implementation.

[1] https://github.com/fanglingsu/vimb/blob/master/src/main.c#L1897

**Comment by fanglingsu** [comment]
There was only one user who requested this feature. Well sometimes this allows easier testing during development, but we can set a custom config file via `-c` option or run a custom profile. So I think we could kick this feature out.
