### ISSUE TITLE
External editor

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#347]
Allow editing texts (e.g. from ```<textarea>```) in external editor (e.g. vim (: ).

Implemented in vimb2 already. The code [1] can be used as reference.

[1] https://github.com/fanglingsu/vimb/blob/master/src/input.c#L105

**Comment by hsoft** [comment]
I hadn't noticed this issue before and thought that it was part of #349, but as I wrote in my pR at #386, I excluded it from my work anyway...

**Comment by rti** [comment]
looking into it

**Comment by rti** [comment]
Draft implementation ready, ported from vimb2, using js calls from main app instead of webkit2 API for simplicity. Still requires some fixes and cleanup.

https://github.com/fanglingsu/vimb/compare/webkit2...rti:347_external_editor

**Comment by fanglingsu** [comment]
@rti Looks promising. But we need a solution how to get the current form field text into the spawned editor. So I thinks we have to call the webextension to return the text from the form field and to disable the field. After editing the file we have to clal the webextension to put in the text into the right form field. This would require the webextension to keep the form field element stored so that the text can be written into the right one.

**Comment by rti** [comment]
@fanglingsu this is already working. Everything you mentioned is done via JS, disabling, enabling, getting setting the value. To store the currently focussed element, it uses the same JS variable already used for input field tabbing.

The only shortcoming I can currently think of is the issue with IFrames you pointed out earlier (#328).

**Comment by fanglingsu** [comment]
@rti Oh, sorry for the clutter, I didn't read the code very carefully. Yes IFrame are an issue, but I presume that we're allowed to access frames out of the same origin via the webextension.

**Comment by rti** [comment]
@fanglingsu Hmm, so you think we have to take the webextension path in the end? Would you still accept a merge request implementing the current approach? Maybe it's better than nothing? I could look into the webextension thing in a next step then.

**Comment by fanglingsu** [comment]
I want to have the feature and the current approach seem a good way to get it. I personally do not understand the whole dbus stuff and there seem to be many unresolved corenercases at the time. A Pull-Request is pretty welcome!
