### ISSUE TITLE
Update distribution packages

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#364]
In order to allow users to install vimb3 (webkit2) easily, we could provide packages for distributions. I'd start with Arch Linux and Gentoo.

What other distributions should be added to the list?

Vimb2 has several distribution packages already [1].

We could start adding the package sources / build scripts to the vimb git repository to track them properly.

[1] https://fanglingsu.github.io/vimb/#packages

**Comment by rti** [comment]
Just to track it here: @hsoft built a gentoo package https://github.com/hsoft/portage-overlay/tree/master/www-client/vimb

Nice one! Thanks a lot!

**Comment by fanglingsu** [comment]
I think we should put the links to packages into the README.md and later on the web page too.

**Comment by tharvik** [comment]
I also put a Gentoo ebuild [there](https://github.com/tharvik/overlay/tree/master/www-client/vimb) but for the live version instead of the packaged version.

**Comment by rti** [comment]
@tharvik nice, thanks a lot. 

Can you describe what [this line](https://github.com/tharvik/overlay/blob/master/www-client/vimb/vimb-9999.ebuild#L29) is for? I cannot find any match in the current ```Makefile```. Maybe that's an old bug? Or is it something that should be fixed on the vimb side?

**Comment by fanglingsu** [comment]
@rti Right, the EXTPREFIX mistake was removed by c52088d89aa94d036da8ab5b8b7b47416c4996dd, so mentioned line is not necessary.

**Comment by tharvik** [comment]
Fixed in tharvik/overlay@fec6503.

**Comment by rti** [comment]
Placed a comment to update the failing arch linux aur package

https://aur.archlinux.org/packages/vimb-git

**Comment by fanglingsu** [comment]
Now it's unmaintained.

**Comment by rti** [comment]
@fanglingsu should I adopt this poor package? Do you want to?

**Comment by fanglingsu** [comment]
@rti I don't have time for this. I hope you or someone else could do that.

**Comment by rti** [comment]
https://aur.archlinux.org/account/aksr took it. Long live aur/vimb-git!

**Comment by rti** [comment]
It's a week since askr took the package ownership. He updated it but it's still broken. He is unresponsive since then. I'll ping him again.

https://aur.archlinux.org/packages/vimb-git

**Comment by rti** [comment]
FYI, I just adopted https://aur.archlinux.org/packages/vimb/
Currently, this is still on vimb2. I think I will update it to vimb3 alpha soon.

**Comment by fanglingsu** [comment]
I plan to switch to semantic versioning so it would be the best to install 3.0-alpha as 3.0.0.

**Comment by rti** [comment]
@fanglingsu As I understand semantic versioning we can still append the alpha: 3.0.0-alpha1. What do you think/

**Comment by rti** [comment]
For the record, I just submitted an orphan request to aur for vimb-git as aksr still did not fix the build/installation issue and vimb-git remains broken on arch linux.

**Comment by fanglingsu** [comment]
@rti Yes, 3.0.0-alpha1 is valid for semantic versioning, but the archlinux pagebuild does not like this and I don't like it too. After alpha comes beta, when is it time for beta? For me it's easier to think of backward compatibility and api changes. But I must admit that I don't think to much about versioning - I incremented the version number from time to time. So I want to follow the semnatic versioning to for myself to think more about what is put into a bugfix and what should become a new minor version.

**Comment by rti** [comment]
Finally aksr updated the package ```vimb-git``` and so did I for ```vimb```.

Now we have:

```
aur/vimb 3.0.0.r1466.5bca294-1 (27, 1.80)
    The vim like browser
```

and 

```
aur/vimb-git 3.0.0.r1461.46d6f0d-1 (17, 0.43)
    A Vim-like web browser that is inspired by Pentadactyl and Vimprobable.
```

**Comment by rti** [comment]
Correction: aur/vimb now uses the latest tag: ```3.0-alpha```

```
$ pacaur -Ss vimb
aur/vimb 3.0.0.1-2 (27, 1.79)
    The vim like browser
```

I messed up the version number: To actually upgrade from ```3.0.0.r1461.46d6f0d``` to ```3.0.0``` I had to append a ```.1```. With the next vimb release, the package version number will be clean, e.g. ```3.0.1``` or ```3.1.0```.

**Comment by rti** [comment]
vimb update to 3.1.0 in aur done: https://aur.archlinux.org/packages/vimb

I don't know. For me, this issue could be closed now. Maybe we could open individual issues for further distribution packages once we plan to create them.

**Comment by fanglingsu** [comment]
@rti Thank you for updating the package.
