### ISSUE TITLE
Support webrtc?

### ISSUE THREAD

**Issue by pojoin** [fanglingsu/vimb#366]
Can not be called 'navigator.webkitGetUserMedia' .

**Comment by fanglingsu** [comment]
According to the webkit team the webrtc is still in development [https://webkit.org/status/#specification-webrtc].

**Comment by mfiano** [comment]
According to the status page, WebRTC is now supported, but same error with vimb.

**Comment by fanglingsu** [comment]
@mfiano Strange that they say it's implemented but according to http://www.webrtcinwebkit.org/ it is not. I think this must be enabled to work because the useMedia is disabled by default.
