### ISSUE TITLE
incsearch adds history items for every typed char

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#372]
When ```incsearch``` is activated, every character added to the search term will add another item to the search history.

# Steps to reproduce
- enable ```incsearch``` via ```set incsearch=true```
- open search via ```/```
- type a word, e.g. "abcd" and ```<enter>```
- reopen search via ```/```
- press ```<ctrl>p```several times to inspect search history items

# Expected behaviour
- every search term commited with ```<enter>``` created a history item, e.g. "abcd", the search done before, etc.

# Actual behaviour
- every single character created a history item, e.g. "abcd", "abc", "ab", "a"

**Comment by fanglingsu** [comment]
@rti I think we should try to move the incsearch logic into the `command_search` function so that we don't need to call `command_search(c, &((Arg){0}));` direct to stop searching with all the cleanup and restarting it again.

**Comment by rti** [comment]
@fanglingsu basically followed your approach.

Though, I do not store the last search string to compare but use an explicit parameter for ```command_search()```. I think this is straight forward and fast. Comparing strings might lead to cornercases e.g. when ```incsearch``` is disabled and the user searches for the same string twice.

**Comment by fanglingsu** [comment]
Thank you! Great work! I've change the behaviour that the search is only triggered on stepping through history but not in case of stepping through completion list.
