### ISSUE TITLE
Update project page

### ISSUE THREAD

**Issue by fanglingsu** [fanglingsu/vimb#377]
Update project page in branch gh-page for the webkit2 branch.

During this rework the page for the manual should be removed. It's to expensive to maintain the manual in the code and as markdown for the page and keep both in sync.

**Comment by rti** [comment]
I like the idea to have the manual on the webpage as well. It's always available to everybody, it's easy to link there...

If you really want to go with pod #378, there is also pod2html http://perldoc.perl.org/pod2html.html

**Comment by fanglingsu** [comment]
At the moment it's easier for me to edit the nroff format of the man page direct. The webpage is generated from markdown too, so we could possible use nearly the same soures for both, than man page and the manual. I'm not sure if it's worth the effort to have the manual on the webpage. I think it would be enaugh to link to the man on github (if this is in markdown it will eb schon in a nice way).
