### ISSUE TITLE
Open the last closed page

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#379]
Implemented on the master branch already. There are also some stubs on the webkit2 branch. E.g. [1]. Though, the functionality has not been completely ported to the webkit2 branch yet.

- no new entries are added to ```~/.config/vimb/closed```
- old entries in ```~/.config/vimb/closed``` are not parsed correctly

[1] https://github.com/fanglingsu/vimb/blob/webkit2/src/normal.c#L597

**Comment by fanglingsu** [comment]
You are right. The open last closed page works, in case there is only one last closed page in the file. But the logic can't handle multiple lines at the time. So this bus appers only in case there is a `~/.config/vimb/closed` file written by latest webkit1 vimb. So we need to readd the features to allow to store multiple last closed pages from 8ae4cadf58e46b3e9951fa89cf084bd2792984c3 to th webkit2 branch.
