### ISSUE TITLE
Download path not honored

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#380]
The setting ```download-path``` is not honored. Regardless of what is configured, downloads are stored in ```~```.

### Steps to reproduce
- set the download path to some path except for ```~```
  - e.g. ```:set download-path="~/Downloads"```
  - make sure the path exists
- download a file

### Expected behaviour
- the download is stored in ```download-path```

### Actual behaviour
- the download is stored in ```~```

**Comment by fanglingsu** [comment]
I did not test this, but I assume this might be inserted by 597a0acfd9e35f6516a6c5069fdf651416e9f11c.

**Comment by rti** [comment]
The issue is indeed fixed with edd5bec.
