### ISSUE TITLE
Download fails if file exists

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#381]
Downloading two files with the same name does not work. The second download instantly finishes, the file on disk does not change.

### Steps to reproduce
- download a file
- wait for the download to finish
- make sure the file was created and check the timestamp
- download the same file again
- wait for the download to finish

### Expected behaviour
- the file downloaded first is not touched
- a second file is created next to the first one, having "_2" appended before the file extension

### Actual behaviour
- the file downloaded first is not touched
- the second file does not exist

**Comment by fanglingsu** [comment]
@rti Could you please check if the issue is fixed for you too? I could not reproduce die mentiones issue direct but got other errors.

**Comment by rti** [comment]
Sorry for the late response. Yes, the issue is indeed fixed by edd5bec.
