### ISSUE TITLE
Setting for hint css styles

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#391]
I'd like to have (parts) of the hint css style to be user configurable via settings, just like the style of the status bar, input field, etc. 

Maybe we should always append certain settings to the user defined style. This way we could prevent unexpected results if the user forgets to add mandatory things like ```position:absolute; z-index:100000``` to his styles.

**Comment by fanglingsu** [comment]
I'm not sure if it's worth to add a setting to apply user style to the hints. In my opinion it's enough to allow the user to overrule the css by user defined stylesheet in .config/vimb/styles.css which already works.

**Comment by rti** [comment]
You are totally right. I just tried it and it works like a charm. Thanks a lot.

Just for documentation purposes: This was related to #349.

My hint style now looks like this:

```~/.config/vimb/style.css```
```
/* Base16 Eighties Color Scheme by Chris Kempson (http://chriskempson.com) */

._hintLabel {
    background-color: #f2f0ec !important;
    border: 1px solid #2d2d2d !important;
    color: #2d2d2d !important;
    font: bold 10pt monospace !important;
    opacity: 1 !important;
    padding: 0.1em !important;
    padding-left: 0.4em !important;
    padding-right: 0.4em !important;
}
._hintLabel._hintFocus {
    font: bold 13pt monospace !important;
}
._hintElem {
    background-color: #ffcc66 !important;
    color: #2d2d2d !important;
}
._hintElem._hintFocus {
    background-color: #6699cc !important;
    color: #2d2d2d !important;
}
```
