### ISSUE TITLE
External editor does not support content editable elements

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#396]
Editing content editable elements does not work vie the external editor.

### Steps to reproduce
 - Let vimb render this page:
 ```<html><body><p contentEditable="true">This is an editable paragraph</p></body></html> ```
 - Focus the paragraph
 - Press CTRL-T to open the external editor

### Expected result

- The editor loaded a file containing "This is an editable paragraph"

### Actual behaviour

- The editor loaded a file containing "undefined"

**Comment by fanglingsu** [comment]
I think we have to add a new JavaScript under _src/scripts_ (like the scroll.js) with some more logic for handling focus, blur and getting and setting of content depending on the element. At the moment it's ok to add some little JavaScript files helping us doing the dirty dom related stuff. In the long run, we should pack the little snippets together to larger JavaScript objects providing some utility methods.

**Comment by rti** [comment]
Yes. Good idea. It's a cleaner approach.

**Comment by fanglingsu** [comment]
Closed this because it's a duplicate to #248.
