### ISSUE TITLE
Webview Crashed (3.0-alpha)

### ISSUE THREAD

**Issue by dantleech** [fanglingsu/vimb#409]
Hi,

When visiting twitter.com I get the following error:

![123123](https://cloud.githubusercontent.com/assets/530801/26557541/2a048e62-449a-11e7-87f8-d8927a24688e.png)

Using acf2820a51802d0bf5c22933e2611398c5293160

**Comment by fanglingsu** [comment]
I can't reproduce this issue. Which version of webkit do use use?

**Comment by dantleech** [comment]
I seem to be using: `2.16.3-1`:

```
$ dpkg -l | grep webkit2gtk-4
ii  libwebkit2gtk-4.0-37:amd64                2.16.3-1                               amd64        Web content engine library for GTK+
ii  libwebkit2gtk-4.0-37-gtk2:amd64           2.16.3-1                               amd64        Web content engine library for GTK+ - GTK+2 plugin process
ii  libwebkit2gtk-4.0-dev:amd64               2.16.3-1                               amd64        Web content engine library for GTK+ - development files
```

**Comment by fanglingsu** [comment]
Can you please start vimb from cli and check if there are useful messages printed during the the crash?

**Comment by dantleech** [comment]
```
** (WebKitWebProcess:26693): WARNING **: Error sending focus message

(WebKitWebProcess:26693): GStreamer-CRITICAL **: 
Trying to dispose element appsrc1, but it is in READY instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(WebKitWebProcess:26693): GStreamer-CRITICAL **: 
Trying to dispose element webkitwebsrc0, but it is in PAUSED instead of the NULL state.
You need to explicitly set elements to the NULL state before
dropping the final reference, to allow them to clean up.
This problem may also be caused by a refcounting bug in the
application or some element.


(WebKitWebProcess:26693): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object->refcount > 0' failed
```

**Comment by fanglingsu** [comment]
I get something similar, but no crash.
```
** (WebKitWebProcess:19084): CRITICAL **: file gstaudioringbuffer.c: line 2044 (gst_audio_ring_buffer_set_channel_positions): should not be reached
```
Might be a GStreamers issue [144040](https://bugs.webkit.org/show_bug.cgi?id=144040).

**Comment by fanglingsu** [comment]
I fear we can't do anything in vimb to fix this.

**Comment by dantleech** [comment]
For the record I did not get this same issue on another laptop (so I guess different dep versions), but on that laptop I still get random webview crashes on a "complicated" JS page.

As you suggest, probably a webkit issue.

**Comment by fanglingsu** [comment]
@dantleech If it's related to JavaScript maybe setting env var `JavaScriptCoreUseJIT=0` would help here too or one of the other JavaScript related [environment variables](https://trac.webkit.org/wiki/EnvironmentVariables).
