### ISSUE TITLE
Compilation error on 3.0-alpha tag

### ISSUE THREAD

**Issue by mlopes** [fanglingsu/vimb#410]
Hi, 

I'm trying to compile vimb alpha 3.0, as per the instructions [here](https://fanglingsu.github.io/vimb/) but I get a compilation error:

```
cc -std=c99 -pipe -Wall -pthread -I/usr/include/webkitgtk-4.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/webkitgtk-4.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DVERSION=\"3.0-alpha\" -DEXTENSIONDIR=\"/usr/local/lib/vimb\" -DPROJECT=\"vimb\" -DPROJECT_UCFIRST=\"Vimb\" -D_XOPEN_SOURCE=500 -D__BSD_VISIBLE -DGSEAL_ENABLE -DGTK_DISABLE_SINGLE_INCLUDES -DGDK_DISABLE_DEPRECATED -c -o main.o main.c
main.c: In function ‘client_new’:
main.c:685:56: error: ‘WIN_WIDTH’ undeclared (first use in this function)
     gtk_window_set_default_size(GTK_WINDOW(c->window), WIN_WIDTH, WIN_HEIGHT);
                                                        ^~~~~~~~~
main.c:685:56: note: each undeclared identifier is reported only once for each function it appears in
main.c:685:67: error: ‘WIN_HEIGHT’ undeclared (first use in this function)
     gtk_window_set_default_size(GTK_WINDOW(c->window), WIN_WIDTH, WIN_HEIGHT);
                                                                   ^~~~~~~~~~
Makefile:34: recipe for target 'main.o' failed
```

cc's version is:

`cc (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005`

As seen above, I'm trying to compile on ubuntu.

I get the same error on `master` but it compiles without issues on the `webkit2` branch.

**Comment by mlopes** [comment]
hum... something must have been corrupted in my local repo, cloned it again and not it's fixed.

**Comment by fanglingsu** [comment]
The error is caused by an aoutdated _src/config.h_ file. The file is initially created by make fomr the _src/config.def.h_ and then never touched again. In case some new constants are added to the _src/config.def.h_ the copilation might fail because of missing constants in _src/config.h_. So on the next time you could check for differences beween the two files and update the config.h by hand to avoid cloning the whole sources again.

**Comment by mlopes** [comment]
I ran make clean, shouldn't that have done it?

**Comment by fanglingsu** [comment]
No! The config.h ist there for your personal configuration and should not be damaged by make clean.
