### ISSUE TITLE
No hints or hjkl scroll on FreeBSD

### ISSUE THREAD

**Issue by mike402** [fanglingsu/vimb#412]
Hints do not seem to come up on hitting "f", although the command line changes.
Scrolling with hjkl does not work, but works with arrows and mouse.

Is there a chance this has something to do with src/scripts/js2h.sh?

FreeBSD 11.0-RELEASE-p9
webkit2-gtk3-2.16.2

**Comment by iamleot** [comment]
Hello Michael,

Michael Danilov writes:
> Hints do not seem to come up on hitting "f", although the command line changes.
> Scrolling with hjkl does not work, but works with arrows and mouse.
> 
> Is there a chance this has something to do with src/scripts/js2h.sh?
> 
> FreeBSD 11.0-RELEASE-p9
> webkit2-gtk3-2.16.2

I can confirm the same on NetBSD with webkit-gtk in pkgsrc-wip
(latest webkit-gtk stable release and both with vimb3-git and
vimb-3.0alpha)... But unfortunately I didn't have any way to debug that.

If anyone has any idea how to debug that please let me know!

**Comment by rti** [comment]
I can reproduce such a behaviour if I prevent the webextension from loading on arch linux as well.

Due to the webkit2 process model, vimb now implements a shared library loaded by the webkit process, the webextension. The main process and the webextension communicate with each other in order to implement functionality such as hinting, hjkl scrolling and a lot more.

Unfortunately, there does not seem to be an error message at the moment, if the webextension is not loaded.

I just found a quick and dirty way that might shed some light onto that issue.

First, you need to apply the following patch on the ```3.0-alpha``` tag.

```
diff --git a/src/webextension/ext-main.c b/src/webextension/ext-main.c
index d70db00..e696ebd 100644
--- a/src/webextension/ext-main.c
+++ b/src/webextension/ext-main.c
@@ -123,6 +123,8 @@ void webkit_web_extension_initialize_with_user_data(WebKitWebExtension *extensio
             G_DBUS_CONNECTION_FLAGS_AUTHENTICATION_CLIENT, observer, NULL,
             (GAsyncReadyCallback)on_dbus_connection_created, extension);
     g_object_unref(observer);
+
+    g_warning(__func__);
 }
 
 static gboolean on_authorize_authenticated_peer(GDBusAuthObserver *observer,
```

Run ```make clean```.

Run ```make sandbox```.

Run ```sandbox/usr/bin/vimb```.

On my machine I now get a message like ```** (WebKitWebProcess:12035): WARNING **: webkit_web_extension_initialize_with_user_data``` and everything works fine.

When I now run ```rm sandbox/usr/lib/vimb/webext_main.so``` and do ```sandbox/usr/bin/vimb``` again, the message does not appear anymore and also hints and hjkl scrolling is broken.

Failing to load the webextension could be related to path settings. The ```Makefile``` sets ```EXTENSIONDIR``` which is then used e.g. in ```main.c:977``` to ```    webkit_web_context_set_web_extensions_directory(webctx, EXTENSIONDIR);```. So as I understand the code, the installation path of the webextension is built into the vimb binary.

Thats all I know.

**Comment by fanglingsu** [comment]
@rti Thanks for answering. I don't know how you compiled vimb, but I assume that the `PREFIX` for the compilation is not given to the make step. If you use a own PREFIX, this must be given for `make` and `make install` too (we avoid using something bloated like configure here).

**Comment by mike402** [comment]
Ah yes! Everything works in the sandbox! Must have been a PEBKAC. :/

**Comment by rti** [comment]
@mike402 sounds like a possible source for the problem. As I understand it, the make settings should match the final installation path.

**Comment by fanglingsu** [comment]
I'm dissatisfied with the current way to build vimb, but I don't have a better alternative to this. We need to know the install path of the webextension already during compilation.

**Comment by mike402** [comment]
Yes, but the final location where it ends up is what is passed to the first "make", it is only the "make install" which is told to put files in a different place? I bet there is no way to roll it into a package without doing this?

**Comment by fanglingsu** [comment]
@mike402 I'm not sure what you mean. Can you please show, the two lines you use to build vimb or a link to a package or something to discuss about.

**Comment by mike402** [comment]
On Fri, Jun 02, 2017 at 03:34:12AM -0700, Daniel Carl wrote:
> @mike402 I'm not sure what you mean. Can you please show, the two lines you use
> to build vimb or a link to a package or something to discuss about.

Compilation:

+ /usr/bin/env 'XDG_DATA_HOME=/tmp/usr/ports/www/vimb/work' 'XDG_CONFIG_HOME=/tmp/usr/ports/www/vimb/work' 'HOME=/tmp/usr/ports/www/vimb/work' 'NO_PIE=yes' 'MK_DEBUG_FILES=no' 'MK_KERNEL_SYMBOLS=no' 'SHELL=/bin/sh' 'NO_LINT=YES' 'PREFIX=/usr/local' 'LOCALBASE=/usr/local' 'LIBDIR=/usr/lib' 'CC=cc' 'CFLAGS=-O2 -pipe  -fstack-protector -fno-strict-aliasing' 'CPP=cpp' 'CPPFLAGS=' 'LDFLAGS= -fstack-protector' 'LIBS=' 'CXX=c++' 'CXXFLAGS=-O2 -pipe -fstack-protector -fno-strict-aliasing ' 'MANPREFIX=/usr/local' 'PATH=/usr/local/libexec/ccache:/home/mike/bin:/home/pub/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/games:/home/pub/bin:/home/mpd/bin:/home/transmission/bin/' 'CCACHE_DIR=/root/.ccache' 'BSD_INSTALL_PROGRAM=install  -s -m 555' 'BSD_INSTALL_LIB=install  -s -m 0644' 'BSD_INSTALL_SCRIPT=install  -m 555' 'BSD_INSTALL_DATA=install  -m 0644' 'BSD_INSTALL_MAN=install  -m 444' gmake -f Makefile -j2 all

Staging:

install  -m 444 /tmp/usr/ports/www/vimb/work/vimb-3.0-alpha/doc/vimb.1 /tmp/usr/ports/www/vimb/work/stage/usr/local/man/man1/
install  -s -m 555 /tmp/usr/ports/www/vimb/work/vimb-3.0-alpha/src/vimb /tmp/usr/ports/www/vimb/work/stage/usr/local/bin

Then, the files are packaged, and when the package is installed they end up in the prefix set during compilation, that is |/usr/local".

**Comment by fanglingsu** [comment]
@mike402 Why don't you use `make install`? I think the webextension is missed in the install/staging step. It seems you copy the man page, but there are some data missing in the man page that are written there during `make install` (date and version).

**Comment by mike402** [comment]
On Fri, Jun 02, 2017 at 04:29:09AM -0700, Daniel Carl wrote:
> @mike402 Why don't you use make install? I think the webextension is missed in
> the install/staging step. It seems you copy the man page, but there are some
> data missing in the man page that are written there during make install (date
> and version).

My bad! I forgot to remove the surrogate install from the old version. "make install" does it right.

Thanks!

**Comment by rti** [comment]
@mike402 I never used FreeBSD and I have no idea how packages work there. But did your research and work lead to something we could share with other FreeBSD users in order to ease vimb installation on their machines?

**Comment by vlmarek** [comment]
I might have seen the same issue on OpenSuse Tumbleweed. I have pulled fresh git, made little change

diff --git a/config.mk b/config.mk
index 610512e..7b148b2 100644
--- a/config.mk
+++ b/config.mk
@@ -18,7 +18,7 @@ SRCDIR  = src
 DOCDIR  = doc
 
 # used libs
-LIBS = gtk+-3.0 'webkit2gtk-4.0 >= 2.3.5'
+LIBS = gtk+-3.0 'webkit2gtk-4.0 >= 2.3.5' glib-2.0
 
 # setup general used CFLAGS
 CFLAGS   += -std=c99 -pipe -Wall

and compiled via 'make clean runsandbox'

The browser appears. I can open a page via 'o', but pressing 'f' only sows ';o' and no hitns are shown.

**Comment by vlmarek** [comment]
Well, of course when I try to do it now, it works :-/ I don't think I have changed anything in the environment.

**Comment by rti** [comment]
@vlmarek Any chance you have experienced #422 ?

**Comment by mike402** [comment]
On Thu, Jun 15, 2017 at 03:37:26PM -0700, rti wrote:
> @mike402 I never used FreeBSD and I have no idea how packages work there. But
> did your research and work lead to something we could share with other FreeBSD
> users in order to ease vimb installation on their machines?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

Hi,

Nothing special is required, it was my mistake. The morale was that after simple
"make" one should run vimb from the install path.

I think I have finished the port for vimb 3.0, going to submit it to FBSD today
or after the weekend.

Kind regards,
Mike

**Comment by vlmarek** [comment]
@rti No, I haven't been building in parallel. If I'll see the issue again, I'll let myself be heard. Thank you.
