### ISSUE TITLE
Unable to use self signed certificates

### ISSUE THREAD

**Issue by mlopes** [fanglingsu/vimb#413]
Using vimb 3.0-alpha on ubuntu. I've added the certificate to `/usr/share/ca-certificates/extra`, ran `sudo dpkg-reconfigure ca-certificates` and checked the certificate in the list, and got confirmation it was added. But vimb says `Unacceptable TLS certificate`. Tried setting `ca-bundle` to point to a file with the certificates, as per an older ticket where someone asked about the same thing, but that setting seems to have been removed, and I get a `config ca-bundle not found` error.

**Comment by fanglingsu** [comment]
@mlopes I have to admit that I don't know where webkit2 reads the certificates from. As I can see there is no way to set a custom certificate bundle. But there is a function that allows to a single chertifacte that is allowed for a single given host but this is not added in vimb jet.

**Comment by mlopes** [comment]
Maybe it's worth to close this one then, I'm finding it very likely that this is some misconfiguration  on my part, as I've managed to make other self signed certificates to work.

Thanks.

**Comment by fanglingsu** [comment]
@mlopes On my system the system wide certificates are read by vimb in `/etc/ssl/certs/ca-certificates.crt` so I assume webkit2 does in general use the system certificates.
You can check which files are read with strace:
```
strace -e trace=open -f -o trace.log vimb https://badssl.com
```
