### ISSUE TITLE
undeclared enum values

### ISSUE THREAD

**Issue by josephtoles** [fanglingsu/vimb#415]
I'm not sure if I'm doing something wrong. I cloned the vimb repo, installed libwebkit2gtk-4.0-dev and attempted to `make` vimb. Then I got the following error.

```
make[1]: Entering directory `/home/joseph/temp/vimb/src'
cc main.o
main.c: In function ‘vimb_setup’:
main.c:1527:5: warning: implicit declaration of function ‘webkit_web_context_set_web_process_count_limit’ [-Wimplicit-function-declaration]
     webkit_web_context_set_web_process_count_limit(ctx, 1);
     ^
cc setting.o
setting.c: In function ‘hardware_acceleration_policy’:
setting.c:550:9: warning: implicit declaration of function ‘webkit_settings_set_hardware_acceleration_policy’ [-Wimplicit-function-declaration]
         webkit_settings_set_hardware_acceleration_policy(settings, WEBKIT_HARDWARE_ACCELERATION_POLICY_ON_DEMAND);
         ^
setting.c:550:68: error: ‘WEBKIT_HARDWARE_ACCELERATION_POLICY_ON_DEMAND’ undeclared (first use in this function)
         webkit_settings_set_hardware_acceleration_policy(settings, WEBKIT_HARDWARE_ACCELERATION_POLICY_ON_DEMAND);
                                                                    ^
setting.c:550:68: note: each undeclared identifier is reported only once for each function it appears in
setting.c:552:68: error: ‘WEBKIT_HARDWARE_ACCELERATION_POLICY_ALWAYS’ undeclared (first use in this function)
         webkit_settings_set_hardware_acceleration_policy(settings, WEBKIT_HARDWARE_ACCELERATION_POLICY_ALWAYS);
                                                                    ^
setting.c:554:68: error: ‘WEBKIT_HARDWARE_ACCELERATION_POLICY_NEVER’ undeclared (first use in this function)
         webkit_settings_set_hardware_acceleration_policy(settings, WEBKIT_HARDWARE_ACCELERATION_POLICY_NEVER);
                                                                    ^
make[1]: *** [setting.o] Error 1
make[1]: Leaving directory `/home/joseph/temp/vimb/src'
make: *** [src.subdir-all] Error 2
```

It seems like my src/settings.c file isn't properly importing the webkit header. I apologize if this isn't the right place to post such an issue. I don't know much about C programming and couldn't find an answer to this problem anywhere else.

**Comment by fanglingsu** [comment]
@josephtoles It looks like your webkit version is too old. `webkit_web_context_set_web_process_count_limit` was added with webkit 2.10 according to the documentation, so I assume your version is slightly lower. `WEBKIT_HARDWARE_ACCELERATION_POLICY_NEVER` was added with 2.16. If you tell me the webkit version I'll check, if we can lower the requirements by doing some version depending compilation.

**Comment by josephtoles** [comment]
@fanglingsu 

I appear to be using webkit version 2.8.5 if that's what the apt-get line `Preparing to unpack .../libwebkit2gtk-4.0-37-dbg_2.8.5+dfsg1-1~14.04~webkitteam1_amd64.deb ...` means.

Thanks. Lowering the webkit requirements would be really helpful. I've been trying for an hour to install a more updated version of webkit2gtk but have been having trouble figuring out how. If you can't lower the requirements I'll try harder to install the newer version.

**Comment by fanglingsu** [comment]
@josephtoles OK, I'll see if this is possible, but this will take some time to check through the code.

**Comment by fanglingsu** [comment]
@josephtoles I've surrounded the new parts by version checks. Can you pleas echek if this works for you?

**Comment by josephtoles** [comment]
Thank you for trying. Now it can't identify the enum GUI_STYLE_CSS_BASE.

```
make[1]: Entering directory `/home/joseph/src/vimb/src'
cc main.o
main.c: In function ‘vb_gui_style_update’:
main.c:1562:41: error: ‘GUI_STYLE_CSS_BASE’ undeclared (first use in this function)
     GString *style_sheet = g_string_new(GUI_STYLE_CSS_BASE);
                                         ^
main.c:1562:41: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [main.o] Error 1
make[1]: Leaving directory `/home/joseph/src/vimb/src'
make: *** [src.subdir-all] Error 2
```

I will figure out how to install the required webkit2k version on my machine. I hope you don't waste any more time on fixing this just for me. Thank you very much for trying to make it compatible with the old library but this is my job to fix. Vimb is my favorite open source software application. I use it many times every day and am very grateful that you wrote it.

**Comment by rti** [comment]
@josephtoles The most recent build error you reported is not webkit related anymore but due to an updated ```config.h```. You can either:
 - adjust your ```src/config.h``` manually
 - OR ```cp src/config.def.h src/config.h```
 - OR just restart with a fresh git clone of vimb

**Comment by josephtoles** [comment]
It works. Thank you so much!
