### ISSUE TITLE
Commit 773a71c makes partial redraw issues visible when running vimb -e in tabbed

### ISSUE THREAD

**Issue by Ferenc-** [fanglingsu/vimb#417]
Running 

`tabbed vimb -e`

when the tabbed window size is bigger than the default window dimensions specified compile time, causes partial redraw issues, for example the status bar etc is not refreshed.

When `773a71c` is reverted on the current master head, or a version previouos to `773a71c` the issue is not observable.

**Comment by fanglingsu** [comment]
@Ferenc- Thank you for pointing this out. The default size is not needed and obviously wrong in case vimb is embedded.

**Comment by fanglingsu** [comment]
Can you please check if the last change removed the issue for you too?

**Comment by Ferenc-** [comment]
@fanglingsu Yes. I tested it too and I can confirm, that it has been fixed by `0dde688`.
