### ISSUE TITLE
Race condition with parallel builds (make -j)

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#422]
### Problem
When using parallel builds (e.g. `make -j5 clean runsandbox`) the `install` step might run too early and therefore tries to install an incomplete build.

### Effect
The effects are manifold:
- The webextension is missing, leading to issue similar to #412
- The install step just breaks with an error like this:
```
$ make -j5 clean runsandbox
make[1]: Entering directory '/home/rti/projects/vimb'
make[1]: Entering directory '/home/rti/projects/vimb/src'
make[2]: Entering directory '/home/rti/projects/vimb/src'
make[2]: Entering directory '/home/rti/projects/vimb/src/webextension'
rm -f webext_main.so *.lo
make[2]: Leaving directory '/home/rti/projects/vimb/src/webextension'
make[3]: Entering directory '/home/rti/projects/vimb/src/webextension'
rm -f vimb *.o scripts/scripts.h
make[1]: Leaving directory '/home/rti/projects/vimb/src'
cc ext-util.lo
cc ext-main.lo
cc ext-dom.lo
cc webext_main.so
make[3]: Leaving directory '/home/rti/projects/vimb/src/webextension'
make[2]: Leaving directory '/home/rti/projects/vimb/src'
install -d ./sandbox/usr/bin
install -m 755 src/vimb ./sandbox/usr/bin/vimb
install: cannot stat 'src/vimb': No such file or directory
make[1]: *** [Makefile:16: install] Error 1
make[1]: Leaving directory '/home/rti/projects/vimb'
make: *** [Makefile:38: sandbox] Error 2
```

### Workaround
Always use single threaded builds for now `make -j1 clean runstandbox`

**Comment by fanglingsu** [comment]
Most packages are build as `make` followed by `make install` so this is not very critical. But I'm not experienced enough to fix this. I fear we have to change the make stuff completly new to check dependencies right.

**Comment by fanglingsu** [comment]
@rti I'm not sure if it's a issue of the Makefile in general. `make -j5 clean && make -j5 runsandbox` works for me, where `make -j5 clean runsandbox` does not. But the later one fails because the cleaning an the build will definitly run in parallel so that already built files might be remove by the running clean target. If you use that for testing, ou should add the `clean` as dependency to the `runsandbox` target - this should work in my opinion.

**Comment by fanglingsu** [comment]
@rti Does `make -j5 clean && make -j5 runsandbox` work for you to. In this case I'd close this issue, because it's abviously not a good idea to run clean tasks and build tasks in parallel.

**Comment by rti** [comment]
@fanglingsu Yes it does. Actually, it was meant as an exaggeration for an issue where running ```make runsandbox``` from a clean checkout sometimes failed to load the webextension properly. Anyway, I cannot reproduce it either at the moment.
