### ISSUE TITLE
JS is not working with 3.0-alpha or further

### ISSUE THREAD

**Issue by yblein** [fanglingsu/vimb#424]
I tried the alpha release of vimb 3 and JS is not working. As a consequence, neither is scrolling or hinting. (Tested against 3.0-alpha and master on a up-to-date Arch Linux)

I tracked down the issue to dbus server connection. The server is properly started in `ext_proxy_init` but the `on_new_connection` callback is never fired and `dbusproxy` is never set.

I don't know much about dbus and I'm sure how to solve this issue.

**Comment by fanglingsu** [comment]
@yblein Might be a compile issue. Can you check, if this dbus works in case you run vimb in sandbox.
```
make clean
make sandbox && sandbox/usr/bin/vimb
```
Might be possible that the webextension is not found in general.

**Comment by yblein** [comment]
Nice catch, everything is working with the sandbox mode. Thank you.
