### ISSUE TITLE
vb_echo texts are editable

### ISSUE THREAD

**Issue by rti** [fanglingsu/vimb#432]
When a message is echo'd via ```vb_echo```, it can be clicked and edited, as the gtk input box remains editable.

Vimb version:
```
$ git rev-parse --short HEAD
ec5c3d1
```

### Steps to reproduce
- open a webpage, e.g. ```:o https://github.com```
- type ```y``` to yank the url
- click the message "Yanked: https://github.com" at the bottom of the vimb window and type backspace

### Expected behaviour
- the message is not focussed
- no cursor appears
- typing backspace does not change the message

### Actual behaviour
- the message is focussed
- a cursor appears
- typing backspace deletes characters from the message

**Comment by fanglingsu** [comment]
@rti I'm not sure if it really needed to avoid editing in the mentioned case. And to disable the input box in this case would possibly be the only case when the inputbox is not editable - so I'm not sure if it's wort the effort.

**Comment by rti** [comment]
@fanglingsu Well, I do think it is confusing to be able to edit vimb's messages.

The patch is quite simple if I am not missing any corner cases...
```
diff --git a/src/main.c b/src/main.c
index c00e80a..1842034 100644
--- a/src/main.c
+++ b/src/main.c
@@ -205,6 +205,9 @@ void vb_echo(Client *c, MessageType type, gboolean hide, const char *error, ...)
 
     input_print(c, type, hide, buffer);
     g_free(buffer);
+
+    gtk_text_view_set_editable(GTK_TEXT_VIEW(c->input), FALSE);
+    gtk_text_view_set_cursor_visible(GTK_TEXT_VIEW(c->input), FALSE);
 }
 
 /**
@@ -222,6 +225,9 @@ void vb_echo_force(Client *c, MessageType type, gboolean hide, const char *error
 
     input_print(c, type, hide, buffer);
     g_free(buffer);
+
+    gtk_text_view_set_editable(GTK_TEXT_VIEW(c->input), FALSE);
+    gtk_text_view_set_cursor_visible(GTK_TEXT_VIEW(c->input), FALSE);
 }
 
 /**
@@ -281,6 +287,9 @@ void vb_enter_prompt(Client *c, char id, const char *prompt, gboolean print_prom
          * event listener could grep the new prompt */
         vb_echo_force(c, MSG_NORMAL, FALSE, c->state.prompt);
     }
+
+    gtk_text_view_set_editable(GTK_TEXT_VIEW(c->input), TRUE);
+    gtk_text_view_set_cursor_visible(GTK_TEXT_VIEW(c->input), TRUE);
 }
 
 /**
@@ -716,6 +725,8 @@ static void client_show(WebKitWebView *webview, Client *c)
     g_signal_connect(c->buffer, "changed", G_CALLBACK(on_textbuffer_changed), c);
     /* Make sure the user can see the typed text. */
     gtk_text_view_set_wrap_mode(GTK_TEXT_VIEW(c->input), GTK_WRAP_WORD_CHAR);
+    gtk_text_view_set_editable(GTK_TEXT_VIEW(c->input), FALSE);
+    gtk_text_view_set_cursor_visible(GTK_TEXT_VIEW(c->input), FALSE);
 
     /* pack the parts together */
     box = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
```

Would you accept a merge request?

**Comment by fanglingsu** [comment]
@rti OK, seems simple. Do a pull request so that we can check how it feels to disable the inputbox.
