### ISSUE TITLE
Invisibe HTML input elements

### ISSUE THREAD

**Issue by JacksonGariety** [fanglingsu/vimb#434]
Version: 3.0-alpha

### Steps to reproduce
1. Open vimb
2. navigate to https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_checked
### Expected behaviour
Checkboxes appear
### Actual behaviour
Checkboxes do not appear

This seems to be the case for all HTML input elements with a GTK chrome: radio buttons, <select>, etc. The elements are there, and you can click on them, but the chrome is invisible.

Not sure if this has to do with my GTK config, or if the feature is just missing from vimb alpha.

**Comment by fanglingsu** [comment]
@JacksonGariety I can see the checkboxes there. This is no issue of vimb - because vimb does not render the page. This is the job of webkit. So I assume that the issue is in webkit or possibly also a GTK configuration. Do you use use stylesheet in `$XDG_CONFIG_HOME/vimb/style.css` that the issue might be caused by this.

**Comment by JacksonGariety** [comment]
@fanglingsu looks like the invisible elements was my GTK theme. It was set to Raleigh. I changed it to Adwaita (the default) and the checkboxes came back.

Separate issue: there is no text highlight color when I select text. There are also large transparent shapes in `<textarea>` elements. Image is attached.
![2017-07-31-221559_1240x505_scrot](https://user-images.githubusercontent.com/1356828/28810230-860a1a40-763d-11e7-86fa-937791f35683.png)

**Comment by fanglingsu** [comment]
@JacksonGariety Thank you for investigating into the issue. Never thought that the gtk theme has any effect to the webkit rendering itself.
