### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by beli3ver** [fanglingsu/vimb#435]
Hello,

is there a way, to handle Downloads via wget?
Like

    xterm -e "wget %s" 

or somethink like that by default?

How can I see my bookmarks?
Can I export my bookmarks?

**Comment by fanglingsu** [comment]
@beli3ver At the time there is no support in vimb for external download tools. We had this in the webkit1 version of vimb, but it's not ported to webkit2.
You can see the bookmarks in `$XDG_CONFIG_HOME/vimb/bookmark` file. The format `URL<tab>title<tab>space separated tags`. There is no export of te bookmarks in vimb. But I assume it would be easy to export them in some other format with some shell tools.

**Comment by Docbroke** [comment]
It is possible to create external handler script using something like this, with external-handler script in $PATH and below line in the .config/vimb/config
```
nmap x :sh lariza-external-handler -u "$VIMB_URI"<CR>

nmap X ;x 
set x-hint-command=:sh lariza-external-handler -u <C-R>;<CR>
```

**Comment by fanglingsu** [comment]
@beli3ver You can see your bookmarks in the `.config/vimb/bookmark` file. The format is `url<TAB>title<TAB>space separated tags`.

**Comment by fanglingsu** [comment]
Closed because questions where answered.
