### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by beli3ver** [fanglingsu/vimb#436]
### Steps to reproduce
Go to youtube click on a video.

### Expected behaviour
To hear sound.

### Actual behaviour
No sound playing no errors.
```
malte@DebLep:~$ vimb --bug-info
Commit:          3.0-alpha-56-gbcccce8
WebKit compile:  2.16.3
WebKit run:      2.16.6
GTK compile:     3.22.11
GTK run:         3.22.17
libsoup compile: 2.56.0
libsoup run:     2.56.0
Extension dir:   /usr/local/lib/vimb
```

**Comment by fanglingsu** [comment]
@beli3ver I assume your are missing some library or configuration to hear the sound. Does your sound work else? Do you have the gstreamer libraries installed? On my system I have following - not sure if all of them are needed.
```
gst-libav 1.12.2-1
gst-plugins-bad 1.12.2-1
gst-plugins-base 1.12.2-1
gst-plugins-base-libs 1.12.2-1
gst-plugins-good 1.12.2-1
gst-plugins-ugly 1.12.2-1
gstreamer 1.12.2-1
```

**Comment by beli3ver** [comment]
Ok fixed by installing:

```bash
#Debian SID
apt install gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly
```

Thanks.
