### ISSUE TITLE
[sway, wayland] vimb ignores keyboard layout.

### ISSUE THREAD

**Issue by kindaro** [fanglingsu/vimb#437]
```
% vimb --version
vimb, version 3.0-alpha

...
```

```
% sway --version
sway version 0.14.0
```
### Steps to reproduce
```
setxkbmap -layout ru
```

### Expected behaviour
I'd like to see cyrillic letters appear in an input field, for example, when I press letter keys on my keyboard, as it happen to be in *urxvt*, *firefox* and any other program that I use from day to day.
### Actual behaviour
I see latin letters instead.

**Comment by fanglingsu** [comment]
@kindaro Thank you for the report. I'll try to reproduce this. But as I can say, there is no logic in vimb to handle input methods or keyboard layouts, so I assume the issue might be somewhere in gtk or in the way we use this.

**Comment by fanglingsu** [comment]
@kindaro Sorry for the late answer. I can use setxkbmap to use cyrillic letters in vimb inputbox. But I use X11 and no compositor. But as I understand https://github.com/SirCmpwn/sway/wiki#keyboard-layout right, the setxkbmap works only together with X11, if you use wayland you have to setup the keyboard layout like described or with some other tool.
