### ISSUE TITLE
Motion commands are ignored

### ISSUE THREAD

**Issue by iamleot** [fanglingsu/vimb#438]
````
% /usr/pkg/bin/vimb3 --bug-info                                                                                                       ~
Commit:          3.0-alpha-56-gbcccce8
WebKit compile:  2.16.6
WebKit run:      2.16.6
GTK compile:     3.22.19
GTK run:         3.22.19
libsoup compile: 2.58.2
libsoup run:     2.58.2
Extension dir:   /usr/pkg/lib/vimb
````

Motion commands (as documented in vimb(1) man page) are ignored.

### Steps to reproduce
Install vimb3-git available on pkgsrc-wip in `pkgsrc/wip/vimb3-git`, install it via `make install'
and then execute it via:

````
% vimb3 -p empty
````
(the `-p empty' profile is used just to avoid possible honoring of - already present - vimb2 config files)

And then try type `j`, `k`, `gg`, `G`, `CTRL-D`, `CTRL-U`, `CTRL-F` or `CTRL-B` to scroll a web page.

### Expected behaviour
As documented in `vimb3(1)` man page I expect them to scroll the current web page.

At least for `gg` I can see that on the status bar a `g` is printed on the bottom right, and after the
second `g` it's cleaned (exactly as vimb 2.12).

### Actual behaviour
For neither of the above listed scrolling commands no action is performed, i.e. all the key
combination seems ignored.

Please note that pressing `Space` or `Shift-Space` works.

Apart that other commands like `gu`, `r`, `o`, etc. correctly works.

Sorry for the incompleteness of this bug report but unfortunately I do not have any idea
on how to debug it. Of course, any tips about that are welcomed (I can rebuild it via debug
symbols and inject breakpoints via gdb).

It's also worth to mention that this happen on NetBSD/amd64 8.99.1 with pkgsrc-current
(I do not have access to any other operating systems so no idea if this can be related to
NetBSD or pkgsrc).

**Comment by fanglingsu** [comment]
@iamleot The bug report is not incomplete. This sounds like the webextension is not found or present. The webextension is expected to be a shared object file at _/usr/pkg/lib/vimb/webext_main.so_ for your Installation. Can you check if this file exists?

**Comment by iamleot** [comment]
Hello Daniel,

Daniel Carl writes:
> @iamleot The bug report is not incomplete. This sounds like the webextension is not found or present. The webextension is expected to be a shared object file at _/usr/pkg/lib/vimb/webext_main.so_ for your Installation. Can you check if this file exists?

It seems that is correctly loaded (thanks to an issue discussion that we
had some months ago I've learned about `RUNPREFIX`):

````
% ktruss -id /usr/pkg/bin/vimb3 -p empty | grep webext_main
[...]
  2072      1 WebKitWebProcess access("/usr/pkg/lib/vimb/webext_main.so", 0) = 0
  2072      1 WebKitWebProcess __stat50("/usr/pkg/lib/vimb/webext_main.so", 0x7f7fff222320) = 0
  2072      1 WebKitWebProcess open("/usr/pkg/lib/vimb/webext_main.so", 0, 0x76) = 12
[...]
````

(if there are some particular non-motion related functionality that I
can exercise regarding webext_main please let me know so we can hopefully
triage it!)


Thank you!

**Comment by fanglingsu** [comment]
@iamleot OK, all the `:eval` stuff is done via webextension too. So you could check if `:e document.location.href` writes the current URL into the inputbox. Another Test would be the hinting. If you ope a page with links and press `f`, you should see some yellow hinted links.

**Comment by iamleot** [comment]
Daniel Carl writes:
> @iamleot OK, all the `:eval` stuff is done via webextension too. So you could check if `:e document.location.href` writes the current URL into the inputbox. Another Test would be the hinting. If you ope a page with links and press `f`, you should see some yellow hinted links.

Thanks!

I can confirm that also `:eval document.location.href` and hinting does
not work.

At the same time, after thinking about that, I'm a bit worried if
this is specific to pkgsrc and in that case I will probably need
to blame myself!
An important change that is disabled in webkit-gtk in pkgsrc
is INDEXED_DATABASE support (this was done to avoid picking a gcc>=4.9
dependency for netbsd-7 releases). I've grep-ed through webkit-gtk
source code and there are several ifdefs about that in a lot of
parts of the code.
I wouldn't be surprised that it can eventually impact to the
webextension that doesn't work.

So, for the moment (and next hours), still unsure if it's a vimb
bug (probably not) or a webkit-gtk and pkgsrc bug (probably yes!).
I will look at it in the next hours (not earlier than 19:00 UTC,
unfortunately), rebuild webkit-gtk with IndexedDB support and then
rebuild and retry vimb (it should need 1 hour and some odd minutes
on my home machine).

I'll then keep you updated if it was it or not! (apart that we do not
have any particular patches that can impacts webkit-gtk
functionalities AFAIK).


Thank you very much again Daniel!
Hope to bring you good news!

**Comment by gr3ggsparr0w** [comment]
was experiencing almost same behavior ( no motion on "j","k" and mousewheel scroll ) vimb-2.11 both gtk2 and gtk3 versions on FreeBSD when disabling scrollbars by 
style.css:
```
html {
overflow: hidden;
}
```
can`t test 3.0alpha right now, it seems ignoring my style.css when built and installed from source

**Comment by josephtoles** [comment]
This might be an issue with library dependencies. Do you have any warnings when you `Make` vimb? I did when I suffered a similar problem #454. I fixed that one by replacing Linux Mint with Arch Linux.

**Comment by fanglingsu** [comment]
@josephtoles I think there are other ways to fix this instead of changing the distribution.

**Comment by glsubri** [comment]
I also have the same problem as @iamleot.
<pre>
vimb --bug-info
Commit:          3.1.0
WebKit compile:  2.18.3
WebKit run:      2.18.3
GTK compile:     3.22.19
GTK run:         3.22.19
libsoup compile: 2.56.1
libsoup run:     2.56.1
Extension dir:   /usr/local/lib64/vimb
</pre>
**/usr/lib64/vimb/webext_main.so** exists
**2>&1 strace vimb | grep webext_main.so** gives nothing
So it looks like webext_main.so is at the right place, but not loaded correctly. 
Does anyone have an idea?

**Comment by fanglingsu** [comment]
@glsubri The strace is wrong, I think you have to give the `-f` option to follow also sub processes to grep the extension.

    2>&1 strace -f vimb | grep webext_main.so

**Comment by glsubri** [comment]
Thanks, I didn't think about that.
The results don't change. It still gives nothing.

**Comment by kazufukurou** [comment]
Same issue
```
$ vimb --bug-info
Commit:          unknown
WebKit compile:  2.18.4
WebKit run:      2.18.4
GTK compile:     3.22.26
GTK run:         3.22.26
libsoup compile: 2.60.2
libsoup run:     2.60.2
Extension dir:   /usr/local/lib/vimb
```
`2>&1 strace -f vimb | grep webext_main.so` gives nothing.

**Comment by fanglingsu** [comment]
@glsubri @kazufukurou I don't have any idea why the webextension is not loaded by webkit. Have you tried to download the sources and to run `make runsandbox`. This should compile vimb with into sandbox directory and run it withthe right extension directory. If this works, the issue might be in the way vimb was compiled or in the directory the webextension is installed to.

**Comment by kazufukurou** [comment]
With `make runsandbox` motion commands works.

**Comment by fanglingsu** [comment]
@kazufukurou How did you compile vimb. Note that you need to give the `PREFIX` for the make and for the `make install`.

**Comment by kazufukurou** [comment]
@fanglingsu I'm using package from Void Linux repository. [Here](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/vimb/template) is how they build it. Maybe the issue is on their side then.

**Comment by glsubri** [comment]
Just noticed the same thing as @kazufukurou: `Extension dir: /usr/local/lib/vimb` but `webext_main.so` is in `/usr/lib/vimb`. I am using gentoo, I will check the ebuild and get back to you.

Thanks @kazufukurou for pointing that out!

**Comment by fanglingsu** [comment]
@kazufukurou I don't knwo how the void linux stuff builds the packages. I can't see any useful things from the template, this are only some metadata. I assume that it's required to provide some confiugre script that set the path for the extension dir instead of assuming `PREFIX` to be set on compile as well as to the install stage.

**Comment by kazufukurou** [comment]
@fanglingsu yes, prefix was not set on build stage. I sent PR to fix that.

**Comment by GKFX** [comment]
On Debian Buster, I got these same symptoms when compiling (from the repository as of today) and running with `make runsandbox`, but not when installing with `sudo make install`.
I feel like a good partial solution would be for Vimb to complain loudly to the user if the webextension isn't loaded at startup. At least that means that the user can fix it more rapidly.

**Comment by fanglingsu** [comment]
@GKFX I thought about something like this, but there is no nice way to check if the webextension was not loaded. It might be possible to check if the extension files is located in the expected directory and is readable.

**Comment by fanglingsu** [comment]
@iamleot Did you find the reason, why the webextension was not loaded?

**Comment by iamleot** [comment]
Hello Daniel,

Daniel Carl writes:
> @iamleot Did you find the reason, why the webextension was not loaded?

Unfortunately no, sorry. :(

**Comment by fanglingsu** [comment]
@iamleot I think you could debug the webextension by breaing at `webkit_web_extension_initialize_with_user_data`. But this does not work on my system.
```
$ gdb src/vimb
symbol-file src/webextension/webext_main.so
b webkit_web_extension_initialize_with_user_data
r
Starting program: /home/daniel/code/c/vimb/src/vimb
...
[Detaching after fork from child process 8764]
[Detaching after fork from child process 8766]
...
/home/daniel/code/c/vimb/src/vimb: symbol lookup error: /home/daniel/code/c/vimb/src/vimb: undefined symbol: webkit_web_view_can_go_forward
[LWP 8773 exited]
...
[Inferior 1 (process 8756) exited with code 0177]
```
Not sure if this is the wrong approach or this is an gbd issue on my system.

**Comment by iamleot** [comment]
Hello Daniel,

Daniel Carl writes:
> @iamleot I think you could debug the webextension by breaing at `webkit_web_extension_initialize_with_user_data`. But this does not work on my system.
> ```
> $ gdb src/vimb
> symbol-file src/webextension/webext_main.so
> b webkit_web_extension_initialize_with_user_data
> r
> Starting program: /home/daniel/code/c/vimb/src/vimb
> ...
> [Detaching after fork from child process 8764]
> [Detaching after fork from child process 8766]
> ...
> /home/daniel/code/c/vimb/src/vimb: symbol lookup error: /home/daniel/code/c/vimb/src/vimb: undefined symbol: webkit_web_view_can_go_forward
> [LWP 8773 exited]
> ...
> [Inferior 1 (process 8756) exited with code 0177]
> ```
> Not sure if this is the wrong approach or this is an gbd issue on my system.
>

Unfortunately putting a breakpoint on
`webkit_web_extension_initialize_with_user_data' does not seem to do the
trick here too... However, after grepping for the error:

  [...]
   158  static void on_dbus_connection_created(GObject *source_object,
   159          GAsyncResult *result, gpointer data)
   160  {
   161      static GDBusNodeInfo *node_info = NULL;
   162      GDBusConnection *connection;
   163      GError *error = NULL;
   164
   165      if (!node_info) {
   166          node_info = g_dbus_node_info_new_for_xml(introspection_xml, NULL);
   167      }
   168
   169      connection = g_dbus_connection_new_for_address_finish(result, &error);
   170      if (error) {
   171          g_warning("Failed to connect to UI process: %s", error->message);
   172          g_error_free(error);
   173          return;
   174      }
  [...]

So, it seems that what fails here is
`g_dbus_connection_new_for_address_finish()'.

(At least this will hopefully restrict possible further investigation.)

I'll append any possible further information if I'll be able to
figure out what's going on... ...of course, if anyone has any idea,
would like to suggest possible strategic printf() or anything else
do not hesitate to contact me!


Thanks again!

**Comment by fanglingsu** [comment]
@iamleot I don't know much about dbus. But you could try to play a little with the dbus-lunch. I'm not sure but `dbus-lunch vimb` should work too. Or replace `--exit-with-session` by `--exit-with-x11`.

**Comment by iamleot** [comment]
JFTR I have tried that but doesn't make any differences.

**Comment by fanglingsu** [comment]
@iamleot I could provoke the error "Failed to connect to UI process: Unexpected lack of content trying to read a line" by returning `FALSE` in `src/ex-proxy.c` (`on_authorize_authenticated_peer`). So I think the issue is dbus authentication related.

**Comment by iamleot** [comment]
Hello Daniel,

Daniel Carl writes:
> @iamleot I could provoke the error "Failed to connect to UI process: Unexpected lack of content trying to read a line" by returning `FALSE` in `src/ex-proxy.c` (`on_authorize_authenticated_peer`). So I think the issue is dbus authentication related.

JFTR, I have retried it with commit id
4f3af00ca1a0b4450f8b05bdb181d9cf531096de
(`vimb --bug-info' `Commit: 3.2.0-36-g4f3af00') and unfortunately
I have the same message on the stderr and motion commands are ignored.


Thank you for looking at it again!

**Comment by fanglingsu** [comment]
@iamleot I did not expect the changes to really fix the issue. But I hopes they would do it anyway. But I'm not sure if it helps, the issue seesm to be related to the dbus authtentication.
could you put a `return TRUE;` in first line of the function https://github.com/fanglingsu/vimb/blob/99461597d932c6ace71d82e44d6df7ff670375cd/src/webextension/ext-main.c#L136-L139
But I fear that this would also not help, because there is already output that would be generated in case the connection can't be authenticated.

**Comment by iamleot** [comment]
Hello Daniel,

Daniel Carl writes:
> @iamleot I did not expect the changes to really fix the issue. But I hopes they would do it anyway. But I'm not sure if it helps, the issue seesm to be related to the dbus authtentication.
> could you put a `return TRUE;` in first line of the function https://github.com/fanglingsu/vimb/blob/99461597d932c6ace71d82e44d6df7ff670375cd/src/webextension/ext-main.c#L136-L139
> But I fear that this would also not help, because there is already output that would be generated in case the connection can't be authenticated.

Yes, same symptoms and behaviours unfortunately.


Thank you and thanks for the suggestion about possible directions to
debug further!

**Comment by fanglingsu** [comment]
@iamleot Oh, there are two function doing the user check at the time. One in the webextension and one for the UI process `src/ext-proxy.c` `on_authorize_authenticated_peer()`. Could you return there TRUE too?

**Comment by iamleot** [comment]
Hello Daniel!

Daniel Carl writes:
> @iamleot Oh, there are two function doing the user check at the time. One in the webextension and one for the UI process `src/ext-proxy.c` `on_authorize_authenticated_peer()`. Could you return there TRUE too?

Wow! After both changes... I do no longer have the error and now
motion commands can be used!


Thank you very very much!

**Comment by fanglingsu** [comment]
Nice! That a first step to get into the issue. We need to understand why there are no credentials given.

**Comment by iamleot** [comment]
Hello Daniel,

Daniel Carl writes:
> Nice! That a first step to get into the issue. We need to understand why there are no credentials given.

Still no idea why there are no credentials given but I have tried
to grep for `on_authorize_authenticated_peer' in the glib2 code.

The documentation contains code similar to the one used by vimb:

 <https://github.com/GNOME/glib/blob/3bf4a720c315b5015c8d51edf0b458348f796674/gio/gdbusauthobserver.c#L57>

However, `gdbusdaemon.c' initializes the `authorized' variable to `TRUE':

 <https://github.com/GNOME/glib/blob/4ade09416b5e7b6d99883c4dd3b886605fdf043a/gio/gdbusdaemon.c#L1537>

(And, of course, similar to the patch you've proposed initializing
`authorized' to `TRUE' works here).

I have tried to use Debian Code Search:

 <https://codesearch.debian.net/>

...but after a quick skim of the search results I was only able to find
similar definitions.

Apart that I was also able to break into
`on_authorize_authenticated_peer()' of `src/ext-proxy.c' and I have
observed that both `credentials' and `data' are `0x0' (I guess
NULL).

**Comment by fanglingsu** [comment]
@iamleot The initialization to `TRUE` in gdbusdaemon seems to be intended to allow also connections that do not provide authentication information. But we want a authenticated private dbus connection, so I think it's right to ignore the connection if there are no credentials given. I think our approach is right, and the issue is caused by the way `dbus-launch` acts on your system.

**Comment by iamleot** [comment]
Daniel Carl writes:
> @iamleot The initialization to `TRUE` in gdbusdaemon seems to be intended to allow also connections that do not provide authentication information. But we want a authenticated private dbus connection, so I think it's right to ignore the connection if there are no credentials given. I think our approach is right, and the issue is caused by the way `dbus-launch` acts on your system.

OK, some more details that are probably important after trying to debug
this problem:

 - On pkgsrc I have disabled dbus via `-dbus' option and gtk3 libraries
   are compiled via `-gtk3-atk-bridge' that (indirectly) needed dbus
   (this passes `--without-atk-bridge').  At least when I first reported
   this issue I had recompiled all relevant packages with `dbus' option
   enabled in order to double-check if that impacted vimb behaviour (I
   had the same problem).
 - `dbus-launch' actually doesn't seem even needed when running vimb!
   Indeed dbus can be completely uninstalled and `vimb' works fine
   also without it.  (Please note though that during the last tests I
   had a `dbus-lanch' session active.)

**Comment by iamleot** [comment]
...and after searching more in the gio gtk-doc I have found
`G_DBUS_DEBUG' variable and this is what I see:

 | % env G_DBUS_DEBUG=all /usr/pkg/bin/vimb3
 | GDBus-debug:Auth: CLIENT: initiating
 | GDBus-debug:Auth: SERVER: initiating
 | GDBus-debug:Auth: CLIENT: sent credentials 'GCredentials:netbsd-unpcbid:pid=12917,uid=1000,gid=100'
 | GDBus-debug:Auth: CLIENT: writing 'AUTH\r\n'
 | GDBus-debug:Auth: CLIENT: WaitingForReject
 | GDBus-debug:Auth: SERVER: didn't receive any credentials
 | GDBus-debug:Auth: SERVER: WaitingForAuth
 | GDBus-debug:Auth: SERVER: WaitingForAuth, read 'AUTH'
 | GDBus-debug:Auth: SERVER: writing 'REJECTED EXTERNAL DBUS_COOKIE_SHA1\r\n'
 | GDBus-debug:Auth: SERVER: WaitingForAuth
 | GDBus-debug:Auth: CLIENT: WaitingForReject, read 'REJECTED EXTERNAL DBUS_COOKIE_SHA1'
 | GDBus-debug:Auth: CLIENT: Trying to choose mechanism
 | GDBus-debug:Auth: CLIENT: Trying mechanism 'EXTERNAL'
 | GDBus-debug:Auth: CLIENT: writing 'AUTH EXTERNAL 31303030\r\n'
 | GDBus-debug:Auth: CLIENT: WaitingForOK
 | GDBus-debug:Auth: SERVER: WaitingForAuth, read 'AUTH EXTERNAL 31303030'
 | GDBus-debug:Auth: SERVER: writing 'REJECTED EXTERNAL DBUS_COOKIE_SHA1\r\n'
 | GDBus-debug:Auth: SERVER: WaitingForAuth
 | GDBus-debug:Auth: CLIENT: WaitingForOK, read 'REJECTED EXTERNAL DBUS_COOKIE_SHA1'
 | GDBus-debug:Auth: CLIENT: Trying to choose mechanism
 | GDBus-debug:Auth: CLIENT: Trying mechanism 'DBUS_COOKIE_SHA1'
 | GDBus-debug:Auth: CLIENT: writing 'AUTH DBUS_COOKIE_SHA1 31303030\r\n'
 | GDBus-debug:Auth: CLIENT: WaitingForData
 | GDBus-debug:Auth: SERVER: WaitingForAuth, read 'AUTH DBUS_COOKIE_SHA1 31303030'
 | GDBus-debug:Auth: SERVER: writing 'DATA 6f72675f67746b5f67646275735f67656e6572616c2031204d4c46694c316c527855517969324e45\r\n'
 | GDBus-debug:Auth: SERVER: WaitingForData
 | GDBus-debug:Auth: CLIENT: WaitingForData, read='DATA 6f72675f67746b5f67646275735f67656e6572616c2031204d4c46694c316c527855517969324e45'
 | GDBus-debug:Auth: CLIENT: writing 'DATA 65737738496c756332336278564b6f382032323736636362303736356365306639336665616262303132356330316233363338326239366363\r\n'
 | GDBus-debug:Auth: CLIENT: WaitingForOK
 | GDBus-debug:Auth: SERVER: WaitingForData, read 'DATA 65737738496c756332336278564b6f382032323736636362303736356365306639336665616262303132356330316233363338326239366363'
 | 
 | ** (vimb3:21810): WARNING **: 00:09:25.696: No credentials received from web extension.
 | 

The first lines seems to look a bit strange! (client send credentials...
...but server didn't receive any credentials?)

(I hope to report back soon some progress!)

**Comment by fanglingsu** [comment]
@iamleot This is strange. On my system the first lines look like this.
```
GDBus-debug:Auth: CLIENT: initiating
GDBus-debug:Auth: CLIENT: sent credentials 'GCredentials:linux-ucred:pid=16003,uid=1000,gid=100'
GDBus-debug:Auth: SERVER: initiating
GDBus-debug:Auth: CLIENT: writing 'AUTH\r\n'
GDBus-debug:Auth: CLIENT: WaitingForReject
GDBus-debug:Auth: SERVER: received credentials 'GCredentials:linux-ucred:pid=16003,uid=1000,gid=100'
GDBus-debug:Auth: SERVER: WaitingForAuth
GDBus-debug:Auth: SERVER: WaitingForAuth, read 'AUTH'
GDBus-debug:Auth: SERVER: writing 'REJECTED EXTERNAL DBUS_COOKIE_SHA1\r\n'
GDBus-debug:Auth: SERVER: WaitingForAuth
GDBus-debug:Auth: CLIENT: WaitingForReject, read 'REJECTED EXTERNAL DBUS_COOKIE_SHA1'
GDBus-debug:Auth: CLIENT: Trying to choose mechanism
GDBus-debug:Auth: CLIENT: Trying mechanism 'EXTERNAL'
GDBus-debug:Auth: CLIENT: writing 'AUTH EXTERNAL 31303030\r\n'
GDBus-debug:Auth: CLIENT: WaitingForOK
GDBus-debug:Auth: SERVER: WaitingForAuth, read 'AUTH EXTERNAL 31303030'
GDBus-debug:Auth: SERVER: writing 'OK 95baf94bbd3fd9d9ab1f31e15bbfd246\r\n'
GDBus-debug:Auth: SERVER: WaitingForBegin
GDBus-debug:Auth: CLIENT: WaitingForOK, read 'OK 95baf94bbd3fd9d9ab1f31e15bbfd246'
GDBus-debug:Auth: CLIENT: writing 'NEGOTIATE_UNIX_FD\r\n'
GDBus-debug:Auth: CLIENT: WaitingForAgreeUnixFD
GDBus-debug:Auth: CLIENT: initiating
GDBus-debug:Auth: CLIENT: sent credentials 'GCredentials:linux-ucred:pid=16003,uid=1000,gid=100'
GDBus-debug:Auth: CLIENT: writing 'AUTH\r\n'
GDBus-debug:Auth: CLIENT: WaitingForReject
GDBus-debug:Auth: SERVER: WaitingForBegin, read 'NEGOTIATE_UNIX_FD'
GDBus-debug:Auth: SERVER: writing 'AGREE_UNIX_FD\r\n'
GDBus-debug:Auth: SERVER: WaitingForBegin
GDBus-debug:Auth: CLIENT: WaitingForAgreeUnixFD, read='AGREE_UNIX_FD'
GDBus-debug:Auth: CLIENT: writing 'BEGIN\r\n'
GDBus-debug:Auth: CLIENT: WaitingForReject, read 'REJECTED EXTERNAL'
GDBus-debug:Auth: CLIENT: Trying to choose mechanism
GDBus-debug:Auth: CLIENT: Done, authenticated=1
```

**Comment by fanglingsu** [comment]
@iamleot Pretty nice. You made it! After over one year of investigation. I'm glad that you could fix this strange DBus issue not only for you but also for other NetBSD users too.
