### ISSUE TITLE
Hint mode is unresponsive

### ISSUE THREAD

**Issue by Scottyenvivo** [fanglingsu/vimb#445]
### Steps to reproduce
Installed dependancy: webkit2gtk-4.0  (2.8.5)
cloned and compiled vimb  

### Expected behaviour
Works ok but i guess hint mode should show id tags of some sort when i press ";o"

### Actual behaviour
hint mode doesnt seem to affect anything but the rest of vimb seems to work ok

I get this warning:
(vimb:10633): Gtk-WARNING **: Theme parsing error: <data>:1:62: 'caret-color' is not a valid property name

**Comment by fanglingsu** [comment]
Does vimb scroll down on pressing 'j' in normal mode? If this does not work, it seems to be an issue with the webextension or the dbus connection.

**Comment by Scottyenvivo** [comment]
No, it doesnt scroll using hjkl but the arrow keys work.

Is webextention the webkit2gtk?

**Comment by rti** [comment]
Hi there,

the web extension is a library loaded by vimb at runtime. Failing to load the web extension leads to symptoms such as those you describe. Eg no hints, no hjkl scroll, ...

The web extension is expected in a certain path. 

Running '''make runsandbox''' should set up the paths correctly and load the web extension. 

Did you give it a try?

Hope it helps.

**Comment by rti** [comment]
> (vimb:10633): Gtk-WARNING **: Theme parsing error: :1:62: 'caret-color' is not a valid property name

This is probably caused by a too old version of webkit2gtk. Though, this warning just indicates that some GUI styling will not work. So it's not critical. Not sure which other errors might arise from the older WebKit version. Maybe none :)

**Comment by Scottyenvivo** [comment]
I ran "make sandbox" and it mentions the webextention but doesnt affect the problem.

```
make[1]: Entering directory `/usr/local/vimb'
make[2]: Entering directory `/usr/local/vimb/src'
make[3]: Entering directory `/usr/local/vimb/src/webextension'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/usr/local/vimb/src/webextension'
make[2]: Leaving directory `/usr/local/vimb/src'
install -d ./sandbox/usr/bin
install -m 755 src/vimb ./sandbox/usr/bin/vimb
install -d ./sandbox/usr/lib/vimb
install -m 644 src/webextension/webext_main.so ./sandbox/usr/lib/vimb/webext_main.so
install -d ./sandbox/usr/share/man/man1
install -d ./sandbox/usr/share/applications
install -m 644 vimb.desktop ./sandbox/usr/share/applications/vimb.desktop
make[1]: Leaving directory `/usr/local/vimb'

```

**Comment by fanglingsu** [comment]
You don't need to sudo for `make runsandbox`. The runsandbox compiles vimb into a known directory _sandbox_ and start it.

Can you provide the output of `vimb --bug-info` and check if there is a file _webext_main.so_ in the directory mentioned at "Extension dir:".

**Comment by Scottyenvivo** [comment]
```
Commit:          3.0-alpha-60-gc346c0c
WebKit compile:  2.8.5
WebKit run:      2.8.5
GTK compile:     3.10.8
GTK run:         3.10.8
libsoup compile: 2.44.2
libsoup run:     2.44.2
Extension dir:   /usr/local/lib/vimb
```
webext_main.so is in the right spot

**Comment by fanglingsu** [comment]
Might it be that the hinting does not work on a specific page?

**Comment by Scottyenvivo** [comment]
I did try google search result page, duck search result page and a wikipedia page.

**Comment by fanglingsu** [comment]
The tags should appear righ after you type the "o" of ";o". Or you type only "f" which is something like an alias for ";o". But you said that the scrolling via "hjkl" does also not work so this is not a hinting only issue but a more general one. there is something wrong with the webextension like rti already mentioned.

Can you check if the webextension is loaded? You need to find out the PID of the WebKitWebPocess and then you could check the loaded shard object files via /proc file system.

    grep 'webext_main.so' /proc/$(pgrep -n 'WebKitWebProcess*')/maps

This checks only the last spawed WebKitWebPocess, so it might be better to have only one instance of vimb running.

**Comment by Scottyenvivo** [comment]
My os had suffered years of hacky learning so i wiped it.  Ill close this issue and follow your advice in setting it up the next time.  I'm sure the error was somewhere on my end.  Thanks for your help

**Comment by Vintodrimmer** [comment]
Hello there,

I've just installed the 3.1.0 version and experience the same behaviour. No hints, no INSERT mode (I can write in forms, but any button that is mapped to something is not printed, but is captured by the vimb itself, so I have to use PASSTHROUGH mode), no `hjkl` navigation and so on.

How did you finally solve it, @Scottyenvivo?

@fanglingsu I have launched vimb and your command returned nothing. How can I make sure that webextensions are launched by vimb?

```
$ grep 'webext_main.so' /proc/$(pgrep -n 'WebKitWebProcess*')/maps
$
```

**Comment by fanglingsu** [comment]
@Vintodrimmer if the `ln -s /usr/lib/vimb/ /usr/local/lib/vimb` solves teh issue means there is somethings work with the way vimb is compiled or installed. The extension should me installed into the right place where vimb will look for it `vimb --bug-info | grep ^Extension`.

**Comment by Vintodrimmer** [comment]
```
➤ vimb --bug-info | grep Extension
Extension dir:   /usr/local/lib/vimb
```
I installed it from the void repos. Here's the [templade](https://github.com/voidlinux/void-packages/blob/55dc9a6f8f213535b63063fac627cfc78ffea56e/srcpkgs/vimb/template), but it just runs `gnu-makefile` scripts and installs the package.
