### ISSUE TITLE
Hide HTTP basic auth credentials in url bar

### ISSUE THREAD

**Issue by rudism** [fanglingsu/vimb#452]
When HTTP basic auth credentials are supplied in a url (either typed in or saved in a bookmark), it would be nice if the credentials were not displayed in the url bar at the bottom.

For example, instead of displaying `https://username:password@domain.com/whatever` it would strip the sensitive information and just display `https://domain.com/whatever`.

**Comment by fanglingsu** [comment]
@rudism Thank you for this suggestion. I've never used credential crafted URL so I haven't noticed this securitiy risk.

**Comment by fanglingsu** [comment]
We forgot to close this issue.
