### ISSUE TITLE
Trouble installing vimb 3.0-alpha

### ISSUE THREAD

**Issue by josephtoles** [fanglingsu/vimb#454]
I'm having trouble getting vimb to 3.0-alpha to function completely. Some commands do not work after installation. I hope someone can tell me what I am doing wrong.

`$ vimb --bug-info`

```
Commit:          3.0-alpha-65-gee984e6
WebKit compile:  2.8.5
WebKit run:      2.8.5
GTK compile:     3.10.8
GTK run:         3.10.8
libsoup compile: 2.44.2
libsoup run:     2.44.2
Extension dir:   /usr/local/lib/vimb
```

## Steps to reproduce
Open a website and then attempt to use the "j" (down), "k" (up), or "f" (follow link) hotkey.

### Expected behavior
"j" scrolls the screen down. "k" scrolls the screen up. "f" pops up ";o" in the command line displays numbers next to each link. (Some other commands are broken too *but not all of them*.)

### Actual behavior
"j" does nothing. "k" does nothing. "f" **does** pop up `;o` in the command line but does not highlight any links. `;o` does not let me follow any links.

Interestingly, some commands work just fine. "o" pops up the ":open" dialog which works fine. The spacebar scrolls down on a website and shift + spacebar scrolls up. "y" copies the url of the current webpage to the system clipboard.

### Error messages

I get the following error messages when I `make` vimb (this does not prevent compilation)

```
cc ext-dom.lo
ext-dom.c: In function ‘ext_dom_focus_input’:
ext-dom.c:92:5: warning: implicit declaration of function ‘webkit_dom_document_get_elements_by_tag_name_as_html_collection’ [-Wimplicit-function-declaration]
     collection = webkit_dom_document_get_elements_by_tag_name_as_html_collection(doc, "html");
     ^
ext-dom.c:92:16: warning: assignment makes pointer from integer without a cast [enabled by default]
     collection = webkit_dom_document_get_elements_by_tag_name_as_html_collection(doc, "html");
                ^
ext-dom.c:137:16: warning: assignment makes pointer from integer without a cast [enabled by default]
     collection = webkit_dom_document_get_elements_by_tag_name_as_html_collection(doc, "iframe");
                ^
```

I also get the following error when I run vimb (this does not crash the program)

```
(vimb:32426): Gtk-WARNING **: Theme parsing error: <data>:1:62: 'caret-color' is not a valid property name

(vimb:32426): Gtk-WARNING **: Theme parsing error: <data>:1:62: 'caret-color' is not a valid property name

(vimb:32426): Gtk-WARNING **: Theme parsing error: <data>:1:62: 'caret-color' is not a valid property name

(vimb:32426): Gtk-WARNING **: Theme parsing error: <data>:1:62: 'caret-color' is not a valid property name

(vimb:32426): Gtk-WARNING **: Theme parsing error: <data>:1:62: 'caret-color' is not a valid property name

(vimb:32426): Gtk-WARNING **: Theme parsing error: <data>:1:62: 'caret-color' is not a valid property name

(vimb:32426): Gtk-WARNING **: Theme parsing error: <data>:1:62: 'caret-color' is not a valid property name

(vimb:32426): Gtk-WARNING **: Theme parsing error: <data>:1:62: 'caret-color' is not a valid property name

(vimb:32426): Gtk-WARNING **: Theme parsing error: <data>:1:62: 'caret-color' is not a valid property name
```

Sorry if I'm missing something obvious. I'm not an expert in C programming.

**Comment by iamleot** [comment]
Hi josephtoles,

josephtoles writes:
> I'm having trouble getting vimb to 3.0-alpha to function completely. Some commands do not work after installation. I hope someone can tell me what I am doing wrong.
> [...]

This sounds similar (probably the same!) to issue #438.

(and, sorry for not adding more information to #438, unfortunately I
hadn't made any progress on it)

**Comment by josephtoles** [comment]
@iamleot Thanks!. Yes, this looks like a duplicate. That's a good place to start. I'll take a look at the comments there and see if they help.

**Comment by fanglingsu** [comment]
I close this because this is duplicate to already mentioned #438.
