### ISSUE TITLE
cant' get proxy setting work

### ISSUE THREAD

**Issue by tyjak** [fanglingsu/vimb#459]
Commit:          3.0-alpha-72-g6bbfaed
WebKit compile:  2.18.3
WebKit run:      2.18.3
GTK compile:     3.22.26
GTK run:         3.22.26
libsoup compile: 2.60.2
libsoup run:     2.60.2
Extension dir:   /usr/lib/vimb

### Steps to reproduce
set proxy=true (in ~/.config/vimb/config)
http_proxy=127.0.0.1:8118 (in ~/.xinitrc)

### Expected behaviour
access to privoxy settings and use the proxy to navigate

### Actual behaviour
can't get privoxy settings, no web navigation thru proxy

status line error : "Config 'proxy' not found" but in https://fanglingsu.github.io/vimb/man.html in the bottom of the page : 

> http_proxy
> If this variable is set to an none empty value, **and the configuration option ‘proxy’ is enabled**, this will be used as http proxy. If the proxy URL has no scheme set, http is assumed.

**Comment by fanglingsu** [comment]
@tyjak Oh, sorry. Seems some left over documentation from previous vimb versions. There is no configuration option to toggle proxy usage from the side of vimb. Webkit2 does not provide any API to change the proxy settings as I remember. But Webkit should honor the environment variable you export. But I'm not sure if it uses http_proxy or HTTP_PROXY to get the proxy to use.

**Comment by me-benni** [comment]
Setting HTTP_PROXY worked for me
