### ISSUE TITLE
combine autocommand with other commands

### ISSUE THREAD

**Issue by Docbroke** [fanglingsu/vimb#460]
I have set autocommand to keep scripts off, and I did try to turn javascript and reload website with single click using,
```
nnoremap <F8> :au! scripts|:set scripts=on|no! R<CR>
```
but it doesn't work. If I combine commands without autocommand  "au! scripts", they work, so I have to use two different keybinds at present.

**Comment by fanglingsu** [comment]
@Docbroke I'm not sure why the pipe after the augroup does not work. But following should work, even if it looks strange.

    nnoremap <F8> :au! scripts<CR>:set scripts=on|no! R<CR>

Might be useful to use "::" instead of single ":" to avaoid putting the commands into the history.

**Comment by Docbroke** [comment]
Thanks
