### ISSUE TITLE
vimb waits for :sh/x-hint-command to complete

### ISSUE THREAD

**Issue by Docbroke** [fanglingsu/vimb#461]
When I use x-hint-command to open url with some other application, vimb waits (becomes unresponsive) till that application is closed. Same happens with :sh command. 

To reproduce try something like
```
:sh firefox "$VIMB_URI"<CR>
```
After this vimb becomes unresponsive till firefox is open. Same happens while using x-hint-command.

**Comment by cdlscpmv** [comment]
Use the asynchronous version of the command: `sh! firefox ...`.

**Comment by Docbroke** [comment]
Thanks, I had read this in man page but failed to comprehend.
