### ISSUE TITLE
Can't watch YouTube videos above 720p

### ISSUE THREAD

**Issue by cprn** [fanglingsu/vimb#462]
`vimb, version 3.0-alpha`

### Steps to reproduce
1. Open 4K YouTube video, e.g. [this one](https://www.youtube.com/watch?v=Bey4XXJAqS8)
1. Try to switch video quality above 720p

### Expected behaviour
Options like 1080p (and higher) available.

### Actual behaviour
The [Missing options](https://support.google.com/youtube/answer/6322658?visit_id=0-636482107681491587-2279162750&p=missing_quality&rd=1) link instead of high quality options.

![2017-12-07-034707_2560x1440_scrot](https://user-images.githubusercontent.com/6132708/33696306-f1773ba4-db01-11e7-9190-584195c01945.png)

**Comment by Docbroke** [comment]
Probably a webkit issue. 
Above 720p videos are provided in two separate files ( one for video and one for audio), which needs to be mixed by the browser.

An alternative is to use youtube-dl with mpv for watching videos.

**Comment by cprn** [comment]
So... Other open-source WebKit based browsers, e.g. Chromium, take care of syncing and playing back the video and audio streams together? Would it be possible to just copy the approach into `vimb`?

**Comment by Docbroke** [comment]
Chromium is not based on webkit, it is based on blink ( same as google-chrome).  Check here https://wiki.archlinux.org/index.php/List_of_applications#Web_browsers

I have tested this with surf, (also based on webkit2) which gives the same "missing options".

**Comment by fanglingsu** [comment]
@cprn I think this is caused by youtubes switch from h.264 codec to more efiicient vp9 codec. I assume that gstreamer or the gst plugins do not fully support this. So there is nothing from side of vimb we can do.

**Comment by cprn** [comment]
@Docbroke I see. A bit more research shows there's a lib called Chromium Embedded Framework, currently used by e.g. Steam client. I was sure Steam runs on WebKit but indeed, it's Blink (via CEF). Is there any discussion about switching `vimb` from WebKit to CEF?

@fanglingsu I think you're right, it seems vp8 and vp9 got disabled in `libwebrtc`. I don't understand why the following webkit bugzilla issue comments state it's by Safari team's decision but it seems we're out of luck until they decide otherwise.

**Comment by fanglingsu** [comment]
@cprn I don't think vimb will switch to any other webengine. It's too much work and I assume that each way has it's own drawbacks.
