### ISSUE TITLE
Download handling

### ISSUE THREAD

**Issue by Docbroke** [fanglingsu/vimb#463]
How to view / cancel / pause ongoing download without closing vimb ?

**Comment by fanglingsu** [comment]
@Docbroke There is no download manager built into vimb. The only indicator might be the download progress bar at the right of the statusbar. I'm not as interested in putting it into vimb. I think it would be a greater deal to readd the external download feature to allow the user to configure some tool to manage the downloads.

**Comment by Docbroke** [comment]
Thank for the reply. Adding external download manager would be great.
I am currently using wget in new terminal window through my external-handler script (using `x-hint-command`).  Is it possible to  use `handler-add` to load all links that starts download, with wget or something like that?

**Comment by fanglingsu** [comment]
@Docbroke I think, the handler-add would not work for downloads. Because we can't decide if a URI will start a download or can be shown direct without doing the request and allow webkit to decide if the content can be shown direct ord have to be downloaded.

**Comment by jun7** [comment]
@fanglingsu  Hi. Webkit2gkt v2.20 adds APIs to manage cookies. So now it is may possible to use the downloaders. It returns cookies even in the ephemeral mode.
https://webkitgtk.org/reference/webkit2gtk/stable/api-index-2-20.html

I'm happy if below link helps you. Sorry for the dirty commit but see WEBKIT_CHECK_VERSION's sections.
https://github.com/jun7/wyeb/commit/f127cff9c9e850621844600b68a4f9e14afcf261
