### ISSUE TITLE
Hide the command bar if not in command mode

### ISSUE THREAD

**Issue by maciejsum** [fanglingsu/vimb#466]
Is it possible to hide the command bar (the one below the status bar) when I'm not typing any commands? Most of the time it's just a blank white bar and it is particularly annoying when watching videos in fullscreen mode.

**Comment by fanglingsu** [comment]
@maciejsum You could hide this by setting `:set input-autohide=on`. This hides the input bar if it's not empty. If there is somethings shown, like a result from `:e ...` you have to press `<Esc>` to clear it so it can be hidden.

**Comment by maciejsum** [comment]
This is exactly what I was looking for. I overlooked it at the manpage, thanks a lot and sorry.

**Comment by fanglingsu** [comment]
@maciejsum No problem.
