### ISSUE TITLE
vimb bspwm(?) rendering issues with Google authentication

### ISSUE THREAD

**Issue by Vintodrimmer** [fanglingsu/vimb#472]
```
➤ vimb --bug-info
Commit:          unknown
WebKit compile:  2.18.4
WebKit run:      2.18.5
GTK compile:     3.22.26
GTK run:         3.22.26
libsoup compile: 2.60.2
libsoup run:     2.60.3
Extension dir:   /usr/lib/vimb
```

### Steps to reproduce
1. Open youtube.com
2. Press the `sign in` button
### Expected behaviour
Redirection to the sigh in page.
### Actual behaviour
Rendering stops, as if the browser has been frozen.

If I launch some window above the the `vimb`, such as `Conky`, it will leave the black rectangle on the place it occupied.
Browser itself looks virtually frozen and there is no output to the console.

If I focus another window and then refocus the `vimb`, next page will be shown, where I have to enter my email address, after which it freezes again. This has to be repeated for every new page.

I guess this has something to do with Google's authentication scripts. There is another forum that I frequent that has recently introduced the Google's picture ReCaptcha and it began freezing too.

This might also be some issue with `bspwm`, since I have `bspc config ignore_ewmh_focus` turned off, so `chromium` doesn't steal focus occasionally.

**Comment by fanglingsu** [comment]
I can't reproduce this. But this sounds like a known issue with vimb running in tabbed #420. Where the screen isn't updated on changing a page.
does the issue also appear in case you run vimb without tabbed?

**Comment by Vintodrimmer** [comment]
It works perfectly without `tabbed`.

Sorry for misinformation.

**Comment by fanglingsu** [comment]
I hope we'll find the reason for this rendering issue when runnin vimb in tabbed. But at the time I have no idea why it happens. But it seems only to affect internal mapped bindings. Keys that are not handled by vimb but by webkit (Up, down cursor keys) do not show such issues.
