### ISSUE TITLE
Per-site default zoom possible?

### ISSUE THREAD

**Issue by rudism** [fanglingsu/vimb#473]
Is it possible to set per-site (based on domain) default zoom settings?

Barring the ability to do this through pure configuration, is there a way to adjust zoom in scripts.js? If so this may be doable by manually checking the domain and applying the change when necessary.

**Comment by cdlscpmv** [comment]
There are autocommands for that. Try adding this to your config file:
`autocmd LoadCommitted <URL-pattern> normal! zi`

You can prefix `zi` with a number if you want more zoom. The URL-pattern
is described in the man page in the section about autocommands.

**Comment by rudism** [comment]
Perfect solution, thanks.

**Comment by fanglingsu** [comment]
@cdlscpmv thank you for answering.
@rudism If you want to ahve more fine grained controll about the zoom you could set the default-zoom level (defaul is 100) by the autocommands.
```
aug zoom
au LoadCommitted * set default-zoom=100
au LoadCommitted http{s,}://github.com/* set default-zoom=160
aug end
```
