### ISSUE TITLE
[Feature Request] Commands for going back and forward in history

### ISSUE THREAD

**Issue by troydm** [fanglingsu/vimb#476]
It would be nice to have commands for going forward and backward and ability to map them to other keys. 
Like for example I want to swap behaviour of <C-i> and <C-o> but currently I can't do it

**Comment by fanglingsu** [comment]
@troydm I don't know what you want to achieve. As I understand you should toggle the keybindings by 
```
:nnoremap <C-o> <C-i>
:nnoremap <C-i> <C-o>
```

**Comment by troydm** [comment]
Ah thx, didn't knew this worked as I've tried doing it with nmap and it didn't worked for me, silly me
