### ISSUE TITLE
Link hinting cut off by the edges of the window

### ISSUE THREAD

**Issue by brainard52** [fanglingsu/vimb#477]
[Here is a screenshot](https://i.imgur.com/O2vZPMt.png)

I don't know whether this demonstrates very well, but I'm specifically pointing out how 12 and 13 are covered up by the edges of the window. I think it would be reasonable to put it at the very center of the link. I don't think removing the transparency would be a bad thing either since it's not always going to be covering the text.

**Comment by fanglingsu** [comment]
The labels are cut of, because I've set them to appear a little left and above the link. Else the labe might cover too much of the link. In most cases this is a sane default. If you like it othe you only need to modify the _src/scripts/hints.css_ file (remove the `-webkit-transform:translate` and `opacity `lines) and recompile vimb.

**Comment by brainard52** [comment]
The fact that the label will cover the link is almost irelevant since the label won't be shown until you already know where you want to go on the site. It seems to me that ensuring that every label will be shown completely would be the most important thing. The transparency isn't really a problem. I just mentioned it since it could simplify things a bit. Is there any way you'd be able to set these things as togglable during runtime or via an rc?

**Comment by fanglingsu** [comment]
@brainard52 You can adapt the style by putting the style definitions into the `$XDG_CONFIG_HOME/vimb/style.css` file and enabling using the user style `:set stylesheet=on` (if not already enabled). You can orient on the sample [dark theme css](https://fanglingsu.github.io/vimb/howto.html#dark-theme).
According to the label covering the link: If you open a long page and start the hinting and scroll by mouse or something similar, the hints are recreated for the new appearing links. So there are cases where the user does not see the link before it will be covered by the label. The current hint labels are only a default, and are designed according to other hinting browsers.
