### ISSUE TITLE
Does not recognize localhost as address.

### ISSUE THREAD

**Issue by JJK96** [fanglingsu/vimb#478]
### Steps to reproduce
:open localhost

### Expected behaviour
connect to my localhost web server

### Actual behaviour
searches for "localhost" using default search engine

**Comment by cdlscpmv** [comment]
If you are running an http server, try  opening `http://localhost:port/`.

**Comment by dantleech** [comment]
This works for me `:o http://localhost:8080` - `:o localhost:8080` does open the search engine howerver (as would firefox).

**Comment by dantleech** [comment]
> Firefox does not open the search engine for me.

Ah maybe only with Vimperator / VIM Vixen.

**Comment by fanglingsu** [comment]
@JJK96 Yes, if the string after the open does not contain a '.' it's resolved by the shortcut system. You may use the `:open http://localhost` direct or do a dirty workareound by setting a shortcut called 'loclahost' `:shortcut-add localhost=http://localhost`.

**Comment by sagb** [comment]
Another workaround is `:open localhost.` (with dot at the end).
