### ISSUE TITLE
Is editor-command broken on the gtk migration?

### ISSUE THREAD

**Issue by sdothum** [fanglingsu/vimb#479]
vimb, version 3.1.0
### Steps to reproduce
set editor-command="gvim -f %s"
;e (also for Ctrl-T)
### Expected behaviour
gvim editing of form
### Actual behaviour
** (vimb:5746): WARNING **: 21:30:39.332: Could not spawn editor-command

**Comment by fanglingsu** [comment]
I think you should remove the quotes `set editor-command=gvim -f %s`.

**Comment by sdothum** [comment]
Beautiful! That did it.

Thank you for maintaining my favourite browser.
