### ISSUE TITLE
How can i compile vimb on mint

### ISSUE THREAD

**Issue by direcyoung** [fanglingsu/vimb#481]
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
Package webkit2gtk-4.0- was not found in the pkg-config search path.
Perhaps you should add the directory containing `webkit2gtk-4.0-.pc'
to the PKG_CONFIG_PATH environment variable
No package 'webkit2gtk-4.0-' found
cc shortcut.o
shortcut.c:20:18: fatal error: glib.h: No such file or directory
compilation terminated.
Makefile:27: recipe for target 'shortcut.o' failed

**Comment by direcyoung** [comment]
i have webkit2gtk-4.0.37 , i find   WebKitGTK+ 2.21.1    in internet , should i download it?

**Comment by mati75** [comment]
You need install this packages: libgtk-3-dev libwebkit2gtk-4.0-dev libglib2.0-dev

**Comment by direcyoung** [comment]
thank you , i finished install
![screenshot_2018-04-27_13-15-19](https://user-images.githubusercontent.com/6316447/39345797-29354d4e-4a1d-11e8-96ea-440181089105.png)
