### ISSUE TITLE
Select and yank text

### ISSUE THREAD

**Issue by mb720** [fanglingsu/vimb#482]
Hi and thanks a lot for vimb!

Being new to the browser, I was wondering whether there's a way to select and yank text other than URIs from a web site.
VimFx had `vf` that would show a hint for each paragraph (and other elements) on a site and placed the cursor there. I could then use Vim movements (e.g `jklh`) to move the cursor, use `v` to start selecting, and `y` to yank the text into the system clipboard.

That was a great feature.

Does something similar exist in vimb?

**Comment by fanglingsu** [comment]
@mb720 Yes you can yank selected text via `Y`. But there are no built in keybindings to easily select paragraphs or sentences by hinting. But as a workaround you could use the search to select the first word which you want to yank and use Shift+Cursor keys to expand the selection. If all is selected you can yank it by `Y`.
