### ISSUE TITLE
Using Impossible Amounts of Memory

### ISSUE THREAD

**Issue by BadDecisionsAlex** [fanglingsu/vimb#484]
vimb, version 3.0-alpha

### Steps to reproduce
open vimb

### Expected behaviour

have a nice lightweight browser

### Actual behaviour

Virtual Memory Use : 98gb on webkit2gtk-4.0/WebKitWebProcess 1 19

**Comment by BadDecisionsAlex** [comment]
As a side note : 
I have some free time this summer and would like to help work on this project.
I have a few ideas for specific features I want to add for myself; but I figured the best way to get my feet wet was to help take care of a few existing issues with a bit of guidance from y'all.

**Comment by fanglingsu** [comment]
@BadDecisionsAlex I'm not familiar with the different memory meanings. But `top` reports also such hight values on my system. But this does not have any meaning, because I can open many instances without any issues on 4GB ram (used only <1GB most of the time). If I check the memory reported by ps_mem.py I get following output.
```
 Private  +   Shared  =  RAM used       Program

 16.2 MiB +  12.6 MiB =  28.8 MiB       vimb
156.8 MiB +  34.8 MiB = 191.7 MiB       WebKitWebProcess (2)
---------------------------------
                        220.4 MiB
=================================
```

**Comment by BadDecisionsAlex** [comment]
Private/shared has to do with memory sharing between processes, which is not really relevant here. All we need to worry about is RAM used.

The issue is mine is 96GB, which is impossibly high.

**Comment by BadDecisionsAlex** [comment]
I was able to collect these errors as well.

```
** (vimb:18940): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-RNAj28awSO: Connection refused

(vimb:18940): Gtk-WARNING **: Theme parsing error: <data>:1:62: 'caret-color' is not a valid property name

** (WebKitWebProcess:18952): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-RNAj28awSO: Connection refused
```

**Comment by fanglingsu** [comment]
@BadDecisionsAlex Two of the eroors say, that the dbus connection between the ui process and the webprocess could not be established. The error with the caret-color could be aovided by removing this from the gtk css rules https://github.com/fanglingsu/vimb/blob/9acf27194f5814aea179d8618a44ebdc08fa8300/src/config.def.h#L45
Top reports also on my system a virtual memory usage of about 300Gb, but I can use many instances of vimb without any drawbacks.

**Comment by fanglingsu** [comment]
@BadDecisionsAlex Does the momory allocation depend on your settings? Could you try with empty configuration?

**Comment by exitium** [comment]
WebKit intentionally allocates this memory with its [Gigacages](https://labs.mwrinfosecurity.com/blog/some-brief-notes-on-webkit-heap-hardening/).

**Comment by fanglingsu** [comment]
@exitium Thank you for providing the link.
So I close this, because it seems to be indended behaviour of webkit.
