### ISSUE TITLE
Possible support for pasting images?

### ISSUE THREAD

**Issue by dantleech** [fanglingsu/vimb#485]
This might be out-of-scope - but one of the (few) features I really miss in Vimb compared to FF/Chrome is the ability to paste images into, for example, github issues / PRs

**Comment by mlopes** [comment]
I wonder if that would have to be implemented at the webkit level though?

**Comment by dantleech** [comment]
I _think_ it already is, at least they seem to now support pasting in HTML documents with images: https://webkit.org/blog/8170/clipboard-api-improvements/

**Comment by fanglingsu** [comment]
As I understand it right, the clipboard api is only available on IOS systems. I think pasting HTML has many security drawbacks and will bloat vimb. I assume most of the vimb users do not have tools that allow yanking html with images that could be pasted into vimb. So I won't do any work on this feature.

**Comment by dantleech** [comment]
If it makes any difference - this isn't about pasting HTML, but pasting images. I work on Linux, and the feature works both in FF and chrome. Typically I copy to the clipboard as follows:
```
xclip -selection clipboard -t image/png < someimage.png
```

or I copy an image in Gimp.

**Comment by fanglingsu** [comment]
I've checked if the images could be pasted by `webkit_web_view_execute_editing_command`, but this does only work for texts but not images. If there is a solution with some lines of code I'd put this into vimb.

**Comment by dantleech** [comment]
I think Github etc. uses the Clipboard API, which is supported by Webkit:

https://twitter.com/WebKitGTK/status/1001080141311873025

and seems also supported by VimB: https://whatwebcando.today/clipboard.html

So still not sure why it doesn't work :thinking:

**Comment by fanglingsu** [comment]
@dantleech I've thought that there might be a [setting](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html) which will enable the feature to work right. But I can't find any setting which would do the trick.

**Comment by dantleech** [comment]
Cool, I'll ask on the WebKit GTK+ mailing list or IRC and see if they can point the way
