### ISSUE TITLE
Customize search colors

### ISSUE THREAD

**Issue by dealelopez** [fanglingsu/vimb#487]
Is possible to customize the background and foreground color of highlighted words with the search function?

**Comment by fanglingsu** [comment]
There is no api tp change this direct, but I assume you can change this by css in _$XDG_CONFIG_HOME/vimb/style.css_ file. But I can't find the pseudo element to access the search hits https://stackoverflow.com/questions/41244357/how-can-i-change-the-style-of-highlighted-texts-in-the-browser-search-result/41244420#41244420. But the current focused one can be cahnged by
```css
::selection {
    background-color: #f0f;
}
```

**Comment by fanglingsu** [comment]
@dealelopez I close this because there seems to be no way to change this direct. If you find a way, please let us know it.
