### ISSUE TITLE
UTF-8 characters are not passed correctly from the external editor to textfields

### ISSUE THREAD

**Issue by svensp** [fanglingsu/vimb#492]
Commit:          3.1.0-26-g4e8c5b2
WebKit compile:  2.20.1
WebKit run:      2.20.1
GTK compile:     3.22.29
GTK run:         3.22.29
libsoup compile: 2.62.1
libsoup run:     2.62.1
Extension dir:   /usr/local/lib/vimb
### Steps to reproduce
Open a text field in an external editor
add utf-8 characters
save the file

### Expected behaviour
UTF-8 characters appear in the text field as seen in the file

### Actual behaviour
g_strescape escapes each byte of the UTF-8 characters separatly, causing for 2 unintended characters to appear instead.

I did some googling and it seems there have been 2 attempts to add a g_utf8_strescape function to glib but neither reached a conclusion.
I'm also currently testing only escaping \r, \n and " via util_str_replace and it seems to fix the imidiate problem - the utf-8 characters appear - but I'm not sure if that doesn't just open the door for more problems in the future

**Comment by fanglingsu** [comment]
@svensp Thank you for you investigation. I've introduced this issue by 1c18deec15b84b99ef2b1d4947ccb6739398d418. The multiple calls to `util_str_replace()` here to much in my opinion and I found the `g_strescape` function I thought would do the dirty stuff for us. I'll write a separate escaping function.
