### ISSUE TITLE
Vimbhint styles

### ISSUE THREAD

**Issue by dealelopez** [fanglingsu/vimb#497]
I've seen that `._hintLabel`s have been replaced for `vimbhint`. Is possible to customize the styles like before with CSS?

**Comment by dealelopez** [comment]
I've found the solution.
In styles.css you can use this to style them:
`span[vimbhint="label"]`
`span[vimbhint="label focus"]`
`a[vimbhint="hint"]`
`a[vimbhint="hint focus"]`

**Comment by fanglingsu** [comment]
@dealelopez The reduction to 'a' elements is to strict, note that also form elements and images can be accessed by hinting. I think you can use the sample dark theme css https://fanglingsu.github.io/vimb/howto.html#dark-theme as example how to address the hinted elements.

**Comment by dealelopez** [comment]
@fanglingsu thanks a lot!
