### ISSUE TITLE
3.2.0 compile-time error: no scripts/scripts.h file

### ISSUE THREAD

**Issue by mazocomp** [fanglingsu/vimb#500]
Hi!

I checked your tree and don't see this file, do you test builds before releasing?
```
input.c:30:10: fatal error: 'scripts/scripts.h' file not found
#include "scripts/scripts.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by iamleot** [comment]
Leonid Bobrov writes:
> Hi!
>

Hello Leonid!

> I checked your tree and don't see this file, do you test builds before releasing?
> ```
> input.c:30:10: fatal error: 'scripts/scripts.h' file not found
> #include "scripts/scripts.h"
>          ^~~~~~~~~~~~~~~~~~~
> 1 error generated.
> ```

I think that:

 https://github.com/fanglingsu/vimb/pull/496

should fix that.

**Comment by mazocomp** [comment]
On Tue, Jun 26, 2018 at 04:14:54AM -0700, Leonardo Taccari wrote:
> Leonid Bobrov writes:
> > Hi!
> >
> 
> Hello Leonid!
> 
> > I checked your tree and don't see this file, do you test builds before releasing?
> > ```
> > input.c:30:10: fatal error: 'scripts/scripts.h' file not found
> > #include "scripts/scripts.h"
> >          ^~~~~~~~~~~~~~~~~~~
> > 1 error generated.
> > ```
> 
> I think that:
> 
>  https://github.com/fanglingsu/vimb/pull/496
> 
> should fix that.
> 

Ok, I thought that commit doesn't make sense...

Thanks, issue closed.
