### ISSUE TITLE
Weird position values on text page

### ISSUE THREAD

**Issue by TimsManter** [fanglingsu/vimb#501]
**vimb, version 3.2.0**
### Steps to reproduce
Go to [kernel coding style](https://www.kernel.org/doc/Documentation/process/coding-style.rst) and scroll down the page,
### Expected behaviour
Page position indicator (at right in address bar) shoud inform about view position on the page in %s.
### Actual behaviour
Values starts from about 61537% and while scrolling go to 0% then loop again from around 2^16%.

**Comment by fanglingsu** [comment]
@TimsManter Thank you for your detailed investigations. These information helped me a lot. I've made a new branch so we can test this a while.
