### ISSUE TITLE
FATAL: Primitive gigacage disabled, but we don't want that in this process.

### ISSUE THREAD

**Issue by Walther-MD** [fanglingsu/vimb#508]
After updating my Gentoo install's webkit-gtk version to 2.20.3, vimb cannot open any windows, it appears a Heap protection mechanism is not being initialized and webkit refuses to run without it.

$ vimb --bug-info -->
Commit:          unknown
WebKit compile:  2.20.3
WebKit run:      2.20.3
GTK compile:     3.22.30
GTK run:         3.22.30
libsoup compile: 2.58.2
libsoup run:     2.58.2
Extension dir:   /usr/lib/vimb

### Steps to reproduce
Start vimb
### Expected behaviour
webview opens up and loads homepage

### Actual behaviour
Fatal error is printed by webkit-gtk, pages do not load: FATAL: Primitive gigacage disabled, but we don't want that in this process.

**Comment by fanglingsu** [comment]
@Walther-MD I'm not sure if we can do anything from vimb to avoid this. I'm not familiar with the last changes to establish the gigacages. But as I understand the gigacages are enforced by webkit for some data strcutures/heaps and there are cases where the memory of the gigacages could not be allocated. In this case this error message is printed and the process ends.
I can't reproduce this on my linux machine. But it might worth trying to disable the gigacages by setting environment variable `GIGACAGE_ENABLED="no"` see [Gigacage.cpp](https://github.com/WebKit/webkit/blob/master/Source/bmalloc/bmalloc/Gigacage.cpp#L263). But I'm not sure if this will help you and I'm not sure if thie is a good decission.

**Comment by Walther-MD** [comment]
I'll try researching the issue myself and report back if I find anything. For now, disabling gigacage allows vimb to function normally, even if it's not the best choice :/
