### ISSUE TITLE
Please add new feature to remap function

### ISSUE THREAD

**Issue by lbkvu** [fanglingsu/vimb#510]
Currently, vimb uses `Ctrl+O` to go back. I want to map this "go back" function to H but can't find any way to do it.

I suggest 2 approaches:
1. Allow remap of Ctrl+O to H
2. Allow function to be mapped. Ex:
```
:nnoremap H :goback<CR>
```

**Comment by cdlscpmv** [comment]
`:nnoremap H <C-O>` should do it.
