### ISSUE TITLE
Can't enter input mode

### ISSUE THREAD

**Issue by ParanoidNote** [fanglingsu/vimb#511]
### Steps to reproduce
Build and run vimb.

### Expected behaviour
When i press "gi" in normal mode according to the [man page](https://fanglingsu.github.io/vimb/man.html) vimb should enter input mode.

### Actual behaviour
vimb remains in normal mode, only some letters are entered and others are recognized as commands. Currently the only way to enter text in input boxes is using pass-through mode.

Am i the only with this issue? Am i missing something?

**Comment by fanglingsu** [comment]
@ParanoidNote It might be an issue with the webextension. Can you scroll using `j` or `k`? What happens if you click into form field by mouse?

**Comment by ParanoidNote** [comment]
scroll with `j` and `k` doesn't work and if i click with mouse it remains in normal mode

**Comment by ParanoidNote** [comment]
Yeah it reports `Extension dir: /usr/local/lib/vimb` while the webext_main lib is under /usr/lib.

I was trying to build a package for alpine linux and PREFIX=/usr was set only when running make install, setting it for the entire build process fix the issue.

On voidlinux the official package is broken for the same reason i think.

Thanks again for your help!
