### ISSUE TITLE
External editor, not writing to temporary file

### ISSUE THREAD

**Issue by dantleech** [fanglingsu/vimb#512]
Version: 3.2.0

### Steps to reproduce

Invoke the external editor on a text area

### Expected behaviour

Writes contents of text area to temporary file, opens external editor.

### Actual behaviour

Temporary file does not exist, external editor opened with a new file.

---

I debugged this and in `gboolean util_create_tmp_file` the correct number of `bytes` are being returned from `write` - no error is raised but the file does not exist at the path and the newly opened editor reports that it is editing a "new file".

**Comment by fanglingsu** [comment]
@dantleech Hm, do you use systemd - might be the tmp file is not created direct in /tmp but in private systemd tmp directory. Can you please provide some information about you system helping to near down the issue?

**Comment by dantleech** [comment]
Hmm it seems to work with `gvim` but not through a terminal:

```
set editor-command=gvim -f %s
```

is fine, but

```
set editor-command=gnome-terminal -- "vim %s"
```

or

```
set editor-command=xfce4-terminal -e "vim %s"
```

Causes the reported problem

**Comment by dantleech** [comment]
Yeah, very odd. I tried with the suckless terminal (`st`?) and it worked fine, but neither `gnome-terminal` nor `xfce4-terminal` work:


```
set editor-command=xfce4-terminal --initial-title scratchpad --command=vim %s
```

```
xfce4-terminal: Unknown option "/tmp/daniel/vimb-6SISNZ"
```

Will update if I find a solution

**Comment by dantleech** [comment]
Sounds exactly like my issue - I'll close this ticket then, as guess theres nothing we should do about here/ Thanks for investigating :)
