### ISSUE TITLE
Mailing list CAPTCHA broken

### ISSUE THREAD

**Issue by serussell** [fanglingsu/vimb#518]
Tried to sign up for the mailing list; went through the visual CAPTCHA -- not kidding -- ten times.  Gave up and tried the audio, which was clear; entered the text and got a message saying that my browser may be sending automated queries.  I tried to subscribe with vimb (3.2.0-1, on Arch).

![screenshot-20181009t11 16](https://user-images.githubusercontent.com/504337/46683107-f634b000-cbb4-11e8-8840-9a36d3534080.png)

Mostly, I blame Sourceforge, but in any case, I'm unable to subscribe to the mailing list.  Is there an IRC, or Matrix room, or something?

**Comment by fanglingsu** [comment]
@serussell Thank you for reporting this issue. I think it's an recaptcha issue and none of sourceforge. I've tested it on https://patrickhlauke.github.io/recaptcha/ and this does also not end for me if i use vimb. But if works if i use chomium.
I've set the same user-agent in vimb as chromium uses, but this did not change anything.
But if I open the webdeveloper tools in vimb by `gF` I can see many erros like
```
[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''report-sample''. It will be ignored.
[Error] The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
```
I fear that theses errors prevent the recaptcha to work properly. These Content-Security-Policies are not available at the time via webkit (https://bugs.webkit.org/show_bug.cgi?id=175277 and https://bugs.webkit.org/show_bug.cgi?id=184031)

I don't think we can do here anything to get this working. Sometimes it helps to wait for google to fix their damn online tools.
