### ISSUE TITLE
Cannot uninstall vimb?

### ISSUE THREAD

**Issue by beef6** [fanglingsu/vimb#527]
### Steps to reproduce
Installed vimb via installation instructions. Used, did not want to change from qutebrowser. Attempted to: sudo pacman -Rs vimb, successful.
### Expected behaviour
vimb would be uninstalled from my computer.
### Actual behaviour
vimb is still in dmenu and can be called on the terminal. Acts as default browser when clicking links from IRC. I have scoured computer for files for vimb.

pkgfile vimb returns nothing
sudo pacman -Qo `which vimb` returns: error no package owns /usr/local/bin/vimb

Would like some help or guidance, thank you.

**Comment by iamleot** [comment]
Hello beef6,

beef6 writes:
> 
> ### Steps to reproduce
> Installed vimb via installation instructions. [...]
> [...]
> ### Actual behaviour
> vimb is still in dmenu and can be called on the terminal. Acts as default browser when clicking links from IRC. I have scoured computer for files for vimb.
>
> pkgfile vimb returns nothing
> sudo pacman -Qo `which vimb` returns: error no package owns /usr/local/bin/vimb
> [...]

If you have installed vimb via:

 % make install

Doing:

 % make uninstall

will uninstall it.

**Comment by beef6** [comment]
> Hello beef6, beef6 writes:
>  ### Steps to reproduce Installed vimb via installation instructions. [...] [...] ### Actual behaviour vimb is still in dmenu and can be called on the terminal. Acts as default browser when clicking links from IRC. I have scoured computer for files for vimb. pkgfile vimb returns nothing sudo pacman -Qo `which vimb` returns: error no package owns /usr/local/bin/vimb [...]
> If you have installed vimb via: % make install Doing: % make uninstall will uninstall it.

Thank you for your reply. I tried this. Since I:
`sudo -Rs vimb`
and also
`sudo rm -rf vimb` (github repo)

I had to:
`cd /usr/local/bin`
`rm vimb`
to get the program to stop being called and used in dmenu. I hope this helps anyone else stuck in my predicament. I'm el stupido.

**Comment by iamleot** [comment]
beef6 writes:
> [...]
> I had to:
> `cd /usr/local/bin`
> `rm vimb`
> [...]

If you have manually removed it, you will probably also need to
remove:

 /usr/local/lib/vimb/webext_main.so
 /usr/local/share/applications/vimb.desktop
 /usr/local/share/man/man1/vimb.1

**Comment by fanglingsu** [comment]
@beef6 I do not understand how you installed vimb. Did you `make install` or did you use `makepkg` to buily and installthe package. If youused `make install` a `make uninstall` should have worked.

**Comment by beef6** [comment]
@fanglingsu I did the `make install` but did not know that a simple `make uninstall` would work. I had deleted the file instead of hiding it. I learned the hard way, thank you for providing me with the opportunity to do so. :smile:

**Comment by AloisMahdal** [comment]
@beef6 just make sure you always use `make uninstall` from the exact same commit as you used `make install`, list of installed/uninstalled files may change between commits so you might end up with stray files.  (I've learned that the hard way.)

(If that seems clumsy, well that's why we have package managers. ;-))
