### ISSUE TITLE
Paypal closing all windows

### ISSUE THREAD

**Issue by serussell** [fanglingsu/vimb#535]
```
Commit:          5cc4709
WebKit compile:  2.22.4
WebKit run:      2.22.5
GTK compile:     3.24.1
GTK run:         3.24.2
libsoup compile: 2.64.2
libsoup run:     2.64.2
Extension dir:   /usr/lib/vimb
```

I don't know if this is a bug, per se, or just some wierd interaction with how this one site is using Paypal.  I'm curious if anybody else has seen this.

I have some VMs in [Veeble](https://www.veeble.org); when I go to pay an invoice and choose Paypal, it opens the new window and I complete the Paypal transaction just fine.  When it comes to the step where the Paypal pop-up window closes, though, both that and the original invoice window close so I can't complete the transaction on the Veeble site.

Is everybody else able to use Paypal without issue?  Is it just Veeble?  Is it just me?  Are there known config settings that break Paypal?  I _believe_ that I have this same issue with other sites, but as I haven't payed for anything else with Paypal in a while I can't recall if I needed to fall back to Chrome for that as well.

**Comment by fanglingsu** [comment]
@serussell Thank you for reporting this issue. I don't use paypal and I don't know any page where the payment process could be tested with a paypal sandbox account. So I hope someone else can help to investigate this issue.

**Comment by fanglingsu** [comment]
@serussell This might be an issue with the way vimb treats the popups. I fear that is something wrong in the way vimb handles the webextension and the relations between webpage and browser instance. This is only a guess at the moment. I'll try to get a minimal test case which opens a new window via JS that is closed on clicking some link. Might be we can reproduce the issue this way.

**Comment by serussell** [comment]
@fanglingsu , thanks -- let me know if there's anything I can do to help.

**Comment by iamleot** [comment]
Hello Sean,

Sean Russell writes:
> @fanglingsu , thanks -- let me know if there's anything I can do to help.

It wasn't suggested and probably will just steal a minute or two...

Can you please try that with another webkit-gtk browser? (e.g.
Midori or if your package system has it there is also MiniBrowser
that is part of webkit-gtk.)


Thanks!

**Comment by serussell** [comment]
@iamleot Yes!  I have at least one other webkit-based minimalist browser installed; however, I'm traveling and won't have access to that computer for another two weeks.  Don't close this -- I'll do it when I get home!  Thanks.

**Comment by serussell** [comment]
I'm back, and I've run two tests.

### Check-out from a different company (GouletPens.com)

Same `vimb` behavior: completing the transaction in the PayPal pop-up window closes both windows.

### Check-out using `wyeb`

[wyeb](http://wyeb.org) is also a WebKit based browser (webkit2gtk).  It does _not_ close both windows, and I was able to complete a transaction.

Is there any other information I can provide?

**Comment by fanglingsu** [comment]
@serussell Do you know if vimb was closed or crashed by a segfault. If a segfault occured this issue might be related or the same like #537 which is hopefully fixed now.

**Comment by serussell** [comment]
@fanglingsu , interesting thought.  I do not know; I don't run `vimb` from the command line, so I wouldn't have seen a segfault.  Next time I plan to check out with Paypal, I'll run it from the command line and see.

**Comment by fanglingsu** [comment]
@serussell Better you use the latest version. If all works fine - this is a better proof that the bothe issues where the same:)

**Comment by serussell** [comment]
Hmmm.  I've got it installed via the package manager on Arch, which is 3.3.0-2, which claims it was built this past Dec 17.  I'm probably going to wait until Arch updates the package, but I'll report back when it does and I can test it.

**Comment by fanglingsu** [comment]
@serussell You could also use https://aur.archlinux.org/packages/vimb-git/ which uses the current master branch.
If you use arch linux, you should have systemd installed and can possibly request segfaults by `coredumpctl list vimb`.

**Comment by serussell** [comment]
I haven't noticed this in a while, so closing.
