### ISSUE TITLE
Hinting lag when `set input-autohide=true`

### ISSUE THREAD

**Issue by lifranc** [fanglingsu/vimb#540]
Versions:
- vimb: 3.3.0
- webkit: 2.22.5 (built with `-DENABLE_X11_TARGET=OFF`)

Hinting often, but not always, takes about a second, and sometimes up to 2 or 3 seconds to by displayed after using a hinting shortcut of any kind.

Obviously, with webkit built without Xorg, it is using wayland backend.

My very wild guess is it has to do with wayland, since I cant find any related bug reports and most people still use X (at least with xwayland)

I'll do more testing as I only recently started using vimb again after qutebrowser started to misbehave.

**Comment by iamleot** [comment]
Hello Li,

Li writes:
> [...]
> Versions:
> - vimb: 3.3.0
> - webkit: 2.22.5 (built with `-DENABLE_X11_TARGET=OFF`)
>
> Hinting often, but not always, takes about a second, and sometimes up to 2 or 3 seconds to by displayed after using a hinting shortcut of any kind.
>
> Obviously, with webkit built without Xorg, it is using wayland backend.
>
> My very wild guess is it has to do with wayland, since I cant find any related bug reports and most people still use X (at least with xwayland)
>
> I'll do more testing as I only recently started using vimb again after qutebrowser started to misbehave.
> [...]

Can you please share an HTML file and/or an URL to try to reproduce
that?


Thanks!

**Comment by lifranc** [comment]
@iamleot Sure!

https://duckduck.com/
https://www.google.com/

Those two reliably have hinting lag. It seems to happen less on domains in my JS whitelist. But allowing scripts on duckduckgo.com didnt fix the issue there.

**Comment by iamleot** [comment]
Li writes:
> @iamleot Sure!
>
> https://duckduck.com/
> https://www.google.com/
>
> Those two reliably have hinting lag. It seems to happen less on domains in my JS whitelist. But allowing scripts on duckduckgo.com didnt fix the issue there.
> [...]

Thanks!

(Instead of duckduck.com I have tried with <https://duckduckgo.com>)
I could not reproduce it with:

 % vimb --bug-info
 Version:         3.3.0-16-g6aa6a51
 WebKit compile:  2.22.5
 WebKit run:      2.22.5
 GTK compile:     3.24.3
 GTK run:         3.24.3
 libsoup compile: 2.64.2
 libsoup run:     2.64.2
 Extension dir:   /usr/pkg/lib/vimb

(This is on a NetBSD/amd64 -current machine with X11 though.)

Can you please also share for completeness also the information of
`vimb --bug-info' not sure if - maybe! - also the GTK version can
be relevant too.


Thanks again!

**Comment by fanglingsu** [comment]
@lifranc For me the hints appear immediately. The hints would take some time on pages with a lot of elements like those with endless scrolling where new elements are added to the end.
I see only following field to investigate at the time.
1. Wayland - If wayland is the culprit it might be some screen redrawing issue. So also other actions like scrolling by mousewheel or link hovering should show a rendering lag.
2. DBus - The communication between webextension and the UI process uses DBus. Not shure, but this might also generate some lag between typing and the appearing of the hints. In this case also other DBus driven action should lag e.g. scrolling by `n` or `CTRL-G`.

**Comment by lifranc** [comment]
@iamleot 
```sh
> vimb --bug-info
Commit:          unknown
WebKit compile:  2.22.5
WebKit run:      2.22.5
GTK compile:     3.24.1
GTK run:         3.24.1
libsoup compile: 2.64.2
libsoup run:     2.64.2
Extension dir:   /nix/store/841qvslfavvslw70j3iij48h6jmfp2pq-vimb-3.3.0/lib/vimb
```

@fanglingsu It happens on pages with very few element like https://duckduckgo.com/
The scrolling shortcuts don't display any bug. In fact the `;o` shows up after a few 100ms lag and then the hinting will display after a *second* slightly (subjectively - no measure taken) longer lag. I'll have a newer build soon, as we are deploying our continuous build for a wayland-focused nixos, so I'll keep reporting as I can test new builds.

**Comment by athrungithub** [comment]
`version:         3.3.0-16-g6aa6a51
WebKit compile:  2.22.5
WebKit run:      2.22.5
GTK compile:     3.24.4
GTK run:         3.24.4
libsoup compile: 2.64.2
libsoup run:     2.64.2
Extension dir:   /usr/local/lib/vimb`

the site archlinux.org is lag. in x11 or wayland backend.
in github is fast 
Thanks vimb!

**Comment by lifranc** [comment]
> the site archlinux.org is lag. in x11 or wayland backend.
> in github is fast

I can reproduce here. Same result.

**Comment by lifranc** [comment]
This is still an issue with my latest build.
```
❯ vimb --bug-info                                                                            ~
Commit:          unknown
WebKit compile:  2.24.0
WebKit run:      2.24.0
GTK compile:     3.24.5
GTK run:         3.24.5
libsoup compile: 2.64.2
libsoup run:     2.64.2
Extension dir:   /nix/store/45agcn03sff56ns1id1cq7v8a9qsgij9-vimb-3.3.0/lib/vimb
```

**Comment by fanglingsu** [comment]
@lifranc I don't have any glue what should generate such a lag. Maybe you can post some pages where the hinting appears fast - if there are any. Do you have a chance to run vimb in X environment and check the hinting.

**Comment by lifranc** [comment]
I narrowed it down, the issue goes away when
```
set input-autohide=true
```
is changed to
```
set input-autohide=false
``````

And now I remember having issues with rendering on X with this option as well...
Github is fast, and if the input bar is showing from a previous command, then it
is fast on any domain. All `file://` 'domains' appear to get lag. I have no idea what the domain-name related behavior is about.

**Comment by fanglingsu** [comment]
@lifranc That's interesting. But I can't see any difference in the time the hints appear independant from the `input-autohide` value. This sounds strange to me. There is no relation between hinting and the inpubox except of the fact that starting the hinting should open it to display the `;o`.

**Comment by lifranc** [comment]
Actually, I could open another issue, since there seems to be all kinds of bad behavior whenever the statusbar or command input lines are hidden. Hiding the status bar results in render-freezes. Everything feels fine when both are not hidden.

**Comment by lifranc** [comment]
I'll open a different issue (if it hasn't been done by then) when I'm ready to debug it. Now Im back on vimb, on wayland, and it's great!
