### ISSUE TITLE
inoremap prevents character inputing after timeout

### ISSUE THREAD

**Issue by noboruma** [fanglingsu/vimb#546]
vimb, version 3.3.0-21-ga884a81

### Steps to reproduce
I have the following in my config:
inoremap jj \<Esc\>j

### Expected behaviour
If I input j and wait a bit, I would expect j to appear in the input.

### Actual behaviour
j never shows up. jj works, j does nothing.

**Comment by fanglingsu** [comment]
@noboruma Thank you for this report. We had a similar issue year before #258 which was solved by a pull request. But I can't find any code of this now. This might have been dropped during migration to webkit2.

**Comment by noboruma** [comment]
@fanglingsu Thanks for the reply! Good to know this issue was already raised, I will see if I can get it working and make a new PR.

**Comment by noboruma** [comment]
#547 is waiting for approval, I am closing this issue.
