### ISSUE TITLE
Disable highlighting hinted text.

### ISSUE THREAD

**Issue by Docbroke** [fanglingsu/vimb#548]
When hint command is used vimb highlights hinted text in yellow along while displaying hint labels. Is there any way to avoid highlighting hinted texts ? On some pages with many clickable elements entire page goes yellow. I tried to set colour of hinted text to while with style.css, but that doesn't work on pages with non-white background.

Additionally can we turn off hint link triggering with hinted text  while using only hint labels. This gets confusing sometimes. For examples, page has link text "next", while some other link may have hint label "NE". So while user types "NE" looking for next, actually some other link with "NE" label is triggered.

**Comment by fanglingsu** [comment]
@Docbroke Thank you for your suggestion.
1. You should be able to disable the yellow marking of hinted elements by _style.css_ using this rule
```css
*[vimbhint^='hint'] {
    background-color: inherit !important;
}
```
2. If you use numeric hint labels you would normaly not run into the issue with hintlabel. I don't want to add more complexity to the hinting. But you could patch the [hints.js](https://github.com/fanglingsu/vimb/blob/beba6b162c7a199f871061dac217ef6c88b1a598/src/scripts/hints.js#L274-L280) and skip the hiding of hints by given text filter.

**Comment by Docbroke** [comment]
Thanks for the reply
Even with style.css trick applied, colours are still getting inverted for the text of hinted links.

I recently switched from numeric to "asdfglkjh" hint labels, to make it more touch-type friendly, but I think I will go back to numeric hint labels.

**Comment by fanglingsu** [comment]
@Docbroke You're right! The colors are changed depending on the surrounding html element. I did not notice that on the page I tested this.
You could fix this by removing the `background-color` and `color` settings from https://github.com/fanglingsu/vimb/blob/491b3a4b6905b512fa5f1c99bf14260a3c75c79d/src/scripts/hints.css#L13-L19 and recompile vimb.

**Comment by Docbroke** [comment]
Thanks. This now works as expected.
