### ISSUE TITLE
not show media-control-panel

### ISSUE THREAD

**Issue by higowas** [fanglingsu/vimb#549]
not show video and audio media control panel.
https://filepush.co/j6LZ/2019-03-23-144434_1280x1024_scrot.png

**Comment by fanglingsu** [comment]
@higowas Please provide more information about your system `vimb --bug-info` and the url to test the issue. Which version of gstreamer and gst-plugin-* do use use?

**Comment by higowas** [comment]
@fanglingsu

Commit:          unknown
WebKit compile:  2.24.0
WebKit run:      2.24.0
GTK compile:     3.24.7
GTK run:         3.24.7
libsoup compile: 2.66.0
libsoup run:     2.66.0
Extension dir:   /usr/lib/vimb

gstreamer 1.14.4-1

gst-plugins-base 1.14.4-1
gst-plugins-base-libs 1.14.4-1
gst-plugins-good 1.14.4-2
gst-plugins-ugly 1.14.4-1

**Comment by higowas** [comment]
problem occurs in all direct links to audio and video files (for example http://video.com/video.mp4)

**Comment by fanglingsu** [comment]
@higowas Your link redirects to disney for me. But I can reproduce the issue with http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
I'll check if there is a setting in webkit2 which prevents the media controls to be shown. If I make a right click into the video I get a menu with option to toggle media control, but this does not change anything.
May be this is a bug in webkit2.

**Comment by higowas** [comment]
@fanglingsu

thank you.
I did a downgrade webkit2gtk 2.24.0-1 --> webkit2gtk 2.22.7-1
and it worked
