### ISSUE TITLE
Files required for successful build not included in archive

### ISSUE THREAD

**Issue by serussell** [fanglingsu/vimb#553]
The recent 3.4.0 release `Makefile` adds pulling version information from `.git/index`; this file _only_ exists if the project is cloned.  The [release tarball](https://github.com/fanglingsu/vimb/archive/3.4.0.tar.gz), such as used by package maintainers (e.g. Arch) does not include this file, so the project does not build.

To reproduce:

```
wget https://github.com/fanglingsu/vimb/archive/3.4.0.tar.gz
tar -xzf 3.4.0.tar.gz
cd vimb-3.4.0
make
```

Output:

```
make: *** No rule to make target '.git/index', needed by 'version.h'.  Stop.
```

**Comment by pks-t** [comment]
This has been fixed via #552

**Comment by serussell** [comment]
My github issue search skills obviously need improvement.  Sorry for the noise.

**Comment by rti** [comment]
@serussell Also, the aur package is now updated and includes #552.

**Comment by serussell** [comment]
@rti I saw that -- mere minutes after I flagged it as out-of-date.  Awesome, thanks!
