### ISSUE TITLE
Does not work `;o2` command

### ISSUE THREAD

**Issue by andrejlevkovitch** [fanglingsu/vimb#554]
Version:         3.4.0-5-ga58dcb6
WebKit compile:  2.20.5
WebKit run:      2.20.5
GTK compile:     3.18.9
GTK run:         3.18.9
libsoup compile: 2.52.2
libsoup run:     2.52.2
Extension dir:   /usr/local/lib/vimb

### Steps to reproduce
In command mode push `;o2`

### Expected behaviour
I think it have to work like with other values (all other numbers work correctly)

### Actual behaviour
When in command mode I push `;o` and after push 2 (for open second item) I have just `;o2

PS Sorry about my english

**Comment by fanglingsu** [comment]
@andrejlevkovitch Thank you for your report. You are right the `2` does not work for hinting. And I never noticed that. Seems that I never used the second hinted element:)

**Comment by fanglingsu** [comment]
@andrejlevkovitch Sorry I can't reproduce this issue. I've tested on https://www.archlinux.org/ and the second hinted element is the 'Home' in the topmenu which open the same page. If I scroll down or use another page the `;o2` works. On which page did you notice the issue?

**Comment by andrejlevkovitch** [comment]
For example here:

![Screenshot from 2019-04-09 20-43-57](https://user-images.githubusercontent.com/29674023/55822494-642c4680-5b08-11e9-96ef-ff9af786ede0.png)

**Comment by andrejlevkovitch** [comment]
@fanglingsu Also I check for version 3.3.0, and for the version all works correctly. Problem only for version 3.4.0

**Comment by andrejlevkovitch** [comment]
I think problem in commit 6b07416d773e2b48c6904c3590222e01f0a66725, file scripts/hints.js after 425 string - when i change back to previous commit the changes, then all work correctly

**Comment by fanglingsu** [comment]
@andrejlevkovitch That looks strange! Hanve you set some special hintkeys (what is shown if you run `:set hint-keys?` command)? Normally the `2` should not be shown in the inputbox. The keyevent of the `2` should only be given to the hinting to filter the hints by their label if the `2` is part of the set hintkeys. I looks like the `2` is used to filter the elements by their text.

**Comment by andrejlevkovitch** [comment]
`:set hint-keys` output `0123456789`.

**Comment by vabenil** [comment]
Same problem in [](https://duckduckgo.com) I do `;o2` which should focus the inputbox but it doesn't. It worked on previous versions
