### ISSUE TITLE
Commas in Webkit Header List and Brotli Encoding

### ISSUE THREAD

**Issue by hydrocodone-senpai** [fanglingsu/vimb#555]
Here's the output from `% vimb --bug-info`.
```
Version:         3.4.0
WebKit compile:  2.24.1
WebKit run:      2.24.1
GTK compile:     3.24.8
GTK run:         3.24.8
libsoup compile: 2.66.1
libsoup run:     2.66.1
Extension dir:   /usr/local/lib/vimb
```
### Steps to reproduce

1. Add the following line to your config file:
```
au LoadStarted * set header=DNT=1,User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0,Accept='text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',Accept-Encoding='gzip, deflate, br',Accept-Language='en-US,en;q=0.5'
```
2. Inspect your HTTP header either using the Inspector tool or simply visit https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending to check.

### Expected behaviour

According to the vimb manual, surrounding a header option in single quotations should pass the entire option as a string in case there are equal signs present in the option. 

### Actual behaviour

These are the header options vimb sets:
```
ACCEPT = 'text/html
ACCEPT_ENCODING = 'gzip
ACCEPT_LANGUAGE = 'en_US
```
As you can see, each option is cut off right before the subsequent comma in the option. I've tried adding a backslash to pass the comma character. It doesn't work, and just appends a `\` to each header option. 

The fix doesn't seem too hard to implement, since one can pass `=` in a header option, and the lines of code referenced in Issue #363 don't seem too complex. Sadly, I'm only one chapter into K&R (The C Programming Language) so I can't make much of a contribution myself, so I'd greatly appreciate a fix.

**Comment by fanglingsu** [comment]
@hydrocodone-senpai Thank you for reporting this issue. Internal this header line is parsed by [soup_header_parse_param_list](https://developer.gnome.org/libsoup/stable/libsoup-2.4-Soup-Miscellaneous-Utilities.html#soup-header-parse-param-list). This function honors also quoted strings. If you use double quotes instead single quotes the headers should be parsed rigth. E.g. `set header=Accept="text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"`

**Comment by hydrocodone-senpai** [comment]
I had tried that earlier, but for some reason it returned me a string of random text. Take the example screenshot below.
![20190419-214732](https://user-images.githubusercontent.com/44106031/56450684-538c8500-62ed-11e9-81f0-1e948f6dce95.png)

However, after further experimentation, it wasn't the double quotes that had caused this strange output. This is fixed by removing "br" from the Accept-Encoding option. Is it possible for vimb to support brotli encoding in the future? Or is this a limitation of webkit2?

**Comment by fanglingsu** [comment]
Vimb has nothing to do with networking. And as I understand also webkit does not networking stuff. So supporting brotli would be a task of libsoup.
I think it's not a good decission to set the `Accept-Encoding` header by yourself. If webkit/libsoup supports brotli, I'm pretty sure the `AcceptEncoding` header will be sent with the `br`.
