### ISSUE TITLE
gchar failed

### ISSUE THREAD

**Issue by higowas** [fanglingsu/vimb#565]
** (vimb:3194): CRITICAL **: 13:37:49.083: gchar* webkit_uri_for_display(const gchar*): assertion 'uri' failed
fish: “vimb” terminated by signal SIGSEGV (Address boundary error)

**Comment by iamleot** [comment]
Hello higowas,

higowas writes:
> ** (vimb:3194): CRITICAL **: 13:37:49.083: gchar* webkit_uri_for_display(const gchar*): assertion 'uri' failed
> fish: “vimb” terminated by signal SIGSEGV (Address boundary error)

What `vimb --bug-info' says?

Maybe is it a duplicate of #556 fixed via
commit 79c69ba194db0e4ddfb4ff985bc51c3b14ac8dd3?


Thanks!

**Comment by higowas** [comment]
> Hello higowas, higowas writes:
> ** (vimb:3194): CRITICAL **: 13:37:49.083: gchar* webkit_uri_for_display(const gchar*): assertion 'uri' failed fish: “vimb” terminated by signal SIGSEGV (Address boundary error)
> What `vimb --bug-info' says? Maybe is it a duplicate of #556 fixed via commit [79c69ba](https://github.com/fanglingsu/vimb/commit/79c69ba194db0e4ddfb4ff985bc51c3b14ac8dd3)? Thanks!

Version:         3.4.0
WebKit compile:  2.24.2
WebKit run:      2.24.2
GTK compile:     3.24.8
GTK run:         3.24.8
libsoup compile: 2.66.2
libsoup run:     2.66.2
Extension dir:   /usr/lib/vimb
