### ISSUE TITLE
Using whatsapp web

### ISSUE THREAD

**Issue by Docbroke** [fanglingsu/vimb#566]
When I try to access https://web.whatsapp.com/ using vimb, the site tells
[code] Whatsapp works with safari 7.1+
To use whatsapp update safari or use firefox, chrome or opera[/code]

I tried using epiphany with same webkit version, whatsapp-web worked without error. I also tried to change user-agent but I am getting same error with vimb.

**Comment by fanglingsu** [comment]
@Docbroke I can confirm this. But if I do `:set user-agent=googlebot` this site seems to work as I can see. So it might a User-Agent only issue. Maybe you could use the same useragent string like epiphany for die case.

**Comment by Docbroke** [comment]
Thanks. googlebot works. I have tried using user-agent of epiphany, firefox, safari, chrome but all failed. This is surprising. 
There isn't much difference in user-agent of epiphany and default user-agent of vimb as both use same webkit2gtk version. I continue using googlebot as user-agent for now, unless it give some other troubles.
