### ISSUE TITLE
Can't enter input mode in iron-input

### ISSUE THREAD

**Issue by alucryd** [fanglingsu/vimb#568]
$ vimb --bug-info -->
Version:         3.4.0
WebKit compile:  2.24.3
WebKit run:      2.24.3
GTK compile:     3.24.10
GTK run:         3.24.10
libsoup compile: 2.66.2
libsoup run:     2.66.2
Extension dir:   /usr/lib/vimb

Trying to enter input mode in an iron-input input, vimb stays in normal mode. I believe this is the one:  https://www.npmjs.com/package/@polymer/iron-input

Here is the html snippet I'm trying to input in:
```
<iron-input slot="input" class="input-element" id="input-1">
        <input autocomplete="off" placeholder="" autocapitalize="none" autocorrect="off" aria-describedby="paper-input-add-on-1" aria-labelledby="paper-input-label-1">
</iron-input>
```

**Comment by fanglingsu** [comment]
@alucryd I can't reproduce this on https://www.webcomponents.org/element/@polymer/iron-input/demo/demo/index.html. When I click to such an input, vimb switches to input mode.

**Comment by alucryd** [comment]
Thanks for the quick reply, there must be something else then. The particular input I'm trying to use is the login screen from my Home Assistant setup. Could you please give https://hass.alucryd.xyz a try ?

**Comment by fanglingsu** [comment]
@alucryd The home assistant does not work for me. The fileds used for authentication are completely created as Shadow DOM Nodes. The elements could be those that are known in HTML or  like in this example completely custom elements.
Both variante in common - we can't access them from within the page or vimb. Shadow DOM nodes follow their own rules. I don't see any way to get them working right now.

**Comment by alucryd** [comment]
Thanks for the analysis ! I'll stick to epiphany for now then, looks like new web standards are a pain after all.

**Comment by jonnieey** [comment]
Hey, cannot enter insert mode in  [chatgpt](https://chat.openai.com/chat)
```> vimb --bug-info
Version:         3.7.0-1-ge442041
WebKit compile:  2.40.1
WebKit run:      2.40.1
GTK compile:     3.24.37
GTK run:         3.24.37
libsoup compile: 3.4.2
libsoup run:     3.4.2
Extension dir:   /usr/lib/vimb
```

**Comment by jonnieey** [comment]
> Hey, cannot enter insert mode in  [chatgpt](https://chat.openai.com/chat)
> ```> vimb --bug-info
> Version:         3.7.0-1-ge442041
> WebKit compile:  2.40.1
> WebKit run:      2.40.1
> GTK compile:     3.24.37
> GTK run:         3.24.37
> libsoup compile: 3.4.2
> libsoup run:     3.4.2
> Extension dir:   /usr/lib/vimb
> ```
> ```
> <textarea id="prompt-textarea" tabindex="0" data-id="root" rows="1" 
>     placeholder="Send a message" 
>     class="m-0 w-full resize-none border-0 bg-transparent p-0 pr-10 focus:ring-0 
>            focus-visible:ring-0 dark:bg-transparent md:pr-12 pl-3 md:pl-0" 
>     style="max-height: 200px; height: 21px; overflow-y: hidden;">I</textarea>
>  div contenteditable="plaintext-only">I</div><div pseudo="placeholder">Send a message</div>
> ```
> 
> > Shadow DOM nodes follow their own rules. I don't see any way to get them working right now.
> 
> It seems it also uses the shadow DOM.

Was able to overcome this by entering into passthrough mode. incase somebody has same problem
