### ISSUE TITLE
Has anyone thought about doing a VimB RPM for Fedora?

### ISSUE THREAD

**Issue by philiprhoades** [fanglingsu/vimb#569]
Pretty much as the subject says . . 

Thanks for this great software!

Phil.

**Comment by fanglingsu** [comment]
@philiprhoades There are packages for some distributions but I think most of the users compile vimb from source instread of using as package, but I could be wrong.

**Comment by AloisMahdal** [comment]
I pretty much thought about it.  I might even have had something on COPR. (Can't check now, it seems to be out.)

But then again, vimb compiles faster than you say `vimb.spec` so...

**Comment by philiprhoades** [comment]
Alois,


On 2019-08-02 13:09, Alois Mahdal wrote:
> I pretty much thought about it. I might even have had something on
> COPR. (Can't check now, it seems to be out.)
> 
> But then again, vimb compiles faster than you say vimb.spec so...


Yes, it hardly seems worth the effort but I guess from my point of view 
it might be a nice / good / convenient exercise to get familiar with the 
RPM packaging process . . and vimb might also be exposed to some more 
people?

I might give it a go . .

Regards,

Phil.
-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au
