### ISSUE TITLE
Movement between Tabs?

### ISSUE THREAD

**Issue by philiprhoades** [fanglingsu/vimb#570]
People,

Maybe I'm blind but I can't in the help / docs how I move between tabs in vimb . . 

Thanks,
Phil.

**Comment by iamleot** [comment]
Hello philiprhoades, 

philiprhoades writes:
> [...]
> Maybe I'm blind but I can't in the help / docs how I move between tabs in vimb . . 
> [...]

This depends on the program/tool used for the tabs.  What program are
you using for that?

If tabbed is used, by default Ctrl-Shift-h and Ctrl-Shift-l permits to
move to the previous/next tabs.

Ad-hoc keybinding to vimb could be used too, e.g. to map `Ctrl-p' and `Ctrl-n'
in vimb to move to the previous/next tabs you can add something like
that in ~/.config/vimb/config:

 nnoremap <C-N> :sh! xdotool key --window "${VIMB_XID}" ctrl+shift+l<CR><Esc>
 nnoremap <C-P> :sh! xdotool key --window "${VIMB_XID}" ctrl+shift+h<CR><Esc>

**Comment by philiprhoades** [comment]
@iamleot ,

Thanks for the fast response!

I did not have tabbed installed so I installed it - I coudn't get it to work with vimb it but it seems that using it adds an extra layer between the xterm and vimb anyway - which I would prefer to avoid . .

Also, I tried the remapping - which I also could not get to work - the syntax seems to imply that the tabbed environment is already working . . 

So am I correct in assuming that vimb does not manage its own tabbing and that tabs are not displayed somewhere on the vimb screen anyway?

**Comment by iamleot** [comment]
philiprhoades writes:
> So am I correct in assuming that vimb does not manage its own tabbing and that tabs are not displayed somewhere on the vimb screen anyway?

Yes, that's right.
