### ISSUE TITLE
private-browsing not found message after upgrade

### ISSUE THREAD

**Issue by serussell** [fanglingsu/vimb#571]
### Summary

After upgrading the `vimb` package on Arch, I get an error that the `private-browsing` config option is not found (it is in my config).  It's also not available when trying to manually set it via the command prompt.

### Debug info

| | |
| --- | --- |
| Version |         3.5.0 |
| WebKit compile | 2.24.3 |
| WebKit run |      2.24.3 |
| GTK compile |     3.24.10 |
| GTK run |         3.24.8 |
| libsoup compile | 2.66.2 |
| libsoup run |     2.66.2 |
| Extension dir |   /usr/lib/vimb |

And also (trimmed to best guess at relevancy):

| | |
| --- | --- | 
|Name            | vimb|
|Version         | 3.5.0-1|
|Architecture    | x86_64|
|Depends On      | webkit2gtk|
|Packager        | Maxime Gauduin <alucryd@archlinux.org>|
|Build Date      | Thu 01 Aug 2019 02:26:55 PM CDT|
|Install Date    | Mon 12 Aug 2019 12:46:28 PM CDT|
|Validated By    | Signature|

![2019-08-12-163157_427x166_scrot](https://user-images.githubusercontent.com/504337/62902569-a0291f80-bd25-11e9-9398-29b83ad2fd9f.png)

**Comment by fanglingsu** [comment]
@serussell Yes, this option was removed in c9a7950ae4d76bfd77a389faf3a3ec81490522ea. The private browsing was not really private and vimb still wrote data to files in config dir. So use the `-i` or `--incognito` command line option if you prefer to not leave traces on file system.

**Comment by serussell** [comment]
So, there's no way to enable incognito by default anymore? I liked that no cookies were persisted, or shared between windows.

To get that same level of privacy, do I have to always run every seaxiom with ˋ-iˋ? How do I get the behavior that windows opened with ˋtabopenˋ and ˋopenˋ don't have access to cookies from the parent window?

**Comment by serussell** [comment]
For anyone who comes across this, to get the same behavior as before the patch, do the following (instructions for Linux):

```
sqlite3 ~/.config/vimb/cookies.db 'delete from moz_cookies;'
chmod ugo-w ~/.config/vimb/cookies.db
```

`vimb` uses the database to share state, so forcing it to not be able to write to the DB will prevent it from leaking cookies between windows.

**Comment by fanglingsu** [comment]
@serussell Thank you for providing this workaround. But I think it would be easier to put a little script into the `PATH` called instead of vimb to run it with `-i` or maybe a shell alias would work too.
