### ISSUE TITLE
the editor is not showing

### ISSUE THREAD

**Issue by nsklaus** [fanglingsu/vimb#572]
```
$ vimb --bug-info
Version:         3.5.0
WebKit compile:  2.24.3
WebKit run:      2.24.3
GTK compile:     3.24.10
GTK run:         3.24.10
libsoup compile: 2.66.2
libsoup run:     2.66.2
Extension dir:   /usr/lib/vimb
```
### Steps to reproduce
visit any page, press 'gf' to open page source in text editor.

### Expected behaviour
i expected my text editor (neovim) to pop up and show me the source of the web page.

### Actual behaviour
nothing happens.

i used strace to attach it to vimb process, and saw the when i press 'gf' this happens:
openat(AT_FDCWD, "/tmp/vimb-0IJN6Z", O_RDWR|O_CREAT|O_EXCL, 0600) = 22

that file contains the source of the web page. so that's correct, but for some reason, vimb create it but doesn't open it. in previous version it worked fine though. idon't know if it's vim that is missing something or me that forgot to set a variable or setting, or i don't know. i'm currently testing a new distro (arch based) maybe something is different with it, or their vimb package did something strange. i'm not sure.
my terminal variable is set to 'st', like so: `$TERMINAL=st`
in vimb i also did: `:set editor-command=nvim`
also, in previous version, RMB on a page showed in the context menu an entry for 'source', and it isn't there anymore. the contextual menu shows up but there is no 'source'.

here's my whole vimb config:
```
# path
set download-path=/home/klaus/Downloads/

# home
set home-page=file:///home/klaus//Documents/bookmarks_aug-10-2019.html

# no javascrapt
set scripts=false

# shortcuts
nnoremap b :open !
nnoremap B :tabopen !
nnoremap d :quit<CR>
nnoremap D :quit!<CR>
nnoremap x :set scripts!|no! R<CR>
nnoremap c :set stylesheet!|no! R<CR>
nnoremap h <C-O>
nnoremap l <C-I>

# zoom in, out, reset
nmap + zI
nmap - zO
nmap = zz

# hide inputbox if it contains no text
set input-autohide=true

# use custom css
set stylesheet=false

# tab key to cycle elements on page
set tabs-to-links=true

# use mpv for videos
set x-hint-command=:sh! mpv <C-R>;

# use webgl
set webgl=on

```

**Comment by iamleot** [comment]
Hello nsklaus, 

nsklaus writes:
> [...]
> ### Steps to reproduce
> visit any page, press 'gf' to open page source in text editor.
>
> ### Expected behaviour
> i expected my text editor (neovim) to pop up and show me the source of the web page.
>
> ### Actual behaviour
> nothing happens.
> [...]
> that file contains the source of the web page. so that's correct, but for some reason, vimb create it but doesn't open it. in previous version it worked fine though. idon't know if it's vim that is missing something or me that forgot to set a variable or setting, or i don't know. i'm currently testing a new distro (arch based) maybe something is different with it, or their vimb package did something strange. i'm not sure.
> my terminal variable is set to 'st', like so: `$TERMINAL=st`
> in vimb i also did: `:set editor-command=nvim`
> [...]

Is nvim a graphical editor (e.g. an X11 one) and its process start and
end when you save the file or quit the editor?  If that's not the case
probably it try to invoke `nvim' but then fails because input/output is
not a terminal.

Does setting:

 :set editor-command=st -e nvim

(or something similar) works?

**Comment by nsklaus** [comment]
thanks for the suggestion, i just tried.
this time the editor open up when i press 'gf', but it's empty, there's nothing in it.
nvim is neovim, it's a vim clone, it is terminal based, just like vim.

**Comment by iamleot** [comment]
Sorry for accidentally omitting `%s`!  Yes it's needed.

IIUC previously showing the source code was directly part of WebKit API but is not anymore in WebKit 2 API and so browsers needs to implement them.  That's probably why there isn't anymore a "source" in popup contextual menu.

**Comment by nsklaus** [comment]
@iamleot
alright, mystery solved then, thank you for your help.
i'm closing the issue now.
