### ISSUE TITLE
how to do redirects with vimb ?

### ISSUE THREAD

**Issue by nsklaus** [fanglingsu/vimb#574]
$ vimb --bug-info
Version:         3.5.0
WebKit compile:  2.24.3
WebKit run:      2.24.3
GTK compile:     3.24.10
GTK run:         3.24.10
libsoup compile: 2.66.2
libsoup run:     2.66.2
Extension dir:   /usr/lib/vimb

is it possible to do redirects in vimb ?
for example i'd like to redirect all link 'reddit.com' to 'old.reddit.com'. i cannot find a way to do this, is this possible at all? 
is there some kind of compatibility with other webkit2 based browsers extensions ?

**Comment by iamleot** [comment]
Hello nsklaus, 

nsklaus writes:
> [...]
> is it possible to do redirects in vimb ?
> for example i'd like to redirect all link 'reddit.com' to 'old.reddit.com'. i cannot find a way to do this, is this possible at all? 
> is there some kind of compatibility with other webkit2 based browsers extensions ?
> [...]

I think you can do that via `au', e.g. to redirect from twitter.com to
mobile.twitter.com here I have:

         au LoadFinished *://twitter.com/* eval! userscript_twitter();

...where userscript_twitter() is defined in ~/.config/vimb/script.js as:

         function userscript_twitter()
         {
                 if (window.location.href.search('://twitter.com/') != -1) {
                         window.location.href = window.location.href.replace('://twitter.com/', '://mobile.twitter.com/');
                 }
         	
         	/* other code here unrelated to URL rewriting */
         }

**Comment by nsklaus** [comment]
thank you for the answer,
would there be a way to enable javascript but only for local scripts ?
i tend to browse the web with javascript completely disabled.
i toggle in on when i need it on rares occasion.

also should i close the previous issue myself ? (about the editor not showing up, or should i let it open ?

**Comment by iamleot** [comment]
nsklaus writes:
> thank you for the answer,
> would there be a way to enable javascript but only for local scripts ?
> i tend to browse the web with javascript completely disabled.
> i toggle in on when i need it on rares occasion.
>

At least what I have shared should work also with javascript disabled
(that should apply to all local scripts or similar in vimb AFAIK)

> also should i close the previous issue myself ? (about the editor not showing up, or should i let it open ?
>

If the problem is solved I guess so, but doesn't seem so IIUC (it would
be worth to investigate why nvim is opened but no file is viewed...).

**Comment by iamleot** [comment]
Regarding the editor issue, I missed your edits and sounds like that the main problem was addressed and if for you it's okay probably the issue could be closed.

Thanks!

**Comment by nsklaus** [comment]
i'm colising this issue too then,
redirect works well using the method you've shown me.
i'm using it for reddit -> old.reddit, and youtube -> invidio.us
tthank you
