### ISSUE TITLE
style.css changes persists even when the file is not there anymore

### ISSUE THREAD

**Issue by nsklaus** [fanglingsu/vimb#575]
$ vimb --bug-info
Version:         3.5.0
WebKit compile:  2.24.3
WebKit run:      2.24.3
GTK compile:     3.24.10
GTK run:         3.24.10
libsoup compile: 2.66.2
libsoup run:     2.66.2
Extension dir:   /usr/lib/vimb

### Steps to reproduce
i created a file style.css, as described on vimb's site, for applying dark theme.
it worked well, and the supplied dark theme is quite nice.
after a while though, i decided i don't alway want the dark theme applied. 
so, i renamed the file to `~/.config/vimb/style--.css`.
and the dark theme was mostly gone. mostly but not totaly, html forms and button are still rendered in black. what's worse the input fields are using black font on black background now.
please see attached screenshot 

### Expected behaviour
after removing the style.css file, i expected vimb to completely revert back to normal colors. 

### Actual behaviour
vimb somehow kept some of the theme values for certain html widgets (buttons, forms..)

here's a screenshot, showing vimb after the file style.css is no longer accessible to it.
buttons and text areas shouldn't have stayed dark. ( i restarted the browser many times since then. it doesn't help)
![vimb-theme](https://user-images.githubusercontent.com/6810861/63983292-5b8fd900-cac6-11e9-98b7-c43c4a9cdb28.png)

**Comment by fanglingsu** [comment]
@nsklaus This looks strange. I'd suggest to not move the file but to toggle evaluation of it by `:set stylesheet!` which can be bound via `nmap` like `nnoremap ss :set stylesheet!<CR><Esc>`.
Do the button look normal if you reload the page by `R` (without using cache)?

**Comment by nsklaus** [comment]
@fanglingsu,
thanks for the reply, i renamed the file to just "style.css', made a toggle like so:
`nnoremap c :set stylesheet!|no! R<CR>`
now when i press 'c' i have the theme being toggled on and off. that part works fine.
the forms color and button color problem are still there though.
even when the theme is disabled, i still get some widgets colored in dark.
even with reloading without cache (R), even if i restart the browser.
i also tried to without compton or xcompmgr too. all the same. some widget stays dark, for some reason.

**Comment by nsklaus** [comment]
ok, i've found the problem, it's my fault.
it's really simple and i feel a bit stupid.
i had in ~/.config/gtk-2.0 and gtk-3.0 stuffs that were causing this.
since i use i3, st, and mostly terminal based apps all the time, i had completely forgot about those.
they where probably sitting there since i installed the system.
after initial install, i removed xfce4 and display manager and all thoses stuffs like i usualy do and didn't notice there was remants configs i needed to remove.
sorry for the disturbance.

**Comment by fanglingsu** [comment]
@nsklaus Nice to hear that you solved it. I did not know that it is possible to style parts of the webview via gtk styles.
