### ISSUE TITLE
"Inspect Element" error

### ISSUE THREAD

**Issue by 0xD3BD** [fanglingsu/vimb#577]
Version:         3.5.0-3-g9241283
WebKit compile:  2.26.1
WebKit run:      2.26.1
GTK compile:     3.24.10
GTK run:         3.24.10
libsoup compile: 2.68.1
libsoup run:     2.68.1
Extension dir:   /usr/local/lib/vimb

### Steps to reproduce
The first click did not respond, the second click popped up with an error message.

### Expected behaviour
Normally pop up the Inspect element window.

### Actual behaviour
Popup error message.
![10-03-1570087326_1270x1361](https://user-images.githubusercontent.com/17524858/66106843-71c31480-e5f1-11e9-8e65-e73468b8df65.png)

**Comment by fanglingsu** [comment]
@0xD3BD I can confirm this. I think this is an issue in webkit 2.26.1 because the inspect elements worked until a fey days ago.

**Comment by fanglingsu** [comment]
This is a bug in webkit 2.26.1 ([Bug 202321](https://bugs.webkit.org/show_bug.cgi?id=202321)) so we can't do anything from within vimb to fix it.
