### ISSUE TITLE
Web Inspector doesn't open and causes error

### ISSUE THREAD

**Issue by Koxiaet** [fanglingsu/vimb#578]
Version:         3.5.0
WebKit compile:  2.24.3
WebKit run:      2.26.0
GTK compile:     3.24.10
GTK run:         3.24.11
libsoup compile: 2.66.2
libsoup run:     2.66.2
Extension dir:   /usr/lib/vimb

### Steps to reproduce

Open vimb, and open a website. Press gF, and nothing happens. Continuing to press it sometimes logs `Error sending IPC message: Broken pipe` to stdout. webinspector is set to true. Right-clicking and selecting Inspect Element makes this appear on the bottom page:

#### This page contains the following errors:

    error on line 43 at column 8: Opening and ending tag mismatch: link line 0 and head

#### Below is a rendering of the page up to the first error:

WI.sharedApp = new WI.AppController; WI.sharedApp.initialize();

**Comment by fanglingsu** [comment]
@Koxiaet This issue is a duplicate to #577. This issue is cause by https://gitlab.freedesktop.org/xdg/shared-mime-info/commit/8ae13a589577e9bda12fb16465a03cd81b1cd349 in shared-mime-info so wan cant do anything in vimb to fix it. We have to wait for a fin in shared-mime-info.
