### ISSUE TITLE
Option to turn off link text-based follow?

### ISSUE THREAD

**Issue by daviwil** [fanglingsu/vimb#581]
Hi @fanglingsu,

Thanks so much for making vimb, it's such a nice browser!  One thing that has been a little hard to get used to after moving over from Qutebrowser is that the follow hinting also includes the link text on the page.  I wanted to have letter-based hint keys like I was used to from Qutebrowser but once I configured vimb to use them, I constantly had conflicts with link text in sites, leading me to navigate to places I didn't intend to go pretty often.  This also can be a problem with numeric labels on sites like GitHub.

Is there any chance a setting could be added to disable link text-based follow for those who would prefer to live without it?  Would there be a significant loss of functionality if it was turned off?

I'd certainly be interested to contribute this change to the project if you think it's worthwhile.

Thanks!

```
$ vimb --bug-info
Version:         3.5.0
WebKit compile:  2.26.2
WebKit run:      2.26.2
GTK compile:     3.24.10
GTK run:         3.24.10
libsoup compile: 2.68.2
libsoup run:     2.68.2
Extension dir:   /gnu/store/ci9ryrd27xky0z5bl5812zzmhg1i9mvr-vimb-3.5.0/lib/vimb
```

**Comment by fanglingsu** [comment]
@daviwil If you have `:set hint-keys=...` to switch to letter based hinting? In this case only chars that are not used in the hint labels are used to filter hints by the link text. Or do you want to disable lookup by linktest completely?

**Comment by daviwil** [comment]
I'd like to disable it completely.  When I set `hint-keys` to letters, I still hit collisions between letters in hint labels and letters in the link text.

**Comment by fanglingsu** [comment]
@daviwil I've added a new setting 'hint-match-element' which is true by default. If you set it to false your typed chars are not used to filter the hints as long as they are not part of the hints-keys.

**Comment by daviwil** [comment]
Thanks so much for adding that!  I'll try it out later today and let you know it goes.

**Comment by daviwil** [comment]
Couldn't resist, just cloned and compiled the code; the new setting works perfectly!  Any chance of a new release in the near future?

**Comment by daviwil** [comment]
Closed the issue accidentally while playing with hints :)  This issue is fixed now so I'll legitimately close the issue this time.
