### ISSUE TITLE
Cache/data files in `$XDG_CONFIG_HOME`

### ISSUE THREAD

**Issue by thunktone** [fanglingsu/vimb#582]
I just found my browsing history, cookies etc in `~/.config/vimb`. They really belong in `$XDG_CACHE_HOME` or possibly `$XDG_DATA_HOME`. Fortunately I spotted this before commiting the files to my config git repository. Please change this before someone accidentaly publishes their browsing history on github or something. See [freedesktop basedir spec](specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by fanglingsu** [comment]
@thunktone You are right. `$XDG_CONFIG_HOME` is the wrong place used since the early days of vimb. I'll try to move all files except of `config`, `style.css`, `scripts.js` and `bookmark` to `$XDG_DATA_HOME/vimb/[PROFILE/]`.

**Comment by herrsimon** [comment]
A related suggestion: I think it would be very useful to add options for specifying the paths and filenames for all files individually, either just via the command line when calling vimb (analogously to '--config') or optimally as settings, so that the files can be changed dynamically. This would in particular be very nice for the style.css and script.js files, which could then be changed via auto-commands, depending on the URI.

**Comment by iamleot** [comment]
I think that issue should be reopened (it is not really stale, just not worked on).

**Comment by fanglingsu** [comment]
I'm not sure which files belong to config, data or to cache directory. I see the files as configuration that I inspect and edit with editor - except of the cookies.db.

**Comment by iamleot** [comment]
IMHO:

 - `config`, `script.js` and `style.css` should be under `XDG_CONFIG_HOME`
 - all other files (`cookies.db`, `closed`, `history`, `bookmark`, `command`, `queue` and `search`) under `XDG_DATA_HOME`

**Comment by fanglingsu** [comment]
Like @iamleot suggested the config, script.js and style.css are kept in `$XDG_CONFIG_HOME` all other files are now in `$XDG_DATA_HOME`. Files are not moved automaticallyand should therefor moved from config to data home e.g. by
```
mv $XDG_CONFIG_HOME/vimb/{bookmark,closed,command,cookies.db,history,queue,search} $XDG_DATA_HOME/vimb
```

**Comment by iamleot** [comment]
Thank you @fanglingsu!
