### ISSUE TITLE
x-hint-command broken on some search engine links

### ISSUE THREAD

**Issue by Midek** [fanglingsu/vimb#584]
```
vimb --version
vimb, version 3.5.0-18-g1d81da7
```

I am trying to run hinted url in mpv player.
My x-hint-command is set to:
```
set x-hint-command=:sh! /usr/bin/mpv <C-R>;
```

For example, when going to:
https://www.youtube.com/results?search_query=asdf
selecting `;x` and following first link, the player starts properly.

### Steps to reproduce
Unfortunately, when i search for the same phrase in google (javascript disabled):
https://www.google.com/search?q=asdf
and try to use `;x` hints to open first youtube link it fails.

The command im getting in inputbox looks like this:
```
:sh! /usr/bin/mpv https://www.google.com/url?q=https://www.youtube.com/watch%3Fv%3DLJnpwL-2Drc&sa=U&ved=2ahUKEwj9ntChpNzmAhWDzYUKHbOrC80QtwIwAnoECAQQAQ&usg=AOvVaw0aHhG4zFCiM8qIVCOLF-r2
```

Expected result would be for mpv to start playing, since using the same command in terminal does work.

### Actual behaviour
My suspicion is that vimb resolves % as current url (?) and in the end im passing wrong parameter to the shell.
I tried wrapping <C-R>; in "" and '' but it does not help.

**Comment by fanglingsu** [comment]
@Midek Thank your for reporting this bug. I can reproduce this. By setting `:set x-hint-command=:sh echo <C-R>;`. If I X-hint the video I get an URL like `:sh echo https://www.google.com/url?q=https://www.youtube.com/watch%3Fv...` after pressing enter I get following from the shell `https://www.google.com/url?q=https://www.youtube.com/watchhttps://www.google.com/search?...`.

You are right, the `%` is replaced by current URI during parsing of the right hand side of the shell command.
I'll try to escape the `%` as `%%` before the `:sh` command is prepared.

**Comment by fanglingsu** [comment]
@Midek I've remove the '%' to current URL expansion in general so the x-hint-comand should now work like expected. Please close the issue if it works for you.

**Comment by Midek** [comment]
Yes, looks like its fixed now, thank you very much.
