### ISSUE TITLE
feature request: make hardcoded keybindings customizable

### ISSUE THREAD

**Issue by herrsimon** [fanglingsu/vimb#585]
Hello,

first of all, thanks a lot for providing vimb, it finally saved me from the bloated mainline browser hell! There is one thing missing which would make it perfect: Would it be possible to make the hardcoded keybindings (navigation, hinting etc.) easily customizable, so that for example one could use other keys than ctrl-o/ctrl-i to move forward/backward? Just remapping these other keys to ctrl-o/ctrl-i would unfortunately not be sufficient as this limits the available keys. For example, the keys 'r', 'f', '^' and '$' can never be remapped to do anything else without losing the original functionality.

Two options come to mind:

a) provide the currently hardcoded functionality as user-callable commands (so that the default keybindings can be provided as simple mappings to 'scroll', 'open_register', 'navigate' commands etc.). This would be most flexible and clean but maybe overkill and not quick to implement.

b) define all hardcoded keybindings in some header file, where they can easily be modified before compiling. This should be quick to implement.

Thanks a lot in advance!

**Comment by fanglingsu** [comment]
@herrsimon I think vimb works like vim in this case. That means there is a set of hard coded key bindings you can remap. In fact that are not key bindings but commands that consists only of one or two keys.
I don't have time or interest in changing the way the keys are processed.

**Comment by fanglingsu** [comment]
@herrsimon I do not understand what you mean with the

> For example, the keys 'r', 'f', '^' and '$' can never be remapped to do anything else without losing the original functionality.

You should already be able to remap those keys too. E.g.
```
# remap r to do something else - scroll a little in this case
:nnoremap r 5j
# add new key for the reload
:nnoremap u r
```
With this the `r` is now remapped to do something else and the original functionality is done by `u`.

**Comment by herrsimon** [comment]
Sorry for the late reply, your last answer provides exactly the functionality I was looking for, thanks a lot! Apparently  I don't completely understand the nnoremap command and therefore should learn a bit more about it.
