### ISSUE TITLE
[bug?] x-hint-command not set when sourced from file

### ISSUE THREAD

**Issue by herrsimon** [fanglingsu/vimb#586]
Version:         3.5.0-18-g1d81da7
WebKit compile:  2.26.2
WebKit run:      2.26.2
GTK compile:     3.24.13
GTK run:         3.24.13
libsoup compile: 2.68.3
libsoup run:     2.68.3
Extension dir:   /usr/lib/vimb
### Steps to reproduce
a) start vimb with config containing
``set x-hint-command=:sh! mpv --ytdl <C-R>;<CR>``
b) start vimb with config containing
``source /path/to/somefile``
where somefile contains exactly the line as in a)
### Expected behaviour
If I understand correctly, in both scenarios selecting a video link with ;x should play it in mpv
### Actual behaviour
a) works flawlessly, in b), the x-hint-command is not changed and remains at its default value ``:o <C-R>;`` (checked with ``:set x-hint-command?``). It will also not change when manually issuing ``:source /path/to/somefile`` in a running browser session.

A related question: Is it possible to directly map a single key, say ``m``, so that pressing it sets the x-hint-command as above AND starts x-hint-mode?

**Comment by fanglingsu** [comment]
@herrsimon Thank you for the issue! I can reproduce this. Setting during runtime or by option `--cmd 'set x-hint.comand=...'` works, but from file it does not.

**Comment by herrsimon** [comment]
I actually checked with a config file just containing one line with the x-hint-command and the problem was very simple: There was no empty line at the end of the file (i.e. no newline character at the end of the line with the x-hint-command), so vimb did not read the line. With the newline character everything works as expected now. Sorry for this.

**Comment by fanglingsu** [comment]
@herrsimon Thank you for this information - I'll try to avoid these issues in future that are caused by missing newline in config file.

**Comment by herrsimon** [comment]
@fanglingsu ...or you can simply add to the documentation that configuration files (probably the same is true for scripts.js and style.css) need to end with an empty line

**Comment by fanglingsu** [comment]
@herrsimon If fixed the loading of the config so that is does not discard the normally empty last line. If never seen this, because vim normally adds this newline to the file.
