### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by daviwil** [fanglingsu/vimb#587]
Happy new year! Is there any chance that a new release will be cut soon? Lots of nice new features have been added since the last release. I'd love to get them packaged up in the GNU/Linux distro I use (Guix).

Thanks!

**Comment by fanglingsu** [comment]
@daviwil Your request was the decisive factor for me to make the release  https://github.com/fanglingsu/vimb/releases/tag/3.6.0

**Comment by daviwil** [comment]
Awesome, thanks so much, looking forward to using all the new improvements!
