### ISSUE TITLE
feature request: support POST requests

### ISSUE THREAD

**Issue by herrsimon** [fanglingsu/vimb#590]
It would be a nice addition to vimb to support POST requests, something like ``:post URI key1=value1 [key2=value2 ...]``. 

In my case, I need to access the results of some search forms over and over again, which is currently automated by letting curl do the POST request and then open the returned page with vimb. Just binding ``:post ... <CR>`` to some key would be much easier...

**Comment by fanglingsu** [comment]
@herrsimon I do not understand the reason to do POST-Requests this complicated?

1. If I'd like to do repeated POST-Requests I'd write a little HTML file with prefilled form that posts to the desired URI. This could also be crafted by some JS to submit the form if the DOM is loaded. You could also bind this to something like `:nnoremap P :o file:///home/herrsimon/fake-post.html<CR>` or so.
2.Or you add a function to `scripts.js` file that performs the POST Request.

**Comment by herrsimon** [comment]
of course, you are completely right, I did not think about this. Thanks for pointing it out.
