### ISSUE TITLE
feature request: make current selection available to shell scripts

### ISSUE THREAD

**Issue by herrsimon** [fanglingsu/vimb#592]
It would be useful to make the current selection (if any) available to shell scripts, for example via ``$VIMB_SELECTION``.

**Comment by fanglingsu** [comment]
@herrsimon That sound interesting! I think we could grab the selection content if a `:sh` command is started and set it as environment variable.

**Comment by fanglingsu** [comment]
@herrsimon I've added setting of the `$VIMB_SELECTION` env var if `:shellcmd` is called. Please close this issue if this work for you.

**Comment by herrsimon** [comment]
works like a charm, thanks for the super quick implementation!
