### ISSUE TITLE
feature request: avoid white views when dark-mode is on.

### ISSUE THREAD

**Issue by c0dev0id** [fanglingsu/vimb#594]
Vimb 3.6.0 introduces the dark-mode, which is great! However, when starting vimb with a page, it first shows a grey background, then white, then dark.

Reproduce: 
Execute "vimb https://codevoid.de" (or any other page with a dark background).
It also happens on `:tabopen`.

I'm not sure if this can be influenced (because webkit...). But it would be great it these initial views could be a dark grey when dark-mode is on.

Best Regards,
Sdk

**Comment by fanglingsu** [comment]
@c0dev0id Thank you for the issue. I'll see why this white background is rendered.

**Comment by fanglingsu** [comment]
@c0dev0id I can reproduce the issue by `vimb -C 'set dark-mode=on' https://codevoid.de/`. But in my case I see it white and than dark. Not sure, but one part for color changing might be the `$XDG_CONFIG_HOME/vimb/style.css` file. If you empty this you should see only white and dark.
I've to dig deeper to get the reason for the initial white - maybe the gtk renders the window before the config changes are applied or something like that.

**Comment by c0dev0id** [comment]
@fanglingsu Correct, I have a `style.css`, but I'm only styling hints, no page background color.

Hmm. I can influence the first (grey) screen with the GTK theme. The second white one is still there even without style.css...

Video: https://codevoid.de/9/p/vimbdarkmode.mp4

I removed style.css before recording this. Eventually related is the fact that I'm using a Thinkpad x230, which is a bit dated (but perfectly fine for my tasks).

**Comment by MichaelMackus** [comment]
I've added a PR that fixes this in #781 - I got vimb setup with a lovely solarized dark theme, and this flashing was really annoying me. It is a pretty simple patch you just need to update your config.h and re-compile.
