### ISSUE TITLE
Question: Does vimb do something with USB or Audio on start/page-reload?

### ISSUE THREAD

**Issue by c0dev0id** [fanglingsu/vimb#595]
Hello,

I have a question. I'm using vimb on OpenBSD. It works great, but there is one little itch I don't understand. I'm listening to music using a USB soundcard. Whenever vimb loads/reloads a page, the sound stutters/skips a little bit. It only happens when using a USB soundcard, the internal one works fine during those events.

I've tested the same with chrome, firefox, luakit (webkit), ephipany (webkit). Only vimb triggers this behavior.

Does vimb do some sound or USB initialization during start / reload which could trigger something like this?

The issue is not new and happens in earlier versions too.
But here is the bug-info:

> vimb --bug-info
Version:         3.6.0
WebKit compile:  2.26.2
WebKit run:      2.26.2
GTK compile:     3.24.13
GTK run:         3.24.13
libsoup compile: 2.68.3
libsoup run:     2.68.3
Extension dir:   /usr/local/lib/vimb

Best Regards,
Sdk

**Comment by fanglingsu** [comment]
@c0dev0id There is no sound logic within vimb and also no logic that does something intentional with USB devices. But might be a webkit2 issue that does only vimb.

**Comment by c0dev0id** [comment]
Ok, thanks for the clarification. The hunt continues :) In case I find something, I let you know.
