### ISSUE TITLE
Question: augroup to modify URL?

### ISSUE THREAD

**Issue by c0dev0id** [fanglingsu/vimb#596]
Hello,

I would like to change URLs before they are opened. For example whenever I click or enter www.reddit.com/..., I want it to be changed to old.reddit.com/....

I played with augroup on LoadStarting and I can do something like `!sh echo "$VIMB_URI" | sed ...` but I'm not able to execute `:open` on the result.

Is this something that is possible at all?

Best Regards,
Sdk

**Comment by iamleot** [comment]
Hello @c0dev0id!
I do the following, e.g. to access https://mobile.twitter.com/ URLs instead of https://twitter.com/, in `~/.config/vimb/config` I have:

````
augroup kludges
        [...]
        au LoadFinished *://twitter.com/* eval! userscript_twitter();
        [...]
augroup end
````

...and then in `~/.config/vimb/scripts.js`:

````
[...]
function userscript_twitter()
{
        if (window.location.href.search('://twitter.com/') != -1) {
                window.location.href = window.location.href.replace('://twitter.com/', '://mobile.twitter.com/');
        }

        [...]
}
[...]
````

**Comment by c0dev0id** [comment]
Ah, via JS!

Thanks a ton! @iamleot

Best Regards,
Sdk
