### ISSUE TITLE
Problems with rendering some websites

### ISSUE THREAD

**Issue by steview2000** [fanglingsu/vimb#597]
Version:         3.6.0-6-ge58d6e7
WebKit compile:  2.26.2
WebKit run:      2.26.2
GTK compile:     3.24.5
GTK run:         3.24.5
libsoup compile: 2.64.2
libsoup run:     2.64.2
Extension dir:   /usr/local/lib/vimb

### Steps to reproduce
Try to open reddit.com

### Expected behaviour

Website opens and scrolling is possible. 

### Actual behaviour

Website is loaded to 89% and stops without an error.

This might be a webkit-error, since Midori and the surf-browser (suckless) show very similar behaviour. However qutebrowser works fine, so maybe there exists a workaround. Midori, surf and qutebrowser are from the the Debian-stable repositories. I have compiled vimb from source against the webkit-packages provided by Debian-stable.

**Comment by iamleot** [comment]
Hello steview2000, 

steview2000 writes:
> [...]
> This might be a webkit-error, since Midori and the surf-browser (suckless) show very similar behaviour. However qutebrowser works fine, so maybe there exists a workaround. Midori, surf and qutebrowser are from the the Debian-stable repositories. I have compiled vimb from source against the webkit-packages provided by Debian-stable.
> [...]

AFAIK qutebrowser uses QtWebKit or QtWebEngine (not WebKitGTK).

I have tried to reproduce that problem by scrolling
https://www.reddit.com/ but unfortunately it seems that works fine here:

 % vimb --bug-info
 Version:         3.6.0
 WebKit compile:  2.26.2
 WebKit run:      2.26.2
 GTK compile:     3.24.13
 GTK run:         3.24.13
 libsoup compile: 2.68.3
 libsoup run:     2.68.3
 Extension dir:   /usr/pkg/lib/vimb

(This is on NetBSD/amd64 -current though.)

**Comment by steview2000** [comment]
Hi iamleot,

Thanks for checking. I also checked on a different computer with the same setup (same OS, webkit and vimb version) as my laptop (but better specs) and the problem doesn't occur there. 

> AFAIK qutebrowser uses QtWebKit or QtWebEngine (not WebKitGTK).

Indeed, my qutebrowser installation used QtWebEngine. So I guess the problem is with WebKit or WebKitGTK and maybe some other weird settings on my side and have nothing todo with Vimb.

I guess the issue can be closed then.
