### ISSUE TITLE
Permanent marks and global marks

### ISSUE THREAD

**Issue by AdrienLemaire** [fanglingsu/vimb#598]
Related: #355 

Hi and thanks for making this cute browser. Just found it yesterday, and looking forward to becoming proficient with it.

One thing that I'm missing from [Vimium](https://github.com/philc/vimium) are better marks:

* using backtick ` as well as single quote ' to jump to a mark
* lowercase letters register local marks; uppercase letters register global marks
* marks are remembered permanently (either repeat mX to toggle mark or :delm ?)

Is that not implemented in vimb because you consider bookmarks to be enough?

Example: Access vimb with mark/tag V:
* `mV` then `'V`
* `:bma V` then `:open !V`

Note that marks not only save the url but also the location in the page, which can be very handy when you want to jump to a specific paragraph in a very long webpage. Since vimb clears local tags after leaving the page, it can be tedious to find back the right location in a page if some search pattern to get there is repeated multiple times in that page.

**Comment by fanglingsu** [comment]
@AdrienLemaire This would be a nice feature. I do not like the way the marks are processed now because they do not always address the right location on the page. I'm not sure if it's possible to address the right location in the page in time where so many pages implement sort of endless scrolling and AJAX updated content. If you scroll to the same distance from top tomorrow, you would possibly end up somewhere else.

**Comment by aksr** [comment]
"stale bot" should be removed completely, it close, by now, many relevant bugs reports/features requests.

**Comment by iamleot** [comment]
aksr writes:
> "stale bot" should be removed completely, it close, by now, many relevant bugs reports/features requests.

Yes, I don't think it's nice to automatically close issues.

**Comment by fanglingsu** [comment]
@iamleot I've removed the closing of stale issues with 5840a021f56f62edb031277dd6677a70e8debb6c.

**Comment by iamleot** [comment]
Thank you very much @fanglingsu!
