### ISSUE TITLE
google spreadsheets unsupported

### ISSUE THREAD

**Issue by AdrienLemaire** [fanglingsu/vimb#601]
```console
$ vimb --bug-info
Version:         3.6.0
WebKit compile:  2.26.2
WebKit run:      2.26.3
GTK compile:     3.24.13
GTK run:         3.24.13
libsoup compile: 2.68.3
libsoup run:     2.68.3
Extension dir:   /usr/lib/vimb
```

![google-spreadsheet](https://user-images.githubusercontent.com/260983/73623367-0f058680-4680-11ea-81e4-684f27fdfafe.png)

Have people been able to use google spreadsheets before? Latest webkit2gtk version is 2.26.3, so vimb looks up to date.
I'm not familiar with webkit. Isn't it used by Safari and considered a "modern" browser? I'm pretty sure safari users can open google spreadsheets ^^'

**Comment by AdrienLemaire** [comment]
Also having issues with adobe xd, not able to browser mockups shared on https://xd.adobe.com/view/

**Comment by dantleech** [comment]
I also have issues with Tweetdeck, youtube, github and other "modern" apps (sometimes it's just JS, but I notice Tweetdeck / Github can also leak memory when left open for long periods of time).

**Comment by fanglingsu** [comment]
In the past there where multiple issue with web applications from google caused by the user-agent string. It might be worth to change `set user-agent=...` to something else and check if this helps.

**Comment by AdrienLemaire** [comment]
Spot on for google spreadsheets! That was the most annoying issue, so that's a relief.
Haven't noticed issues with youtube&github so far.
Still no luck with adobe xd, thus I can't work solely with vimb. But to be honest, the debugger console feels subpar compared to chrome or firefox, so I'll keep vimb for non-webdev usage.

**Comment by fanglingsu** [comment]
@AdrienLemaire I've set `:set useragent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15` and there is not warning about unsupported browser at the top and the spreadsheet seems to work.
