### ISSUE TITLE
feature request: set value for mouse scroll step

### ISSUE THREAD

**Issue by sdsddsd1** [fanglingsu/vimb#602]
### Expected behaviour
set (increase) value for the scrollstep wheel scrolling.
### Actual behaviour
One wheel click equals one line forward. This is very tedious when using the mouse.

**Comment by fanglingsu** [comment]
@sdsddsd1 That might be a nice litte feature. But I don't see any knob to easily change the mouse scroll speed. I suggest to configure the wheel speed in general (Xorg or whatever) so it fit the most of your needs.
the difference between scrollstep and wheel scrolling ist that former is handles by vimb itself and later is done by webkit2.

**Comment by sdsddsd1** [comment]
@fanglingsu : I have no Idea if this suits, but at suckless' surf you can modify it with this [patch](http://surf.suckless.org/patches/scroll-faster/)

**Comment by fanglingsu** [comment]
@sdsddsd1 Thank you. This looks promising. But I'm not sure if we can adjust it to scroll done by whell to the the same amount as the scrollstep. I'll see if this works.

**Comment by sdsddsd1** [comment]
I hold my fingers crossed.

**Comment by fanglingsu** [comment]
I've added a new setting `scroll-mulitplier` to do what is done in suckless. At the time its only an integer, so it might be possible that you can find a value that scroll the same distance like your `scroll-step`.

**Comment by fanglingsu** [comment]
@sdsddsd1 Please close this issue if it fit for your needs.

**Comment by sdsddsd1** [comment]
@fanglingsu Thats exct what I was thinking of. I appreciate your erfords. Many thanks!
