### ISSUE TITLE
In normal mode, type "i" key to be in insert mode

### ISSUE THREAD

**Issue by tyjak** [fanglingsu/vimb#605]
Version:         3.6.0
WebKit compile:  2.26.2
WebKit run:      2.26.4
GTK compile:     3.24.13
GTK run:         3.24.14
libsoup compile: 2.68.3
libsoup run:     2.68.3
Extension dir:   /usr/lib/vimb

### Steps to reproduce

In an input field in "insert mode" I hit ESC and I perform a CMD (ie. :set caret\<CR\>) I hit key "i" and I return back to the input field Ieft, BUT with the letter "i" typed in it.

### Expected behaviour

Like in vim, type "i" to be in insert mode aka focused on the last input field you were, if no input field as been focused yet then do like gi command, focus on the first input field found.

### Actual behaviour

On insert mode in any input field, I hit <ESC> key to perform a cmd, and there is no insert command to focus back in the input field I left without have a letter to be inserted in the field.

**Comment by fanglingsu** [comment]
@tyjak I never thought about such a feature. But it sounds reasonable to me to allow to focus last input field after switching away from input mode.

**Comment by fanglingsu** [comment]
@tyjak I've added the normal mode `i` to focus last focused field again if there was one. Could you please check if this works for you too and close the issue if this fits.

**Comment by tyjak** [comment]
@fanglingsu it works as expected thank you :)

But I don't know if I mistaken something during the compilation : my `augroup` and `autocommand` or not recognize as command anymore. 

Version : vimb, version 3.6.0-12-ga212b51

Error:
```
** (vimb:166247): WARNING **: 00:53:18.565: Invalid command in /home/david/.config/vimb/config: 'augroup bookmark'

** (vimb:166247): WARNING **: 00:53:18.565: Invalid command in /home/david/.config/vimb/config: '    autocmd LoadFinished file:///*/bookmark e! bookmarkFileToHtml();'

** (vimb:166247): WARNING **: 00:53:18.566: Invalid command in /home/david/.config/vimb/config: '    autocmd LoadFinished file:///*/bookmark.d/* e! bookmarkFileToHtml();'

** (vimb:166247): WARNING **: 00:53:18.566: Invalid command in /home/david/.config/vimb/config: 'augroup end'
```

**Comment by fanglingsu** [comment]
@tyjak It look like you compiled vimb withou autocmmand support. To have autocommands there must be the `#DEFINE FEATURE_AUTOCMD` in `src/config.h`.
