### ISSUE TITLE
Installation instructions too assumptive

### ISSUE THREAD

**Issue by savaged** [fanglingsu/vimb#608]
### Steps to reproduce

New user interested in installing vimb for the first time finds the README has the following:
```
Edit config.mk to match your local setup.

Edit src/config.h to match your personal preferences.
```
One might expect additional information on what such an edit might require, perhaps with some examples.

### Expected behaviour

Comprehensive instructions on how to install.

### Actual behaviour

No explanation is given, perhaps because experience and knowledge is assumed.

**Comment by fanglingsu** [comment]
@savaged The man page was adapted by @Unixsys so it is clearer what could be changed.
