### ISSUE TITLE
Question: push to Read It Later with mouse

### ISSUE THREAD

**Issue by ghetto-ch** [fanglingsu/vimb#610]
Hello,
I'm aware the goal of this borowser is to use it with the keyboard, nevertheless I would be interested in pushing to the queue using the mouse, I just find it better for this task. Is there a way to do this? In example CTRL-LClick opens in a new tab; is it possible to have a combination like this to push to queue?
Thank you for the great job with vimb! I'm really enjoying so far!

**Comment by fanglingsu** [comment]
@ghetto-ch This sound interesting.

**Comment by fanglingsu** [comment]
@ghetto-ch I've added Shift-LeftMouse to allow to push link url to the queue.

**Comment by ghetto-ch** [comment]
Great! Thank you!
