### ISSUE TITLE
Browser freezing when pressing "f" inside tabbed

### ISSUE THREAD

**Issue by Jeytas** [fanglingsu/vimb#614]
### Steps to reproduce
When using `vimb` inside `tabbed`, it frequently freezes when using the hint-mode. It also seems to freeze randomly when using `tabbed`, but it's most notable when trying to use hint-mode. The screen is then stuck in the `;o` mode without you being able to do anything; merely force closing it using `htop` or `pkill` works.

This happens on all of my machines with clean `vimb` installs from the Manjaro Community Repositories (Vimb version 3.6.0).

### Expected behaviour
The program should obviously not freeze when using it inside tabbed.

### Actual behaviour
It shouldn't freeze when using `tabbed`

**Comment by iamleot** [comment]
Hello @Jeytas,
does it works - with no freezes - outside `tabbed`?

If that's the case probably it is a duplicate of: #138 (in the comments you can find also a possible patch for tabbed to workaround that).

**Comment by Jeytas** [comment]
Hello and thank you @iamleot !

I checked issue #138 and tried out adding `resize(sel, ww, wh - bh);` to line 274 of `tabbed.c` and that _does_ appear to have fixed the issue for now.

Thank you a lot!
