### ISSUE TITLE
Question: Is there a way to cause a reload through a external script?

### ISSUE THREAD

**Issue by saidg23** [fanglingsu/vimb#615]
Hi I was wondering if there was a way to cause vimb to reload through a shell command. I've tried xdotool but it doesn't seem to work.

I use surf to preview a webpage I'm working on in vim and it reloads on save; this is done by sending it SIGHUP. I would really like to switch away from surf as it's not as performant as vimb.

**Comment by fanglingsu** [comment]
@saidg23 There is no direct way to do that at the time. This would required something like the socket support we had in the old version #344 that was not readded yet.

**Comment by saidg23** [comment]
I see. Well I guess I'll have to wait for that then. Thanks
