### ISSUE TITLE
Typo in manual?

### ISSUE THREAD

**Issue by yoctocell** [fanglingsu/vimb#617]
In the man page, there is an option called `spacial-navigation (bool)`, but in the description it says "Spatial Navigation". Should it be called `spatial-navigation (bool)` instead?

```
$ vimb --bug-info
Version:         3.6.0-14-g866ac2b
WebKit compile:  2.28.2
WebKit run:      2.28.2
GTK compile:     3.24.20
GTK run:         3.24.20
libsoup compile: 2.70.0
libsoup run:     2.70.0
Extension dir:   /usr/local/lib/vimb
```

### Steps to reproduce
Type `man vimb` in your shell and search for `spacial-navigation`

**Comment by fanglingsu** [comment]
@yoctocell Thank you for reporting this issue. Also the setting was named wrong.
