### ISSUE TITLE
Youtube play broken

### ISSUE THREAD

**Issue by tyjak** [fanglingsu/vimb#631]
Version:         3.6.0
WebKit compile:  2.26.2
WebKit run:      2.28.4
GTK compile:     3.24.13
GTK run:         3.24.23
libsoup compile: 2.68.3
libsoup run:     2.70.0
Extension dir:   /usr/lib/vimb

### Steps to reproduce
Install last package gst-libav-1.18.0-1, gst-plugins-bad, gst-plugins-bad-libs (Archlinux)

### Expected behaviour
Youtube video to play

### Actual behaviour
Youtube video does not play anymore

I have to downgrade to gst-libav, gst-plugins-bad and gst-plugins-bad-libs to 1.16.2-13 to have youtube play back again.
Probably not a vimb issue, but thought could be useful for other to know this.

**Comment by fanglingsu** [comment]
@tyjak I can't reproduce this issue on archlinux. I updated all packages today an can view youtube videos without any issues.
```
$ pacman -Q | grep gst
gst-libav 1.18.0-1
gst-plugins-bad 1.18.0-1
gst-plugins-bad-libs 1.18.0-1
gst-plugins-base 1.18.0-1
gst-plugins-base-libs 1.18.0-1
gst-plugins-good 1.18.0-1
gst-plugins-ugly 1.18.0-1
gstreamer 1.18.0-1
gstreamer-vaapi 1.18.0-1
```
Not sure if this helps, but your vimb was compiled against an old webkit, so it might help to compile it again.

**Comment by tyjak** [comment]
I installed vimb from the arch communauty repo (pacam -S vimb) and this vimb package is compiled against the 2.26.2 version of webkit. But even with this version and with the updated gst lib dependencies, I don't have the pb anymore...
