### ISSUE TITLE
Duolingo, can't start exercises

### ISSUE THREAD

**Issue by machinedgod** [fanglingsu/vimb#632]
Version:         3.6.0
WebKit compile:  2.26.2
WebKit run:      2.30.1
GTK compile:     3.24.13
GTK run:         3.24.23
libsoup compile: 2.68.3
libsoup run:     2.72.0
Extension dir:   /usr/lib/vimb

### Steps to reproduce
Open 'duolingo.com', try to start any exercise

### Expected behaviour
Clicking on round exercise button opens a small dialogue with two buttons, offering lesson tips if there are any or starting a lesson.

### Actual behaviour
No dialogue opens.

I checked if events are registered using the web inspector, and clicking on the element seems to trigger attribute changes; not sure these are standard HTML attributes and I'm thinking they're probably linked to some UI framework they're using.

In Firefox, it works normally:
![2020-10-12-105459_1411x1073_scrot](https://user-images.githubusercontent.com/5933618/95760768-6c26f280-0c79-11eb-80ff-8b882f1d6347.png)-

Vimb, before click:
![2020-10-12-105701_749x887_scrot](https://user-images.githubusercontent.com/5933618/95761009-b7d99c00-0c79-11eb-993e-092a469635b1.png)

Vimb, after click (notice div element appear in DOM, but not visible on screen)
![2020-10-12-105711_651x844_scrot](https://user-images.githubusercontent.com/5933618/95761180-f1120c00-0c79-11eb-903e-d1719f2bc194.png)

**Comment by fanglingsu** [comment]
I clicke through the evaluation question and thin I'm on the place where the issue can be seen. Ig I open the webdeveloper I get the error `Unhandled Promise Rejection: [object Event]` which might be related to the issue.

**Comment by machinedgod** [comment]
Yeah, could be. I wouldn't be surprised if the site is coded using undefined behaviours that just seem to behave OK on other JS engines.
What could I do to investigate this further and perhaps help fix it?

**Comment by machinedgod** [comment]
Hi,
um, this seems to got fixed by itself. I just tested it, and it works. I shall close this.

**Comment by fanglingsu** [comment]
I like issues that solve themselves.
