### ISSUE TITLE
It is not possible to use WhatsApp web.

### ISSUE THREAD

**Issue by lucasmsoares96** [fanglingsu/vimb#636]
Version:         3.6.0-23-ga614929
WebKit compile:  2.30.1
WebKit run:      2.30.1
GTK compile:     3.24.23
GTK run:         3.24.23
libsoup compile: 2.72.0
libsoup run:     2.72.0
Extension dir:   /usr/local/lib/vimb

### Steps to reproduce
Access the Whatsapp web site:
https://web.whatsapp.com/

### Expected behaviour
Show the qr code to login.

### Actual behaviour

![image](https://user-images.githubusercontent.com/60808407/96370138-41361600-1133-11eb-9d72-a62596779ffd.png)

**Comment by unixbhaskar** [comment]
Okay, if your use this 

`set user-agent=googlebot` 

in your config file , it will get you going. Means you can get the qr code on the screen.

Heads up!! some specific sites misbehave , if you change the user-agent , I haven't found solution to that breakage.

**Comment by fanglingsu** [comment]
@lucasmsoares96 Changing the user-agent solves the issue. So I close this because there is nothing else we can to in case stupid pages rely on evaluation the user agent string.
It's strange, but I see the QR Code also with default user agent after I called the page initially with googlebot.
