### ISSUE TITLE
How to disable prefetch?

### ISSUE THREAD

**Issue by iio7** [fanglingsu/vimb#637]
As the title says, how to disable link prefetching?

**Comment by fanglingsu** [comment]
@iio7 Sorry for the late response. I'm not sure what you mean by "link prefetching". Webkit has support for dns prefetching which is by default disabled https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#WebKitSettings--enable-dns-prefetching.
But i'll allow to change this setting in vimb.
