### ISSUE TITLE
[Feature request] Fetch text first, load images/scripts after

### ISSUE THREAD

**Issue by marek-lach** [fanglingsu/vimb#638]
Make rendering of web pages ready faster, by fetching and rendering all purely text content at first, and only getting images etc., after the text content has finished loading.

**Comment by fanglingsu** [comment]
There are not real knobs in webkit to do such a stepped content loading. And in my opinion this would not provide any benefit. All webengines do their best to load as much as possible in parallel. And normally the text content is loaded with the initial document which is always loaded first. But this is only the load via the net and does not mean that the text is ready for beeing rendered. We can't force to load and render text prior to other sources. What should be rendered on such stupid pages where the whole content is written and moved around by javascript, when the javascript is not loaded?

The only way to skip image loading could be by autocomands like following. But I think this does not make things load faster.
```
aug mygroup
au LoadStarting * set images=off
au LoadFinished * set images=on
aug end
```
