### ISSUE TITLE
History broken

### ISSUE THREAD

**Issue by tyjak** [fanglingsu/vimb#641]
Version:         3.6.0-23-ga614929
WebKit compile:  2.30.1
WebKit run:      2.30.1
GTK compile:     3.24.23
GTK run:         3.24.23
libsoup compile: 2.72.0
libsoup run:     2.72.0
Extension dir:   /usr/lib/vimb
Extensions: 
adblock.so
webext_main.so

1. Go to web page

2. The web page should be in the .config/vimb/history

3. Visited web page aren't in the history file

(I tried without adblock.so same behavior)

**Comment by dantleech** [comment]
I sometimes have the same thing due to a corrupt `history` file, in which case removing the offending line fixes it.

**Comment by tyjak** [comment]
Yes, I verified that also... I'm on archlinux and when I install the aur package vimb that is 3.6.0, I don't have the problem, but with the package vimb-git (head version from github i presume) I encountered the problem (same history file).

**Comment by fanglingsu** [comment]
@tyjak If ouy use lastes version the location of the history files was changes https://github.com/fanglingsu/vimb/blob/a6149298483ae14a3722705d3c402e14820c3bbf/CHANGELOG.md#changed.

**Comment by tyjak** [comment]
@fanglingsu, thank you and sorry I should have read the changelog !!!
