### ISSUE TITLE
Slackware build failing!

### ISSUE THREAD

**Issue by unixbhaskar** [fanglingsu/vimb#644]
```
bhaskar@Slackware_13:55:10_Mon Nov 02:~> vimb --bug-info
Version:         3.6.0-23-ga6149298483a
WebKit compile:  2.28.4
WebKit run:      2.22.2
GTK compile:     3.24.22
GTK run:         3.24.23
libsoup compile: 2.70.0
libsoup run:     2.70.0
Extension dir:   /home/bhaskar/lib/vimb
```
### Steps to reproduce
vimb 
### Expected behavior
should open the browser
### Actual behavior
```
bhaskar@Slackware_13:54:09_Mon Nov 02:~> vimb
vimb: symbol lookup error: vimb: undefined symbol: webkit_uri_for_display
```

**Comment by iamleot** [comment]
Bhaskar Chowdhury writes:
> ```
> [...]
> WebKit compile:  2.28.4
> WebKit run:      2.22.2
> [...]
> ```

That's probably the problem: vimb was compiled against WebKitGTK 2.28.4
but 2.22.2 is used and they are probably API and ABI incompatible.

**Comment by unixbhaskar** [comment]
> Bhaskar Chowdhury writes:
> ``` [...] WebKit compile: 2.28.4 WebKit run: 2.22.2 [...] ```
> That's probably the problem: vimb was compiled against WebKitGTK 2.28.4 but 2.22.2 is used and they are probably API and ABI incompatible.

It seems so....not the specific one open up the browser but showing a big banner of that "**webkit encounter an internal erro**r"

**Comment by fanglingsu** [comment]
@unixbhaskar If you recompile vimb it should work. Or you could update you current webkitgtk package.

**Comment by unixbhaskar** [comment]
> @unixbhaskar If you recompile vimb it should work. Or you could update you current webkitgtk package.

Okay I did, still it was bugging ...so found the source of it ...3 things were missing ...

libwep and related libeary -----> which I got it from slackware.pkg.org
libhyphen ------> which I got from slackware.pkgs.org

Exactly these pkgs were needed :  **hyphen-2.8.8-x86_64-1.txz  libwpe-1.8.0-x86_64-1cf.txz  webkitgtk-2.30.2-x86_64-2cf.txz  wpebackend-fdo-1.8.0-x86_64-1cf.txz**

and the main culprit....**gsettings-desktop-schemas**

Which I installed thorugh local pkg manager .....and voila!!   :)

Thanks a bunch for the patience @iamleot  and Daniel @fanglingsu  for stopping by.  Any one of you can close , if you feel so ...or I will came back after 2 days and close it myself.

**Comment by unixbhaskar** [comment]
Well, I am closing this , becasue it "solves my issue with it" , but you can reopen it , if you are on the same platform and having related isuues, so we might peek in and find out.

**Comment by fanglingsu** [comment]
@unixbhaskar Nice to head that you could solve the issue.
