### ISSUE TITLE
Unable to view content from the LBRY protocol (lbry.tv / odysee.com)

### ISSUE THREAD

**Issue by VictorAlbertsson** [fanglingsu/vimb#647]
### vimb --bug-info
Version:         3.6.0
WebKit compile:  2.26.2
WebKit run:      2.30.2
GTK compile:     3.24.13
GTK run:         3.24.23
libsoup compile: 2.68.3
libsoup run:     2.72.0
Extension dir:   /usr/lib/vimb

### Steps to reproduce
Go to lbry.tv or odysee.com and click on a video

### Expected behaviour
Video plays

### Actual behaviour
Media player reports: "No compatible source was found for this media"

Any help would be greatly appreciated.

**Comment by iamleot** [comment]
Hello Victor,

Victor Albertsson writes:
> [...]
> ### Steps to reproduce
> Go to lbry.tv or odysee.com and click on a video
>
> ### Expected behaviour
> Video plays
>
> ### Actual behaviour
> Media player reports: "No compatible source was found for this media"
>
> Any help would be greatly appreciated.
> [...]

Probably some gstreamer plugins needed not installed.

I can play videos on lbry.tv here with the following gstreamer plugins
installed (output of `pkg_info' on NetBSD with pkgsrc, but other
package systems probably have similar packages):

 % pkg_info | grep gst
 gstreamer1-1.16.2nb2 Open source multimedia framework
 gst-plugins1-libav-1.16.2nb3 GStreamer libav/ffmpeg plugin
 gst-plugins1-base-1.16.2nb4 Open source multimedia framework - Base plugins
 gst-plugins1-good-1.16.2nb1 Open source multimedia framework - Good plugins
 gst-plugins1-oss-1.16.2nb1 Open source multimedia framework - oss plugin

**Comment by VictorAlbertsson** [comment]
Thank you iamleot, the Arch Linux packages i needed to install where gst-libav and gst-plugins-good.

gst-plugins-good is described by pacman as an optional dependecy for webkit2gtk for media decoding and gst-libav for nonfree media decoding, it would probably be a good idea to add these packages to the README dependencies section since most users will expect media to work out of the box.
