### ISSUE TITLE
Incognito

### ISSUE THREAD

**Issue by Haleycarl** [fanglingsu/vimb#652]
### Steps to reproduce
run command `vimb -i [url]`
### Expected behaviour
when typing in text box all key should work

### Actual behaviour
some keys are not working 
e.g keys `H, J, K, L`

**Comment by fanglingsu** [comment]
@Haleycarl Thak you for reporting this issue. It seems that vimb does not switch to input mode in case it was started in incognito mode. The issue can be reproduced with https://github.com/fanglingsu/vimb/blob/94f67dc4468f3d1151d5174b8af9d5c5bcc760a8/tests/manual/editable-focus.html

**Comment by fanglingsu** [comment]
It's stange. The '[initialize-web-extension](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebContext.html#WebKitWebContext-initialize-web-extensions)' signal is never triggered when we use the ephemeral web context.
