### ISSUE TITLE
Feature Request: Support chromium extensions

### ISSUE THREAD

**Issue by Joe23232** [fanglingsu/vimb#653]
VimB seems like a great browser. but as a privacy oriented user. I would like to use chromium-based browsers as on the chrome store there are plenty of extensions that enhance the user's privacy such as Ublock Origin, Privacy Badge, Random User Agent string, VPNs etc.

**Comment by fanglingsu** [comment]
@Joe23232 There is nearly nothing in common between vimb and chromium so chromium extensions would never get working in vimb. And I don't want to bloat vimb by integrating some extension API which is in some point similar to chromium to hope that at least some of the privacy extension would work also for vimb.
