### ISSUE TITLE
Embedding dmenu on a tabbed vimb cover the whole window 

### ISSUE THREAD

**Issue by toniz4** [fanglingsu/vimb#658]
```
vimb --bug-info
Version:         3.6.0-30-ga8d6130
WebKit compile:  2.30.3
WebKit run:      2.30.3
GTK compile:     3.24.22
GTK run:         3.24.22
libsoup compile: 2.70.0
libsoup run:     2.70.0
Extension dir:   /usr/lib/vimb
```
### Steps to reproduce
open dmenu in vimb inside tabbed with `echo test | dmenu -w "$VIMB_XID"`
### Expected behaviour
dmenu being displayed only at the top of the client. When vimb is not inside tabbed it works as expected
![2021-01-19-025545_720x750_scrot](https://user-images.githubusercontent.com/14265358/104993623-e34eee00-5a01-11eb-8f36-929e0d0c9f42.png)
### Actual behaviour
dmenu covers the whole screen when vimb is inside tabbed (I have tabbed configured to only show the tabs when alt is pressed, the same thing happened with vanilla tabbed and dmenu)
![2021-01-19-025801_679x750_scrot](https://user-images.githubusercontent.com/14265358/104993815-2f019780-5a02-11eb-8bf3-d28245695780.png)

**Comment by fanglingsu** [comment]
@toniz4 I'll have a look at that. I've never tried to run demu within vimb - for which use case to you use that?

**Comment by toniz4** [comment]
I have a bookmark manager that i used to use with surf and something like a session manager. I could open dmenu without `-w` and open it in normally, but embedding it looks nicer and more concise. I would try to find a solution, but i don't know where to look.

**Comment by fanglingsu** [comment]
@toniz4 I've added the new env var `VIMB_WIN_ID` which always holds the window id of the gtk window. The `VIMB_XID` is the xid of the gtk window or in case of embedding the xid of tabbed.

**Comment by toniz4** [comment]
Thanks for the quick response! it worked perfectly.
