### ISSUE TITLE
Hinting doesn't work on Gitlab

### ISSUE THREAD

**Issue by TheGreatMcPain** [fanglingsu/vimb#659]
### Steps to reproduce
Go to a gitlab repository page and try to use hinting.

### Expected behaviour
Have hinting appear on most of not all links.

### Actual behaviour
Some yellow highlighting, no numbers, and no highlighting on items in the repository browser.

![vimb-gitlab-issue](https://user-images.githubusercontent.com/6900584/105140466-5e290f00-5abd-11eb-9128-c987e26fa70b.png)

### Debug Info
```
Version:         3.6.0-30-ga8d6130
WebKit compile:  2.30.3
WebKit run:      2.30.4
GTK compile:     3.24.22
GTK run:         3.24.22
libsoup compile: 2.70.0
libsoup run:     2.70.0
Extension dir:   /usr/lib/vimb
```

**Comment by fanglingsu** [comment]
@TheGreatMcPain Thank you for reporting this issue. I could reproduce it.I saw en error in the developer toolbar "TypeError: undefined is not an object (evaluating 'rect.left')" pointing to https://github.com/fanglingsu/vimb/blob/6b07416d773e2b48c6904c3590222e01f0a66725/src/scripts/hints.js#L178
