### ISSUE TITLE
allow user extensions

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [fanglingsu/vimb#663]
It would be nice to have user extensions in `$HOME/.vimb`.

[config.mk](https://github.com/fanglingsu/vimb/blob/3f9a42b9501b8d062be94e0aaa7c440e3deb7e8b/config.mk#L5) seems to be set with PREFIX and EXTENSIONDIR.

Is there a way to add more directories in the `.vimbrc`?

**Comment by fanglingsu** [comment]
@BebeSparkelSparkel I do not see any real benefit from allowing to kick in additional webextensions. And as I understand the code https://github.com/WebKit/WebKit/blob/8afe31a018b11741abdf9b4d5bb973d7c1d9ff05/Source/WebKit/UIProcess/API/glib/WebKitWebContext.cpp#L1513 right there is only one directory where webkit look for webextensions. So I close this.
