### ISSUE TITLE
DuckDuckGo doesn't work with mouse any more

### ISSUE THREAD

**Issue by machinedgod** [fanglingsu/vimb#666]
Version:         3.6.0
WebKit compile:  2.26.2
WebKit run:      2.30.5
GTK compile:     3.24.13
GTK run:         3.24.26
libsoup compile: 2.68.3
libsoup run:     2.72.0
Extension dir:   /usr/lib/vimb

### Steps to reproduce
1. surf to duckduckgo.com
2. search for anything
3. try to LMB with mouse on any link

### Expected behaviour
Links are followed.

### Actual behaviour
Links aren't followed.

![2021-03-16-152824_986x140_scrot](https://user-images.githubusercontent.com/5933618/111368459-4ceb2180-866c-11eb-93b6-4e625ab15c1a.png)

Note - using hinting (f + narrowing with text + number) still works.

Possibly garbage code from DuckDuckGo, but if so - hinting shouldn't work either. Also, if not a Vimb issue, just thought I'd create it so that anyone experiencing the same issue can find it here.

**Comment by toniz4** [comment]
I experienced the same thing, i imagine that it garbage code. Now it's back to normal.

**Comment by machinedgod** [comment]
Same here, this morning its all good. Nevertheless - I think its important to document it because it still worked fine from eg. Firefox.
