### ISSUE TITLE
font size problem

### ISSUE THREAD

**Issue by lingnand** [fanglingsu/vimb#67]
I've recently purchased a retina macbook and installed vimb on it. Functionally it works just as on my old computer (of course), but unfortunately the text is way too small (the input box, the status bar, the hinting text, as well as the normal text size for the content on the website). I tried zooming but it doesn't seem to change text size. I also tried increasing the font size in the gtk config; or setting the 'defaultfontsize' in vimb config. But neither of these works nicely. Is there any workaround for this?

**Comment by JacksonGariety** [comment]
@fanglingsu can you describe how to enable it?

**Comment by JacksonGariety** [comment]
EDIT: I had to set `GDK_DPI_SCALE=2.0` to get it to look right.

**Comment by JacksonGariety** [comment]
Note that, after enabling the HI_DPI feature, I must `:set fontsize=5` otherwise fonts get twice as big as they should be.

**Comment by fanglingsu** [comment]
@JacksonGariety To enable GTK3 you need the gtk3 and the webkitgtk-3.0, I assume that this is provided by `webkitgtk` package https://www.archlinux.org/packages/extra/x86_64/webkitgtk/.

**Comment by JacksonGariety** [comment]
@fanglingsu thanks. Got GTK3 working. The hardest issue was getting the fonts to look right, which I outlined above. Getting video to play was a matter of installing the `gst` plugins listed elsewhere. For some reason I had all of them except `gst-plugins-bad` and that one was causing the youtube to be 50%.

Thanks for your work on this awesome browser!

**Comment by lucasmsoares96** [comment]
Please come back with the HIDPI patch.
with the set default-zoom = 200, some sites do not send the icon with the correct resolution.

![image](https://user-images.githubusercontent.com/60808407/96358797-a5c88500-10e1-11eb-978b-39a7af7794a2.png)
