### ISSUE TITLE
Page display occasionally freezes

### ISSUE THREAD

**Issue by jjakob** [fanglingsu/vimb#676]
Use vimb normally to browse the web. Occasionally the window freezes, while the page is still loaded in the background and not frozen. The mouse changes when hovering over links in the page where they are in the background, not what's shown in the window. Mouse scrolling scrolls the page but doesn't update either the display or the status bar in the bottom right (position percentage stays the same). While in frozen state, entering ":" will always refresh the status bar, but only sometimes refresh the display. Navigation (ctrl-O) works and loads the previous page and updates the status bar, but the display still stays frozen on the old page.

$ vimb --bug-info
Version:         3.6.0-34-g652f411
WebKit compile:  2.30.6
WebKit run:      2.33.2
GTK compile:     3.24.26
GTK run:         3.24.29
libsoup compile: 2.70.0
libsoup run:     2.72.0
Extension dir:   /usr/lib/vimb

**Comment by jjakob** [comment]
I've just recompiled vimb as I saw the compile and run versions were significantly different. I'll see if that'll have any difference.

**Comment by jjakob** [comment]
That did not fix it, I'm still getting freezes.

**Comment by fanglingsu** [comment]
@jjakob Do you run vimb in tabbed? I'd such issues with tabbed in the past where the screen was not refreshed #138. There is also an description how to patch tabbed to avoid these case.

**Comment by jjakob** [comment]
No, in dwm 8.4 in maximised mode with multiple windows one over another

On July 2, 2021 12:52:14 AM GMT+02:00, Daniel Carl ***@***.***> wrote:
***@***.*** Do you run vimb in tabbed? I'd such issues with tabbed in the past where the screen was not refreshed #138. There is also an description how to patch tabbed to avoid these case.
>

**Comment by jjakob** [comment]
I still have this issue that is very common and makes it almost unusable, having to close it every time it freezes. Is there any way I can debug it?

**Comment by mortezadadgar** [comment]
I noticed vimb don't receive any input until the page is fully loaded perhaps it's related to your issue

**Comment by jjakob** [comment]
@mortezadadgar I don't know. Nothing changed, it still behaves the same, I even found a page that displays as a completely white blank page: hub.docker.com .

vimb --bug-info
Version:         3.6.0-57-g6dbde47
WebKit compile:  2.34.3
WebKit run:      2.34.3
GTK compile:     3.24.29
GTK run:         3.24.29
libsoup compile: 2.72.0
libsoup run:     2.72.0
Extension dir:   /usr/lib/vimb

**Comment by fanglingsu** [comment]
@jjakob I also see white page on hub.docker.com, but only if JavaScript is disabled. If I `:set scripts=on` I see the page.

**Comment by jjakob** [comment]
I have `scripts=true`. I tried to disable the workaround I had for webkit-gtk bug #222358 (`export JSC_useBaselineJIT=false`, by manually setting it to true) but there is no change. I also tried flipping both `accelerated-2d-canvas=false` (was true) and `hardware-acceleration-policy=never` (was ondemand), also no change. Also disabling wyebadblock by deleting the `/usr/lib/vimb/adblock.so` symlink.

**Comment by fanglingsu** [comment]
@jjakob Not sure if this is helpful. But I've use following env in past to get rid of crashes on bitbucket.
```
export JavaScriptCoreUseJIT="0"
export WEBKIT_DISABLE_COMPOSITING_MODE=1
```

**Comment by jjakob** [comment]
@fanglingsu Thanks, I'm trying them out right now, so far I haven't had a crash, which is much better than anything before. I think the main difference is in `WEBKIT_DISABLE_COMPOSITING_MODE=1` because I already had `JavaScriptCoreUseJIT=0` (which only stopped Webkit from crashing but didn't fix the window freezing).

Also, interestingly, since a few days ago I can open hub.docker.com with no problems, and I didn't do anything! Maybe a recent update of webkit or some other software fixed it.
