### ISSUE TITLE
Flash not working..?

### ISSUE THREAD

**Issue by lingnand** [fanglingsu/vimb#68]
I'm on arch linux and for some reason the flash plugin has stopped working for me.

On firefox it's stilling working fine though.

**Comment by JacksonGariety** [comment]
@lynnard did you encounter `no appropriate viewer found for libflash.so` when you ran `nspluginwrapper -v -a -n -i`?

**Comment by lynnard** [comment]
No I didn't - it was quite a long time ago but I remember got it working with the steps I outlined in the comment.

**Comment by JacksonGariety** [comment]
@lynnard thanks. Works with your instructions.
