### ISSUE TITLE
Youtube/odysee not showing video thumbnail..check out the picture attached...

### ISSUE THREAD

**Issue by unixbhaskar** [fanglingsu/vimb#682]
**This is happening across OSes , namely , precisely, Gentoo,Slackware,Debian,Arch,Tumbleweed.**

Also tried to change theme to light/dark ...alas! the story is same. Wondering! I am sure, I am missing very obvious.

bhaskar@debian_06:09:47_Mon Sep 20: :~>vimb --bug-info
Version:         3.6.0
WebKit compile:  2.30.3
WebKit run:      2.32.3
GTK compile:     3.24.22
GTK run:         3.24.24
libsoup compile: 2.70.0
libsoup run:     2.72.0
Extension dir:   /usr/local/lib/vimb

### Steps to reproduce

Open youtube.com/odysee.com and seeing this

### Expected behaviour

Should show the video thumbnail

### Actual behaviour

In the attached pic
![2021-09-20-060738_1366x768_scrot](https://user-images.githubusercontent.com/113643/133948339-3aaf5bef-682e-4f90-920c-acbfa31fa959.png)

**Comment by unixbhaskar** [comment]
This issue has striking similarity... Some images won't load #97

Again! recompiled it doesn't solve the issue. Where am I missing? 

Pls shed some light.

**Comment by Sadoon-AlBader** [comment]
Can you share you config and your style.css if you're using one?

**Comment by unixbhaskar** [comment]
@Sadoon-AlBader  Here is my  ...

Style Sheet:
[https://github.com/unixbhaskar/dotfiles/blob/master/vimb_style_config](url)

Config :
[https://github.com/unixbhaskar/dotfiles/blob/master/vimb_config](url)

Check out.

**Comment by Sadoon-AlBader** [comment]
Ah, as expected. The problem is with your stylesheet.
Try
`:set stylesheet=off`

Or consider using an autocmd to disable the stylesheet and enable dark-mode on specific websites like this:

`:autocmd LoadStarted https://odysee.com/* set stylesheet=off | set dark-mode=on`

Some sites, like odysee, do not respect dark mode and you need to toggle it from the site menu on the gear icon.

**Comment by unixbhaskar** [comment]
> Ah, as expected. The problem is with your stylesheet.
> Try
> `:set stylesheet=off`
> 
@Sadoon-AlBader  Thanks a bunch!

**Comment by Sadoon-AlBader** [comment]
> @Sadoon-AlBader Thanks a bunch!

You are most welcome :)

**Comment by fanglingsu** [comment]
@unixbhaskar The reaso for the missing images is following in you style.css
```
*,div,pre,textarea,body,input,td,tr,p
{
    background-color: #002b36 !important;
}
```
This sets background color to all elements. And I assume that this background covers the images or so. I've used a litte more fine grained approach to change the backgorunds and the images for the videos are shown. This is my style, which is only used if dark mode is enabled https://github.com/fanglingsu/dotfiles/blob/master/.config/vimb/style.css

**Comment by unixbhaskar** [comment]
> @unixbhaskar The reaso for the missing images is following in you style.css
> 
> ```
> *,div,pre,textarea,body,input,td,tr,p
> {
>     background-color: #002b36 !important;
> }
> ```
> 
> This sets background color to all elements. And I assume that this background covers the images or so. I've used a litte more fine grained approach to change the backgorunds and the images for the videos are shown. This is my style, which is only used if dark mode is enabled https://github.com/fanglingsu/dotfiles/blob/master/.config/vimb/style.css

Thanks , man! looks bloody good.
