### ISSUE TITLE
PulseAudio sinks not released (used with Tabbed)

### ISSUE THREAD

**Issue by machinedgod** [fanglingsu/vimb#684]
Version:         3.6.0
WebKit compile:  2.26.2
WebKit run:      2.32.4
GTK compile:     3.24.13
GTK run:         3.24.30
libsoup compile: 2.68.3
libsoup run:     2.74.0
Extension dir:   /usr/lib/vimb

### Steps to reproduce
1. Run Vimb nested inside Tabbed
2. Open pages that produces sound (such as YouTube video)
3. Close tabs

### Expected behaviour
PulseAudio sinks are released and removed when page is closed

### Actual behaviour
PulseAudio sinks keep piling up

### Note
It is possible that this is somehow caused by being nested inside Tabbed (this might confuse PulseAudio), although I use the Ctrl-Q shortcut to tell Vimb to close itself.

**Comment by Sadoon-AlBader** [comment]
I also run vimb in tabbed but I do not have the same issue you have.
As soon as I close the "tab", the sink is released.
It looks like you've built vimb on a very old version of webkit and then proceeded to update, did you try `make clean` and then rebuilding and installing vimb from scratch?

**Comment by machinedgod** [comment]
> It looks like you've built vimb on a very old version of webkit and then proceeded to update, did you try `make clean` and then rebuilding and installing vimb from scratch?

Hi, thank you for the tip!
I haven't tried building my own version at all, I am just using official Arch package. I shall try that next and see if it solves the problem.

I didn't even know that webkit version in my build is old, I wonder if this is a cause of some of the other issues I'm having.

**Comment by machinedgod** [comment]
I did what was suggested (rather than installing Vimb from packages, I used AUR package to compile it from git souces, and link it against newer webkit2gtk version).

It fixed the problem :-)
I am closing this issue and marking it as solved.
