### ISSUE TITLE
How to yank the current page Title + URL into a buffer?

### ISSUE THREAD

**Issue by philiprhoades** [fanglingsu/vimb#686]
People,

I have been using VimB for quite a while but only for quick jobs - I now want to replace some of my Chrome / Brave / FF use with it so I just cloned from scratch and spent a fair time installing *-devel RPMs and symlinking dirs and *.h files but finally got a Fedora 34  (Wayland instead of Xorg) binary working - thanks for a great app!

For a long time I have been using Chrome / Brave and FF extensions to grab the Title and URL of a page in a format like:

Title | URL

or 

Title
URL

into the system clipboard - is there some way I can do the same thing with VimB ?

Phil.

**Comment by fanglingsu** [comment]
@philiprhoades If it works for you now, I'll close this.

**Comment by philiprhoades** [comment]
Yes, no worries - been using it for a while now! - and I am gradually replacing some of the Chrome / FF / Brave stuff I do with vimb!
