### ISSUE TITLE
Config Issues

### ISSUE THREAD

**Issue by fennewald** [fanglingsu/vimb#688]
Hello,

I've been struggling to accomplish two things:
1.) On my machine, Ctrl-O is bounded already for something else. I would like to remap the go-back command, but I cannot find a working shortcut command that allows me to go back,
2.) I want to use google search by default, but I can't get search urls formatted right. Has anyone done this/know how to change shortcut url parsing?

**Comment by fanglingsu** [comment]
@fennewald I use something like `shortcut-add gg=https://www.google.de/search?q=$0&ie=UTF-8` to use google search by `:o gg whatever to search for` and have not noticed any issues.
