### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by JustAShadow777** [fanglingsu/vimb#689]
Hi,
I can't find the assigned time between scrollsteps. At keypress it waits a couple of ms to initiate the second step.

**Comment by fanglingsu** [comment]
@JustAShadow777 There is no configuration for the time between the scroll steps. I assume the time between is spent sending the IPC Messages from vimb to its webextension which calls JS logic on the page to scroll.
If I switch to pass through mode by `<ctrl-z>` and use the cursor keys the scrollling is done direct by webkit without the IPC logic but this similar slow and steppy. If you want to scroll faster you should use a mouse wheel or somthing that emulates this or use faster scroll variants like `<ctrl-f>` or `<ctrl-d>`.

**Comment by JustAShadow777** [comment]
> @JustAShadow777 There is no configuration for the time between the scroll steps. I assume the time between is spent sending the IPC Messages from vimb to its webextension which calls JS logic on the page to scroll. If I switch to pass through mode by `<ctrl-z>` and use the cursor keys the scrollling is done direct by webkit without the IPC logic but this similar slow and steppy. If you want to scroll faster you should use a mouse wheel or somthing that emulates this or use faster scroll variants like `<ctrl-f>` or `<ctrl-d>`.

Thanks for responding. I was looking for Vimium-like smooth scrolling with a continuous animation
