### ISSUE TITLE
html5 video not working

### ISSUE THREAD

**Issue by lingnand** [fanglingsu/vimb#69]
I'm using gtk3 vimb in the high-dpi branch and the html5 videos are not working (on Arch Linux). I tried compiling with gtk2 and it still doesn't work.

**Comment by jeaye** [comment]
I spent a long time trying to get this working on my Slackware machine and ended up with a weird solution. In short, even though I'm using ffmpeg, as opposed to libav, I need the gst-libav plugin (the gst-ffmpeg plugin doesn't cut it) in order for video to work.

For the Slackware users out there, this is my gst* related package listing (though all of these may not be needed, the libav plugin certainly is and was not obvious):
```
┌─(✓)[jeaye@darkstar]─[~]
└──╼ ls -1 /var/log/packages/gst*
/var/log/packages/gst1-libav-1.4.5-x86_64-1_SBo
/var/log/packages/gst1-plugins-bad-1.4.5-x86_64-1_SBo
/var/log/packages/gst1-plugins-base-1.4.5-x86_64-1_SBo
/var/log/packages/gst1-plugins-good-1.4.5-x86_64-1_SBo
/var/log/packages/gst1-plugins-ugly-1.4.5-x86_64-1_SBo
/var/log/packages/gst-ffmpeg-0.10.13-x86_64-2_SBo
/var/log/packages/gst-plugins-bad-0.10.23-x86_64-3_SBo
/var/log/packages/gst-plugins-base-0.10.36-x86_64-2
/var/log/packages/gst-plugins-good-0.10.31-x86_64-5
/var/log/packages/gst-plugins-ugly-0.10.19-x86_64-2_SBo
/var/log/packages/gstreamer-0.10.36-x86_64-2
/var/log/packages/gstreamer1-1.4.5-x86_64-1_SBo
```

**Comment by shioyama** [comment]
thanks @jeaye that fixed this issue for me!

**Comment by axionix** [comment]
@shioyama Thanks, that single package was the problem.

**Comment by MagnusMWW** [comment]
Installing gstreamer1-plugins-libav on openbsd solved this issue for me as well. Thanks @jeaye !

**Comment by SamHH** [comment]
I can't seem to get HTML5 video to work on my installation of vimb on Arch. Here's the `--bug-info`:

```
Version:         3.6.0
WebKit compile:  2.26.2
WebKit run:      2.28.1
GTK compile:     3.24.13
GTK run:         3.24.17
libsoup compile: 2.68.3
libsoup run:     2.70.0
Extension dir:   /usr/lib/vimb
```

My repro is `vimb 'https://www.youtube.com/watch?v=_S7B18GqdY0`, though I've experienced the same on other sites, for example on Gfycat embeds on Reddit.

With these installed:

```
$ pacman -Q | rg gst
gst-plugins-base 1.16.2-1
gst-plugins-base-libs 1.16.2-1
gstreamer 1.16.2-1
```

The YouTube page says that my browser doesn't recognise any of the formats available. If I additionally install `gst-libav` then the page starts to load as if video is available, and then I get `Webview Crashed`. There is nothing output to the terminal in which the process was started.

Let me know what else I can do to help debug this, cheers.

**Comment by fanglingsu** [comment]
@SamHH I can view the linked video also on arch. That is what I have on my system. but I'm not sure if all packages are required or not.
```
$ pacman -Q | grep gst
gst-libav 1.16.2-1
gst-plugins-bad 1.16.2-7
gst-plugins-bad-libs 1.16.2-7
gst-plugins-base 1.16.2-1
gst-plugins-base-libs 1.16.2-1
gst-plugins-good 1.16.2-3
gst-plugins-ugly 1.16.2-3
gstreamer 1.16.2-1
gstreamer-vaapi 1.16.2-1
```

**Comment by SamHH** [comment]
Aha! `gstreamer-vaapi` did the trick, many thanks. :smile:
