### ISSUE TITLE
Unacceptable TLS certificate on puppy linux

### ISSUE THREAD

**Issue by robert-winkler** [fanglingsu/vimb#695]
Hi, I compiled `vimb` on Puppy Linux (<http://blog.puppylinux.com/fossapup64-release>) and it runs great on a 2008 thin client ;- ). Thanks for this great browser for `vim` lovers!

However, on several webpages  the error  `Unacceptable TLS certificate` is displayed. These pages open on the standard Puppy browser Pale Moon. Since Puppy by default runs with the `root' user, I installed the root certificates; but with no luck.

I imagine that I need to compile in some libraries; but which and how?

Version:         3.6.0-48-gf679960
WebKit compile:  2.34.1
WebKit run:      2.34.1
GTK compile:     3.24.20
GTK run:         3.24.20
libsoup compile: 2.70.0
libsoup run:     2.70.0
Extension dir:   /usr/lib/vimb

### Steps to reproduce
Compile and install `vimb` on FossaPup64 (using the devx SFS, `git`, and `make` packages).
Browse to a webpage such as <http://www.pandoc.org>

### Expected behaviour
Opens the webpage.

### Actual behaviour
Error `Unacceptable TLS certificate`.

**Comment by fanglingsu** [comment]
@robert-winkler You could try to start vimb from cli to see warning or errors that are written by webkit and libsoup (which should be responsible for the tls stuff). This might help you to dig into the issue. Maybe the certificates are searched in the wrong path or something similar.

**Comment by robert-winkler** [comment]
@fanglingsu Unfortunately, there is no useful information:
~~~
root# vimb
** Message: 11:32:47.223: Could not read style file: /root/.config/vimb/style.css
~~~  
The missing style message appears directly after starting `vimb`.

**Comment by robert-winkler** [comment]
I  recompiled `vimb` on antiX Linux (<https://antixlinux.com/>) and it works fine!
 Therefore, this is not an `vimb` issue and it can be closed.

**Comment by fanglingsu** [comment]
@robert-winkler Good to hear that it is not an vimb issue - if you find the reason why this does not work on puppy linux - please feel free to share your insights here.
