### ISSUE TITLE
How to Bind q to Close Vimb?

### ISSUE THREAD

**Issue by Amarakon55** [fanglingsu/vimb#700]
I know that ctrl+q closes vimb, but I would like to bind it to q. I tried this:
nmap q :q
But that doesn't hit enter.

**Comment by aksr** [comment]
nmap q :q<CR>

**Comment by Amarakon55** [comment]
> `nmap q :q<CR>`

Thanks, this works. I'm closing this issue.

**Comment by fanglingsu** [comment]
You could also use `nmap q <C-q>`.
