### ISSUE TITLE
How to Make Exceptiont to style.css?

### ISSUE THREAD

**Issue by amarakon** [fanglingsu/vimb#703]
I have a file ~/.config/vimb/style.css. It defines the theme for all websites. However, some websides don't work because of it, so can I add exceptiont for those websites?

**Comment by fanglingsu** [comment]
@amarakon There is no direct exception logic in vimb. But you could use autocommands to do something like that and toggle the `stylesheet` flag.
Following lines in .config/vimb/config would disable use stylesheet for github.
```
augroup nouserstyle
autocmd LoadCommitted * set stylesheet=on
autocmd LoadCommitted https://github.com/* set stylesheet=off
augroup end
```

**Comment by amarakon** [comment]
Thank you, it worked. I am closing this issue.
