### ISSUE TITLE
compability with libsoup3/webkit2gtk-4.1

### ISSUE THREAD

**Issue by hovercats** [fanglingsu/vimb#708]
So, Ive been messing with building webkit2gtk, with libsoup3 instead of 2.
Doing so will result in webkit2gtk-4.1, which vimb seems not to be compatible
with. 
To do so, I added `webkit-web-extension-4.1` to LDFLAGS, and CFLAGS, aswell as
change from webkit2gtk\*-4.0 to 4.1 in config.mk

Doing so will result in the following output;
`
util.c: In function 'util_sanitize_uri':
util.c:806:5: error: unknown type name 'SoupURI'
806 |     SoupURI *uri;
    |     ^~~~~~~
make[1]: *** [Makefile:43: util.o] Error 1
make[1]: *** Waiting for unfinished jobs....
cc ext-util.lo
cc webext_main.so
make[2]: Leaving directory
'/tmp/25200/build/vimb-git/src/webextension'
make[1]: Leaving directory '/tmp/25200/build/vimb-git/src'
make: *** [Makefile:57: src.subdir-all] Error 2
`

Is there any thoughts on this subject? is there any interest in moving over to
4.1 instead of 4.0? or if possible, supporting both?

**Comment by machinedgod** [comment]
I am not very familiar with `webkit2gtk` branching and release strategies.
Would you mind writing up a short benefit of upgrading?

Currently, my user experience with 2.36 is pretty buggy, which renders Vimb unstable - which is a shame. If 4.1 is doing better, I'd probably try to tackle this, given @fanglingsu 's approval.

**Comment by hovercats** [comment]
> I am not very familiar with `webkit2gtk` branching and release strategies. Would you mind writing up a short benefit of upgrading, and the difference between `2.36` and `4.1` (except, obviously, the version number). This is just to save me some research time, if you wouldn't mind.

I dont have alot of info on this tbh, as I more or less stumbled upon it as I were trying to upgrade libsoup to >2.74.2. Iirc thats the highest version number which can produce 4.0. Anything above will either error out, or if you build webkit with `-DUSE_SOUP2=OFF`, you get 4.1 instead of 4.0. Its uses the same source as you might've already figured out.
5.0 however uses its own branch.
Its a little confusing with several version numbers at the same time.

> Currently, my user experience with 2.36 is pretty buggy, which renders Vimb unstable - which is a shame. If 4.1 is doing better, I'd probably try to tackle this, given @fanglingsu 's approval.

Rendering issues with webkit browsers isnt something new, that seems to be an inherent issue with all of them (atleast the ones ive used).
Ive been using `surf` and `wywb` for some time now with 4.1, and I cant say I noticed any noticable differences. I mainly use `surf`, which has its own set of problems, that might not be present for other browsers at all. I personally dont have too much issues with the rendering, as I get by with less than most.
The only benefit that comes to mind would be compability. 

[Wyeb](https://github.com/jun7/wyeb) has previously made changes to be compatible with libsoup3, you can  view the issue [here](https://github.com/jun7/wyeb/issues/49) if its of any help.

**Comment by machinedgod** [comment]
It _seems_ like the upgrade wouldn't be something more heavy than just grinding through compilation errors and adjusting the API.
I'll try to tackle it this weekend, might be a fun project, and it'd be nice to have a support - I would _presume_ at least that higher version library would have less bugs.

**Comment by hovercats** [comment]
Sounds about right.
Sounds good! Looking forward to seeing the patch :D

**Comment by hovercats** [comment]
any progress on this?

**Comment by machinedgod** [comment]
Oh lord this completely fell off my radar!
Will have to pick it up again come weekend! Sorry!

**Comment by hovercats** [comment]
looking forward to it :D

**Comment by fanglingsu** [comment]
This issue is solved by #727
