### ISSUE TITLE
feature: hide the scroll bar

### ISSUE THREAD

**Issue by MehrunAskrnzhad** [fanglingsu/vimb#719]
hi, I guess this would be a good feature; as far as I know many peaple don't use scroll bars
so why don't add an option to just turn them off? more "MINIMALISTIC" looks...
 thanks fo this good browser by the way!

**Comment by Dorovich** [comment]
[already possible](https://fanglingsu.github.io/vimb/howto.html#no-scrollbar).

**Comment by MehrunAskrnzhad** [comment]
if you mean with the style.css; it's working on some websites but not all...
also having some issues playing videos on arch linux; tried reinstalling gstreamer and all gst plugins and everything but it just not plays the videos; I have the sound "sometimes" but not the video at all.

**Comment by fanglingsu** [comment]
@MehrunAskrnzhad I have following packages installed on arch linux and videos are played.
```
$ pacman -Q | grep gst
gst-libav 1.20.3-1
gst-plugins-bad 1.20.3-1
gst-plugins-bad-libs 1.20.3-1
gst-plugins-base 1.20.3-1
gst-plugins-base-libs 1.20.3-1
gst-plugins-good 1.20.3-1
gst-plugins-ugly 1.20.3-1
gstreamer 1.20.3-1
```
