### ISSUE TITLE
`G` navigates to top of vimb manual instead of bottom

### ISSUE THREAD

**Issue by cmvanb** [fanglingsu/vimb#723]
Not sure if you wish to receive issues on the HTML documentation... anyways this was very confusing for a new user.

### Steps to reproduce
Install vimb.
Run vimb.
Navigate to vimb manual at `https://fanglingsu.github.io/vimb/`.
Note that `G` scrolls to top of page, not bottom.

### Expected behaviour
`G` should scroll to bottom of page.

### Actual behaviour
`G` scrolls to top of page on the vimb manual page. This must be an interaction between the vimb manual HTML and vimb, it works fine on other websites.

###
```
vimb --bug-info
Version:         3.6.0
WebKit compile:  2.34.6
WebKit run:      2.38.0
GTK compile:     3.24.33
GTK run:         3.24.34
libsoup compile: 2.74.2
libsoup run:     2.74.2
Extension dir:   /usr/lib/vimb
```

```
uname -a
Linux workstation 5.19.13-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 04 Oct 2022 14:36:58 +0000 x86_64 GNU/Linux
```

**Comment by fanglingsu** [comment]
@cmvanb Thank you for reporting this issue. This seems to be related to the `document.body.scrollHeight` used to get the heiht of the whole page. On the vimb page this is 0. For this `document.documentElement.scrollHeight` would work but not for other sites like https://www.jetbrains.com/help/idea/shared-indexes.html

So I assume we should use morde js code to get the page height properly.

**Comment by fanglingsu** [comment]
@cmvanb I use the more sophisticated approach to get the document length now.
