### ISSUE TITLE
Several messengers causing webview to crash

### ISSUE THREAD

**Issue by fluentpwn** [fanglingsu/vimb#724]
Vimb:
```
Version:         3.6.0
WebKit compile:  2.26.4
WebKit run:      2.38.1
GTK compile:     3.24.13
GTK run:         3.24.34
libsoup compile: 2.66.4
libsoup run:     2.74.0
Extension dir:   /usr/lib/vimb
```
System(`inxi --full --system`):
```
System:
  Host: fluentvoid Kernel: 6.0.11_1 arch: x86_64 bits: 64 Desktop: dwm v: 6.4
    Distro: Void Linux
Info:
  Processes: 290 Uptime: 2d 20h 48m Memory: 7.12 GiB used: 3.7 GiB (51.9%)
  Shell: mksh inxi: 3.3.23
```

### Steps to reproduce
1. Login in Discord(https://discord.com/app after login) / click "Login" or "Open Cinny" on Cinny(https://app.cinny.in) / open web-browser Telegram(https://web.telegram.org/z)
### Expected behaviour
Pages to load
### Actual behaviour
`Webview Crashed on <link>` in browser;
```
(WebKitWebProcess:24524): GLib-GObject-WARNING **: 15:26:07.132: invalid (NULL) pointer instance

(WebKitWebProcess:24524): GLib-GObject-CRITICAL **: 15:26:07.132: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE
(instance)' failed
``` 
in terminal after every crash

Same behaviour is seen in surf, just with the crash later on.

**Comment by fluentpwn** [comment]
After trying to compile a newer version webkit(failed) and installing a whole bunch of libraries, I opened vimb and it worked. Not sure which library it was though, probably libsoup3

**Comment by josephkerkhof** [comment]
@fluentpwn I am having this exact same critical error. Here are my logs:

```
(WebKitWebProcess:48864): GLib-GObject-CRITICAL **: 17:03:21.592: invalid (NULL) pointer instance

(WebKitWebProcess:48864): GLib-GObject-CRITICAL **: 17:03:21.592: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

Do you have any recollection on how you resolved this problem? I'm unfamiliar with gstreamer.

For what it's worth, I consistently get this error when opening `youtube.com`.
