### ISSUE TITLE
can't navigate on github.com

### ISSUE THREAD

**Issue by tyjak** [fanglingsu/vimb#733]
Version:         3.6.0
WebKit compile:  2.34.6
WebKit run:      2.38.5
GTK compile:     3.24.33
GTK run:         3.24.37
libsoup compile: 2.74.2
libsoup run:     2.74.3
Extension dir:   /usr/lib/vimb

### Steps to reproduce

Go to https://github.com

### Expected behaviour

Could navigate in the website

### Actual behaviour

Can't use vimb on github.com, except the web inspector where I see a crazy amount of JS error being processed.

the errors : 

`Unhandled Promisevimb Rejection: TypeError: undefined is not an object (evaluating 'navigator.clipboard.read')`

Tried also with default configuration, same behavior... And tried to an other computer same error.

I'm on archlinux, with wm i3-wm on both computers. (Kernel: x86_64 Linux 6.2.2-arch2-1)

**Comment by fictitiousexistence** [comment]
https://bugs.webkit.org/show_bug.cgi?id=253793
https://github.com/orgs/community/discussions/49755

If you add: `navigator.clipboard = {};` to a userscript it helps.

**Comment by dinkocar** [comment]
After you upgrade to webkit 2.40 it will work again, at least it worked for me on Manjaro. (Writing this form vimb;))

**Comment by tyjak** [comment]
@dinkocar Thank you it worked now with webkit 2.40 for me :)
