### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by thyssentishman** [fanglingsu/vimb#741]
Hi! Any chance of a new release coming soon? Some issues I've been having with the latest release have feen fixed already e.g. keys in incognito mode. I use OpenBSD and we mostly only port/package releases. I would love to have it updated.

Thank you :)

**Comment by fanglingsu** [comment]
@thyssentishman I'll try my best release next version soon.

**Comment by thyssentishman** [comment]
@fanglingsu Thank you very much! :)

**Comment by thyssentishman** [comment]
Did you perhaps forget to bump the version in the Makefile? 

Aside from that, thank you for the release! :)

**Comment by fanglingsu** [comment]
@thyssentishman Thank you for the hint. I bumped the version in makefile now.
