### ISSUE TITLE
`vimb --version` and `vimb --bug-info` say `3.6.0` even though I'm using 3.7.0

### ISSUE THREAD

**Issue by falsifian** [fanglingsu/vimb#743]
### Steps to reproduce

Install vimb 3.7.0. (I'm using openbsd-current on amd64.) Then run `vimb --version`.

### Expected behaviour

I see version 3.7.0.

### Actual behaviour

```
$ vimb --version
vimb, version 3.6.0
```

I'm fairly sure I'm using 3.7.0. The OpenBSD package system says so, and in vimb, `:sh echo $VIMB_SELECTION` shows the current selection and I think that feature was added in 3.7.0.

For what it's worth:
```
$ vimb --bug-info
Version:         3.6.0
WebKit compile:  2.40.2
WebKit run:      2.40.2
GTK compile:     3.24.38
GTK run:         3.24.38
libsoup compile: 3.4.2
libsoup run:     3.4.2
Extension dir:   /usr/local/lib/vimb
```

**Comment by fanglingsu** [comment]
@falsifian You caught me. I missed changing the vesion number in Makefile and made the change e442041 after the tag was created.
