### ISSUE TITLE
Gitlab says the browser is out of date (Cloudflare)

### ISSUE THREAD

**Issue by mihalyr** [fanglingsu/vimb#763]
### Steps to reproduce

Go to https://gitlab.com/users/sign_in

### Expected behaviour

The page loads

### Actual behaviour

![image](https://github.com/fanglingsu/vimb/assets/26523902/6fb4a08b-6775-42ea-a846-f8a3903a4936)

When I click on "More information" it crashes...

![image](https://github.com/fanglingsu/vimb/assets/26523902/2d0f5d25-c894-4bfb-ac01-a8438151a6d7)

And also just going to `https://gitlab.com` crashes

![image](https://github.com/fanglingsu/vimb/assets/26523902/343c33f8-340f-4691-b7bd-b40b4e567361)

**Comment by mihalyr** [comment]
I fixed the `Webview Crashed` issue, it was a missing dependency

I installed the package with `dnf install vimb` but it seems it didn't install the required `libglvnd-gles` library (GLES support for libglvnd). 

This fixed opening `https://about.gitlab.com` and also fixed opening the "More information" link now which shows:

![image](https://github.com/fanglingsu/vimb/assets/26523902/502f3d47-fe47-429c-8e4a-1f330b94656c)

So it might not be a bug in the browser, but Cloudflare blocking browsers they don't support...

**Comment by mihalyr** [comment]
I still see the following when I try to open the sign in page:

```
(vimb:240265): Gdk-CRITICAL **: 14:31:58.102: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed
```

I'm using Wayland here, but I do have Xwayland.

**Comment by dinkocar** [comment]
You have to add GDK_BACKEND=x11 if you want to use Xwayland like this

command line:
GDK_BACKEND=x11 vimb

.desktop file:
env GDK_BACKEND=x11 vimb %U

**Comment by mihalyr** [comment]
I tried that but still didn't work. Setting `GDK_BACKEND=x11` does get rid of that `Gdk-CRITICAL` warning from the logs, but the website still won't work. It seems the two things aren't related. 

![image](https://github.com/fanglingsu/vimb/assets/26523902/5b9c8c60-cb73-48a1-819b-fe10c7f9da10)

**Comment by cdlscpmv** [comment]
What version of `webkit2gtk` are you using? The page works fine for me with `webkit2gtk-2.42.5`.

**Comment by dinkocar** [comment]
Also try setting user agent like this (in config file):
set user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15

**Comment by mihalyr** [comment]
> What version of `webkit2gtk` are you using? The page works fine for me with `webkit2gtk-2.42.5`.

It seems, that I have the same version as you do.

```
(fedora-toolbox-39) ➜  ~ rpm -qa | grep -i webkit
webkit2gtk4.0-2.42.5-1.fc39.x86_64
```

> Also try setting user agent like this (in config file):
set user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15

@dinkocar thank you! this was it. should've thought about this before

This is working now:

```
GDK_BACKEND=x11 vimb \
    --cmd 'set user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15' \
    https://gitlab.com/users/sign_in
```

Thanks everyone!
